Veins: veins::BaseDecider Class Reference
veins::BaseDecider Class Reference
Provides some base functionality for most common deciders.
#include <BaseDecider.h>
Public Types
enum BaseDeciderControlKinds { PACKET_DROPPED = 22100, LAST_BASE_DECIDER_CONTROL_KIND }
The kinds of ControlMessages this Decider sends.
Public Member Functions
BaseDecider (cComponent *owner, DeciderToPhyInterface *phy, double minPowerLevel, int myIndex)
Initializes the decider with the passed values.
~BaseDecider () override
simtime_t processSignal (AirFrame *frame) override
Processes an AirFrame given by the PhyLayer.
Public Member Functions inherited from veins::Decider
Decider (cComponent *owner, DeciderToPhyInterface *phy)
Initializes the Decider with a pointer to its PhyLayer.
virtual ~Decider ()
virtual void finish ()
Method to be called by an OMNeT-module during its own finish(), to enable a decider to do some things.
virtual void channelChanged (int newChannel)
Called by phy layer to indicate that the channel this radio currently listens to has changed.
virtual void switchToTx ()
Notifies the decider that phy layer is starting a transmission.
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Types
enum SignalState { NEW, EXPECT_HEADER, EXPECT_END }
The current state of processing for a signal.
typedef std::pair< AirFrame *, int > ReceivedSignal
Pair of a AirFrame and the state it is in.
Protected Types inherited from veins::Decider
using AirFrameVector = DeciderToPhyInterface::AirFrameVector
Defines what an AirFrameVector shall be here.
Protected Member Functions
virtual simtime_t processNewSignal (AirFrame *frame)
Processes a new Signal.
virtual simtime_t processSignalHeader (AirFrame *frame)
Processes the end of the header of a received Signal.
virtual simtime_t processSignalEnd (AirFrame *frame)
Processes the end of a received Signal.
virtual simtime_t processUnknownSignal (AirFrame *frame)
Processes any Signal for which no state could be found.
virtual int getSignalState (AirFrame *frame)
Returns the SignalState for the passed AirFrame.
virtual void setChannelIdleStatus (bool isIdle)
Changes the "isIdle"-status to the passed value.
virtual void getChannelInfo (simtime_t_cref start, simtime_t_cref end, AirFrameVector &out)
Collects the AirFrame on the channel during the passed interval.
Protected Attributes
double minPowerLevel
minPowerLevel value for receiving an AirFrame
ReceivedSignal currentSignal
pointer to the currently received AirFrame
bool isChannelIdle
Stores the idle state of the channel.
int myIndex
index for this Decider-instance given by Phy-Layer (mostly Host-index)
Protected Attributes inherited from veins::Decider
DeciderToPhyInterface * phy
A pointer to the physical layer of this Decider.
const simtime_t notAgain
simtime that tells the Phy-Layer not to pass an AirFrame again
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Provides some base functionality for most common deciders.
Forwards the AirFrame from "processSignal" to "processNewSignal", "processSignalHeader" or "processSignalEnd" depending on the state for that AirFrame returned by "getSignalState".
If a subclassing Decider only tries to receive one signal at a time it can use BaseDeciders "currentSignal" member which is a pair of the signal to receive and the state for that signal. The state is then used by BaseDeciders "getSignalState" to decide to which "process***" method to forward the signal. If a subclassing Decider needs states for more than one Signal it has to store these states by itself and should probably override the "getSignalState" method.
Member Typedef Documentation
ReceivedSignal
typedef std::pair<AirFrame*, int> veins::BaseDecider::ReceivedSignal protected
Pair of a AirFrame and the state it is in.
Member Enumeration Documentation
BaseDeciderControlKinds
enum veins::BaseDecider::BaseDeciderControlKinds
The kinds of ControlMessages this Decider sends.
Sub-classing decider should begin their own kind enumeration at the value of "LAST_BASE_DECIDER_CONTROL_KIND".
Enumerator
PACKET_DROPPED
The phy has recognized a bit error in the packet.
LAST_BASE_DECIDER_CONTROL_KIND
Sub-classing decider should begin their own kinds at this value.
{
         /** @brief The phy has recognized a bit error in the packet.*/
         PACKET_DROPPED = 22100,
         /** @brief Sub-classing decider should begin their own kinds at this
          * value.*/
         LAST_BASE_DECIDER_CONTROL_KIND
     };
SignalState
enum veins::BaseDecider::SignalState protected
The current state of processing for a signal.
Enumerator
NEW
Signal is received the first time.
EXPECT_HEADER
Waiting for the header of the signal.
EXPECT_END
Waiting for the end of the signal.
                      {
         /** @brief Signal is received the first time. */
         NEW,
         /** @brief Waiting for the header of the signal. */
         EXPECT_HEADER,
         /** @brief Waiting for the end of the signal. */
         EXPECT_END,
     };
Constructor & Destructor Documentation
BaseDecider()
veins::BaseDecider::BaseDecider (cComponent * owner, DeciderToPhyInterface * phy, double minPowerLevel, int myIndex) inline
Initializes the decider with the passed values.
Needs a pointer to its physical layer, the minPowerLevel, and the index of the host.
         : Decider(owner, phy)
         , minPowerLevel(minPowerLevel)
         , isChannelIdle(true)
         , myIndex(myIndex)
     {
         currentSignal.first = 0;
         currentSignal.second = NEW;
     }
~BaseDecider()
veins::BaseDecider::~BaseDecider () inline override
     {
     }
Member Function Documentation
getChannelInfo()
void BaseDecider::getChannelInfo (simtime_t_cref start, simtime_t_cref end, AirFrameVector & out) protected virtual
Collects the AirFrame on the channel during the passed interval.
Forwards to DeciderToPhyInterfaces "getChannelInfo" method. Subclassing deciders can override this method to filter the returned AirFrames for their own criteria, for example by removing AirFrames on another not interferring channel.
Parameters
start The start of the interval to collect AirFrames from.
end The end of the interval to collect AirFrames from.
out The output vector in which to put the AirFrames.
References veins::DeciderToPhyInterface::getChannelInfo(), and veins::Decider::phy.
Referenced by veins::Decider80211p::cca(), and veins::Decider80211p::checkIfSignalOk().
 {
     phy->getChannelInfo(start, end, out);
 }
getSignalState()
int BaseDecider::getSignalState (AirFrame * frame) protected virtual
Returns the SignalState for the passed AirFrame.
The default implementation checks if the passed AirFrame is the "currentSignal" and returns its state or if not "NEW".
Reimplemented in veins::Decider80211p.
References currentSignal, and NEW.
Referenced by processSignal().
 {
     if (frame == currentSignal.first) return currentSignal.second;
     return NEW;
 }
processNewSignal()
simtime_t BaseDecider::processNewSignal (AirFrame * frame) protected virtual
Processes a new Signal.
Returns the time it wants to handle the signal again.
Default implementation checks if the signals receiving power is above the minPowerLevel of the radio and we are not already trying to receive another AirFrame. If thats the case it waits for the end of the signal.
Reimplemented in veins::Decider80211p.
References currentSignal, EXPECT_END, veins::Signal::getMax(), veins::Signal::getReceptionEnd(), minPowerLevel, veins::Decider::notAgain, and setChannelIdleStatus().
Referenced by processSignal().
 {
     if (currentSignal.first != 0) {
         EV_TRACE << "Already receiving another AirFrame!" << endl;
         return notAgain;
     }
     // get the receiving power of the Signal at start-time
     Signal& signal = frame->getSignal();
     double recvPower = signal.getMax();
     // check whether signal is strong enough to receive
     if (recvPower < minPowerLevel) {
         EV_TRACE << "Signal is too weak (" << recvPower << " < " << minPowerLevel << ") -> do not receive." << endl;
         // Signal too weak, we can't receive it, tell PhyLayer that we don't want it again
         return notAgain;
     }
     // Signal is strong enough, receive this Signal and schedule it
     EV_TRACE << "Signal is strong enough (" << recvPower << " > " << minPowerLevel << ") -> Trying to receive AirFrame." << endl;
     currentSignal.first = frame;
     currentSignal.second = EXPECT_END;
     // channel turned busy
     setChannelIdleStatus(false);
     return signal.getReceptionEnd();
 }
processSignal()
simtime_t BaseDecider::processSignal (AirFrame * frame) override virtual
Processes an AirFrame given by the PhyLayer.
Returns the time point when the decider wants to be given the AirFrame again.
Reimplemented from veins::Decider.
References EXPECT_END, EXPECT_HEADER, getSignalState(), NEW, processNewSignal(), processSignalEnd(), processSignalHeader(), and processUnknownSignal().
 {
     ASSERT(frame);
     EV_TRACE << "Processing AirFrame..." << endl;
     switch (getSignalState(frame)) {
     case NEW:
         return processNewSignal(frame);
     case EXPECT_HEADER:
         return processSignalHeader(frame);
     case EXPECT_END:
         return processSignalEnd(frame);
     default:
         return processUnknownSignal(frame);
     }
 }
processSignalEnd()
simtime_t BaseDecider::processSignalEnd (AirFrame * frame) protected virtual
Processes the end of a received Signal.
Returns the time it wants to handle the signal again (most probably notAgain).
Default implementation just decides every signal as correct and passes it to the upper layer.
Reimplemented in veins::Decider80211p.
References currentSignal, veins::Decider::notAgain, veins::Decider::phy, veins::DeciderToPhyInterface::sendUp(), and setChannelIdleStatus().
Referenced by processSignal().
 {
     EV_INFO << "packet was received correctly, it is now handed to upper layer...\n";
     phy->sendUp(frame, new DeciderResult(true));
     // we have processed this AirFrame and we prepare to receive the next one
     currentSignal.first = 0;
     // channel is idle now
     setChannelIdleStatus(true);
     return notAgain;
 }
processSignalHeader()
virtual simtime_t veins::BaseDecider::processSignalHeader (AirFrame * frame) inline protected virtual
Processes the end of the header of a received Signal.
Returns the time it wants to handle the signal again.
Default implementation does not handle signal headers.
Referenced by processSignal().
     {
         throw cRuntimeError("BaseDecider does not handle Signal headers!");
         return notAgain;
     }
processUnknownSignal()
simtime_t BaseDecider::processUnknownSignal (AirFrame * frame) protected virtual
Processes any Signal for which no state could be found.
(is an error case).
References veins::Decider::notAgain.
Referenced by processSignal().
 {
     throw cRuntimeError("Unknown state for the AirFrame with ID %d", frame->getId());
     return notAgain;
 }
setChannelIdleStatus()
void BaseDecider::setChannelIdleStatus (bool isIdle) protected virtual
Changes the "isIdle"-status to the passed value.
Reimplemented in veins::Decider80211p.
References isChannelIdle.
Referenced by processNewSignal(), and processSignalEnd().
 {
     isChannelIdle = isIdle;
 }
Member Data Documentation
currentSignal
ReceivedSignal veins::BaseDecider::currentSignal protected
pointer to the currently received AirFrame
Referenced by getSignalState(), veins::Decider80211p::processNewSignal(), processNewSignal(), veins::Decider80211p::processSignalEnd(), processSignalEnd(), and veins::Decider80211p::switchToTx().
isChannelIdle
bool veins::BaseDecider::isChannelIdle protected
Stores the idle state of the channel.
Referenced by veins::Decider80211p::cca(), veins::Decider80211p::processSignalEnd(), setChannelIdleStatus(), and veins::Decider80211p::setChannelIdleStatus().
minPowerLevel
double veins::BaseDecider::minPowerLevel protected
minPowerLevel value for receiving an AirFrame
Referenced by veins::Decider80211p::processNewSignal(), and processNewSignal().
myIndex
int veins::BaseDecider::myIndex protected
index for this Decider-instance given by Phy-Layer (mostly Host-index)
The documentation for this class was generated from the following files:
BaseDecider.h
BaseDecider.cc