Veins: veins::VehicleObstacleShadowing Class Reference
veins::VehicleObstacleShadowing Class Reference
Basic implementation of a VehicleObstacleShadowing that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
#include <VehicleObstacleShadowing.h>
Public Member Functions
VehicleObstacleShadowing (cComponent *owner, VehicleObstacleControl &vehicleObstacleControl, bool useTorus, const Coord &playgroundSize)
Initializes the analogue model.
void filterSignal (Signal *signal) override
Filters a specified Signal by adding an attenuation over time to the Signal.
bool neverIncreasesPower () override
If the model never increases the power level of any signal given to filterSignal, it returns true here.
Public Member Functions inherited from veins::AnalogueModel
AnalogueModel (cComponent *owner)
virtual ~AnalogueModel ()
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Attributes
VehicleObstacleControl & vehicleObstacleControl
reference to global VehicleObstacleControl instance
const bool useTorus
Information needed about the playground.
const Coord & playgroundSize
The size of the playground.
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Basic implementation of a VehicleObstacleShadowing that uses SimplePathlossConstMapping (that is subclassed from SimpleConstMapping) as attenuation-Mapping.
Constructor & Destructor Documentation
VehicleObstacleShadowing()
VehicleObstacleShadowing::VehicleObstacleShadowing (cComponent * owner, VehicleObstacleControl & vehicleObstacleControl, bool useTorus, const Coord & playgroundSize)
Initializes the analogue model.
myMove and playgroundSize need to be valid as long as this instance exists.
The constructor needs some specific knowledge in order to create its mapping properly:
Parameters
owner pointer to the cComponent that owns this AnalogueModel
vehicleObstacleControl reference to global VehicleObstacleControl module
useTorus information about the playground the host is moving in
playgroundSize information about the playground the host is moving in
     : AnalogueModel(owner)
     , vehicleObstacleControl(vehicleObstacleControl)
     , useTorus(useTorus)
     , playgroundSize(playgroundSize)
 {
     if (useTorus) throw cRuntimeError("VehicleObstacleShadowing does not work on torus-shaped playgrounds");
 }
Member Function Documentation
filterSignal()
void VehicleObstacleShadowing::filterSignal (Signal * signal) override virtual
Filters a specified Signal by adding an attenuation over time to the Signal.
Implements veins::AnalogueModel.
References veins::Signal::at(), veins::AntennaPosition::getPositionAt(), veins::VehicleObstacleControl::getPotentialObstacles(), veins::Signal::getReceiverPoa(), veins::Signal::getSenderPoa(), veins::Signal::getSpectrum(), veins::VehicleObstacleControl::getVehicleAttenuationDZ(), veins::POA::pos, and vehicleObstacleControl.
 {
     auto senderPos = signal->getSenderPoa().pos.getPositionAt();
     auto receiverPos = signal->getReceiverPoa().pos.getPositionAt();
     auto potentialObstacles = vehicleObstacleControl.getPotentialObstacles(signal->getSenderPoa().pos, signal->getReceiverPoa().pos, *signal);
     if (potentialObstacles.size() < 1) return;
     double senderHeight = senderPos.z;
     double receiverHeight = receiverPos.z;
     potentialObstacles.insert(potentialObstacles.begin(), std::make_pair(0, senderHeight));
     potentialObstacles.emplace_back(senderPos.distance(receiverPos), receiverHeight);
     auto attenuationDB = VehicleObstacleControl::getVehicleAttenuationDZ(potentialObstacles, Signal(signal->getSpectrum()));
     EV_TRACE << "t=" << simTime() << ": Attenuation by vehicles is " << attenuationDB << std::endl;
     // convert from "dB loss" to a multiplicative factor
     Signal attenuation(attenuationDB.getSpectrum());
     for (uint16_t i = 0; i < attenuation.getNumValues(); i++) {
         attenuation.at(i) = pow(10.0, -attenuationDB.at(i) / 10.0);
     }
     *signal *= attenuation;
 }
neverIncreasesPower()
bool veins::VehicleObstacleShadowing::neverIncreasesPower () inline override virtual
If the model never increases the power level of any signal given to filterSignal, it returns true here.
This allows optimized signal handling.
Reimplemented from veins::AnalogueModel.
     {
         return true;
     }
Member Data Documentation
playgroundSize
const Coord& veins::VehicleObstacleShadowing::playgroundSize protected
The size of the playground.
useTorus
const bool veins::VehicleObstacleShadowing::useTorus protected
Information needed about the playground.
vehicleObstacleControl
VehicleObstacleControl& veins::VehicleObstacleShadowing::vehicleObstacleControl protected
reference to global VehicleObstacleControl instance
Referenced by filterSignal().
The documentation for this class was generated from the following files:
VehicleObstacleShadowing.h
VehicleObstacleShadowing.cc