Veins: veins::BaseMobility Class Reference
veins::BaseMobility Class Reference
Base module for all mobility modules.
#include <BaseMobility.h>
Public Types
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Selects how a node should behave if it reaches the edge of the playground.
enum BaseMobilityMsgKinds { MOVE_HOST = 21311, MOVE_TO_BORDER, LAST_BASE_MOBILITY_KIND }
The kind field of messages.
enum BorderHandling {
NOWHERE, X_SMALLER, X_BIGGER, Y_SMALLER,
Y_BIGGER, Z_SMALLER, Z_BIGGER
}
Specifies which border actually has been reached.
Public Member Functions
BaseMobility ()
BaseMobility (unsigned stacksize)
void handleMessage (cMessage *msg) override
This modules should only receive self-messages.
void initialize (int) override
Initializes mobility model parameters.
void finish () override
Delete dynamically allocated objects.
virtual Coord getPositionAt (simtime_t_cref stWhen) const
Returns the current position at the given simulation time.
virtual Coord getCurrentOrientation () const
virtual Coord getCurrentSpeed () const
Returns the current speed at the current simulation time.
virtual Coord getCurrentDirection () const
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Static Public Attributes
static const simsignal_t mobilityStateChangedSignal = registerSignal("org_car2x_veins_base_modules_mobilityStateChanged")
Store the category of HostMove.
Protected Member Functions
virtual int iconSizeTagToSize (const char *tag)
Maps the passed icon size tag (is) to an actual size in pixels.
virtual const char * iconSizeToTag (double size)
Maps the passed size in pixels to an appropriate icon size tag (is).
virtual void handleSelfMsg (cMessage *)
Called upon arrival of a self messages.
virtual void handleBorderMsg (cMessage *)
Called upon arrival of a border messages.
virtual void makeMove ()
Moves the host.
virtual void updatePosition ()
Update the position information for this node.
double playgroundSizeX () const
Returns the width of the playground.
double playgroundSizeY () const
Returns the height of the playground.
double playgroundSizeZ () const
Returns the height of the playground.
Coord getRandomPosition ()
Random position somewhere in the playground.
Border handling
Utility functions to handle hosts that move outside the playground
bool handleIfOutside (BorderPolicy, Coord &, Coord &, Coord &, double &)
Main border handling function.
virtual void fixIfHostGetsOutside ()
Should be redefined in subclasses.
BorderHandling checkIfOutside (Coord, Coord &)
Checks whether the host is outside the playground and returns where.
void goToBorder (BorderPolicy, BorderHandling, Coord &, Coord &)
calculate the step to reach the border
void reflectCoordinate (BorderHandling border, Coord &c)
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
void reflectIfOutside (BorderHandling, Coord &, Coord &, Coord &, double &)
Utility function to reflect the node if it goes outside the playground.
void wrapIfOutside (BorderHandling, Coord &, Coord &)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
void placeRandomlyIfOutside (Coord &)
Utility function to place the node randomly if it goes outside the playground.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
BaseWorldUtility * world
Pointer to BaseWorldUtility – these two must know each other.
Move move
Stores the current position and move pattern of the host.
simtime_t updateInterval
Time interval (in seconds) to update the hosts position.
cMessage * moveMsg
Self message to trigger movement.
bool scaleNodeByDepth
Enable depth dependent scaling of nodes when 3d and tkenv is used.
double playgroundScaleX
Scaling of the playground in X direction.
double playgroundScaleY
Scaling of the playground in Y direction.
double origDisplayWidth
The original width the node is displayed width.
double origDisplayHeight
The original height the node is displayed width.
double origIconSize
The original size of the icon of the node.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Base module for all mobility modules.
It does not provide mobility at all, so you can use it if you only want to simulate static networks.
BaseMobility provides random placement of hosts and display updates. Change notifications about position changes are also posted to the Blackboard.
Another service provided by BaseMobility is border handling. If a host wants to move outside the playground, this situation has to be handled somehow. BaseMobility provides handling for the 4 most common ways for that: reflection, wrapping, random placement and raising an error. The only thing you have to do is to specify your desired border handling in fixIfHostGetsOutside and call it in makeMove.
For most mobility modules the only two functions you need to implement to define your own mobility module are makeMove and fixIfHostGetsOutside..
This file contains 3D implementations from Michael Swigulski.
Author
Daniel Willkomm, Andras Varga
Member Enumeration Documentation
BaseMobilityMsgKinds
enum veins::BaseMobility::BaseMobilityMsgKinds
The kind field of messages.
that are used internally by this class have one of these values
Enumerator
MOVE_HOST
MOVE_TO_BORDER
LAST_BASE_MOBILITY_KIND
Stores the id on which classes extending BaseMobility should continue their own kinds.
{
         MOVE_HOST = 21311,
         MOVE_TO_BORDER,
         /** Stores the id on which classes extending BaseMobility should
          * continue their own kinds.*/
         LAST_BASE_MOBILITY_KIND,
     };
BorderHandling
enum veins::BaseMobility::BorderHandling
Specifies which border actually has been reached.
Enumerator
NOWHERE
not outside the playground
X_SMALLER
x smaller than 0
X_BIGGER
x bigger or equal than playground size
Y_SMALLER
y smaller than 0
Y_BIGGER
y bigger or equal than playground size
Z_SMALLER
z smaller than 0
Z_BIGGER
z bigger or equal than playground size
{
         NOWHERE, ///< not outside the playground
         X_SMALLER, ///< x smaller than 0
         X_BIGGER, ///< x bigger or equal than playground size
         Y_SMALLER, ///< y smaller than 0
         Y_BIGGER, ///< y bigger or equal than playground size
         Z_SMALLER, ///< z smaller than 0
         Z_BIGGER ///< z bigger or equal than playground size
     };
BorderPolicy
enum veins::BaseMobility::BorderPolicy
Selects how a node should behave if it reaches the edge of the playground.
See also
handleIfOutside()
Enumerator
REFLECT
reflect off the wall
WRAP
reappear at the opposite edge (torus)
PLACERANDOMLY
placed at a randomly chosen position on the playground
RAISEERROR
stop the simulation with error
                       {
         REFLECT, ///< reflect off the wall
         WRAP, ///< reappear at the opposite edge (torus)
         PLACERANDOMLY, ///< placed at a randomly chosen position on the playground
         RAISEERROR ///< stop the simulation with error
     };
Constructor & Destructor Documentation
BaseMobility() [1/2]
BaseMobility::BaseMobility ()
     : BatteryAccess()
     , move()
     , playgroundScaleX(1)
     , playgroundScaleY(1)
     , origDisplayWidth(0)
     , origDisplayHeight(0)
     , origIconSize(0)
 {
 }
BaseMobility() [2/2]
BaseMobility::BaseMobility (unsigned stacksize)
     : BatteryAccess(stacksize)
     , move()
     , playgroundScaleX(1)
     , playgroundScaleY(1)
     , origDisplayWidth(0)
     , origDisplayHeight(0)
     , origIconSize(0)
 {
 }
Member Function Documentation
checkIfOutside()
BaseMobility::BorderHandling BaseMobility::checkIfOutside (Coord targetPos, Coord & borderStep) protected
Checks whether the host is outside the playground and returns where.
Checks whether the host moved outside and return the border it crossed.
Additionally the calculation of the step to reach the border is started.
References veins::Move::getDirection(), veins::Move::getStartPos(), veins::Coord::info(), move, NOWHERE, playgroundSizeX(), playgroundSizeY(), playgroundSizeZ(), veins::BaseWorldUtility::use2D(), world, veins::Coord::x, X_BIGGER, X_SMALLER, veins::Coord::y, Y_BIGGER, Y_SMALLER, veins::Coord::z, Z_BIGGER, and Z_SMALLER.
Referenced by handleIfOutside().
 {
     BorderHandling outside = NOWHERE;
     // Testing x-value
     if (targetPos.x < 0) {
         borderStep.x = (-move.getStartPos().x);
         outside = X_SMALLER;
     }
     else if (targetPos.x >= playgroundSizeX()) {
         borderStep.x = (playgroundSizeX() - move.getStartPos().x);
         outside = X_BIGGER;
     }
     // Testing y-value
     if (targetPos.y < 0) {
         borderStep.y = (-move.getStartPos().y);
         if (outside == NOWHERE || fabs(borderStep.x / move.getDirection().x) > fabs(borderStep.y / move.getDirection().y)) {
             outside = Y_SMALLER;
         }
     }
     else if (targetPos.y >= playgroundSizeY()) {
         borderStep.y = (playgroundSizeY() - move.getStartPos().y);
         if (outside == NOWHERE || fabs(borderStep.x / move.getDirection().x) > fabs(borderStep.y / move.getDirection().y)) {
             outside = Y_BIGGER;
         }
     }
     // Testing z-value
     if (!world->use2D()) {
         // going to reach the lower z-border
         if (targetPos.z < 0) {
             borderStep.z = (-move.getStartPos().z);
             // no border reached so far
             if (outside == NOWHERE) {
                 outside = Z_SMALLER;
             }
             // an y-border is reached earliest so far, test whether z-border
             // is reached even earlier
             else if ((outside == Y_SMALLER || outside == Y_BIGGER) && fabs(borderStep.y / move.getDirection().y) > fabs(borderStep.z / move.getDirection().z)) {
                 outside = Z_SMALLER;
             }
             // an x-border is reached earliest so far, test whether z-border
             // is reached even earlier
             else if ((outside == X_SMALLER || outside == X_BIGGER) && fabs(borderStep.x / move.getDirection().x) > fabs(borderStep.z / move.getDirection().z)) {
                 outside = Z_SMALLER;
             }
         }
         // going to reach the upper z-border
         else if (targetPos.z >= playgroundSizeZ()) {
             borderStep.z = (playgroundSizeZ() - move.getStartPos().z);
             // no border reached so far
             if (outside == NOWHERE) {
                 outside = Z_BIGGER;
             }
             // an y-border is reached earliest so far, test whether z-border
             // is reached even earlier
             else if ((outside == Y_SMALLER || outside == Y_BIGGER) && fabs(borderStep.y / move.getDirection().y) > fabs(borderStep.z / move.getDirection().z)) {
                 outside = Z_BIGGER;
             }
             // an x-border is reached earliest so far, test whether z-border
             // is reached even earlier
             else if ((outside == X_SMALLER || outside == X_BIGGER) && fabs(borderStep.x / move.getDirection().x) > fabs(borderStep.z / move.getDirection().z)) {
                 outside = Z_BIGGER;
             }
         }
     }
     EV_TRACE << "checkIfOutside, outside=" << outside << " borderStep: " << borderStep.info() << endl;
     return outside;
 }
finish()
void veins::BaseMobility::finish () inline override
Delete dynamically allocated objects.
 {};
fixIfHostGetsOutside()
virtual void veins::BaseMobility::fixIfHostGetsOutside () inline protected virtual
Should be redefined in subclasses.
Should invoke handleIfOutside() and pass the references to the parameters to be modified.
Additional action after border handling (such as choosing a new target position if the BorderPolicy is PLACERANDOMLY) should be implemented here.
See also
HandleIfOutside
Reimplemented in veins::TraCIMobility, and veins::LinearMobility.
Referenced by handleBorderMsg().
     {
         throw cRuntimeError("fixIfHostGetsOutside has to be redefined by the user");
     };
getCurrentDirection()
virtual Coord veins::BaseMobility::getCurrentDirection () const inline virtual
References veins::Move::getDirection().
Referenced by veins::TraCIMobility::nextPosition().
     {
         return move.getDirection();
     }
getCurrentOrientation()
virtual Coord veins::BaseMobility::getCurrentOrientation () const inline virtual
References veins::Move::getOrientation().
Referenced by veins::MobileHostObstacle::getShape(), and veins::TraCIMobility::nextPosition().
     {
         return move.getOrientation();
     }
getCurrentSpeed()
virtual Coord veins::BaseMobility::getCurrentSpeed () const inline virtual
Returns the current speed at the current simulation time.
Reimplemented in veins::TraCIMobility.
References veins::Move::getDirection(), and veins::Move::getSpeed().
Referenced by veins::TraCIMobility::getCurrentSpeed(), and veins::TraCIMobility::getHostSpeed().
     {
         return move.getDirection() * move.getSpeed();
     }
getPositionAt()
virtual Coord veins::BaseMobility::getPositionAt (simtime_t_cref stWhen) const inline virtual
Returns the current position at the given simulation time.
References veins::Move::getPositionAt().
Referenced by veins::MobileHostObstacle::getShape(), and veins::MobileHostObstacle::maybeInBounds().
     {
         return move.getPositionAt(stWhen);
     }
getRandomPosition()
Coord veins::BaseMobility::getRandomPosition () inline protected
Random position somewhere in the playground.
DEPRECATED: Use BaseWorldUtility::getRandomPosition() instead
References veins::BaseWorldUtility::getRandomPosition().
     {
         return world->getRandomPosition();
     }
goToBorder()
void BaseMobility::goToBorder (BorderPolicy policy, BorderHandling wo, Coord & borderStep, Coord & borderStart) protected
calculate the step to reach the border
Calculate the step to reach the border. Additionally for the WRAP policy the new start position after reaching the border is calculated.
References veins::Move::getDirection(), veins::Move::getStartPos(), veins::Coord::info(), move, playgroundSizeX(), playgroundSizeY(), playgroundSizeZ(), veins::BaseWorldUtility::use2D(), world, WRAP, veins::Coord::x, X_BIGGER, X_SMALLER, veins::Coord::y, Y_BIGGER, Y_SMALLER, veins::Coord::z, Z_BIGGER, and Z_SMALLER.
Referenced by handleIfOutside().
 {
     double factor;
     EV_TRACE << "goToBorder: startPos: " << move.getStartPos().info() << " borderStep: " << borderStep.info() << " BorderPolicy: " << policy << " BorderHandling: " << wo << endl;
     switch (wo) {
     case X_SMALLER:
         factor = borderStep.x / move.getDirection().x;
         borderStep.y = (factor * move.getDirection().y);
         if (!world->use2D()) {
             borderStep.z = (factor * move.getDirection().z); // 3D case
         }
         if (policy == WRAP) {
             borderStart.x = (playgroundSizeX());
             borderStart.y = (move.getStartPos().y + borderStep.y);
             if (!world->use2D()) {
                 borderStart.z = (move.getStartPos().z + borderStep.z); // 3D case
             }
         }
         break;
     case X_BIGGER:
         factor = borderStep.x / move.getDirection().x;
         borderStep.y = (factor * move.getDirection().y);
         if (!world->use2D()) {
             borderStep.z = (factor * move.getDirection().z); // 3D case
         }
         if (policy == WRAP) {
             borderStart.x = (0);
             borderStart.y = (move.getStartPos().y + borderStep.y);
             if (!world->use2D()) {
                 borderStart.z = (move.getStartPos().z + borderStep.z); // 3D case
             }
         }
         break;
     case Y_SMALLER:
         factor = borderStep.y / move.getDirection().y;
         borderStep.x = (factor * move.getDirection().x);
         if (!world->use2D()) {
             borderStep.z = (factor * move.getDirection().z); // 3D case
         }
         if (policy == WRAP) {
             borderStart.y = (playgroundSizeY());
             borderStart.x = (move.getStartPos().x + borderStep.x);
             if (!world->use2D()) {
                 borderStart.z = (move.getStartPos().z + borderStep.z); // 3D case
             }
         }
         break;
     case Y_BIGGER:
         factor = borderStep.y / move.getDirection().y;
         borderStep.x = (factor * move.getDirection().x);
         if (!world->use2D()) {
             borderStep.z = (factor * move.getDirection().z); // 3D case
         }
         if (policy == WRAP) {
             borderStart.y = (0);
             borderStart.x = (move.getStartPos().x + borderStep.x);
             if (!world->use2D()) {
                 borderStart.z = (move.getStartPos().z + borderStep.z); // 3D case
             }
         }
         break;
     case Z_SMALLER: // here we are definitely in 3D
         factor = borderStep.z / move.getDirection().z;
         borderStep.x = (factor * move.getDirection().x);
         borderStep.y = (factor * move.getDirection().y);
         if (policy == WRAP) {
             borderStart.z = (playgroundSizeZ());
             borderStart.x = (move.getStartPos().x + borderStep.x);
             borderStart.y = (move.getStartPos().y + borderStep.y);
         }
         break;
     case Z_BIGGER: // here we are definitely in 3D
         factor = borderStep.z / move.getDirection().z;
         borderStep.x = (factor * move.getDirection().x);
         borderStep.y = (factor * move.getDirection().y);
         if (policy == WRAP) {
             borderStart.z = (0);
             borderStart.x = (move.getStartPos().x + borderStep.x);
             borderStart.y = (move.getStartPos().y + borderStep.y);
         }
         break;
     default:
         throw cRuntimeError("invalid state in goToBorder switch!");
         break;
     }
     EV_TRACE << "goToBorder: startPos: " << move.getStartPos().info() << " borderStep: " << borderStep.info() << " borderStart: " << borderStart.info() << " factor: " << factor << endl;
 }
handleBorderMsg()
void BaseMobility::handleBorderMsg (cMessage * msg) protected virtual
Called upon arrival of a border messages.
The host actually reached the border, so the startPos and startTime has to be updated.
Additionally fixIfHostGetsOutside has to be called again to catch cases where the host moved in both (x and y) direction outside the playground.
References fixIfHostGetsOutside(), veins::Move::getStartPos(), veins::Coord::info(), veins::Move::info(), move, PLACERANDOMLY, RAISEERROR, REFLECT, veins::Move::setDirectionByVector(), veins::Move::setStart(), updatePosition(), and WRAP.
Referenced by handleMessage().
 {
     EV_TRACE << "start MOVE_TO_BORDER:" << move.info() << endl;
     BorderMsg* bMsg = static_cast<BorderMsg*>(msg);
     switch (bMsg->getPolicy()) {
     case REFLECT:
         move.setStart(bMsg->getStartPos());
         move.setDirectionByVector(bMsg->getDirection());
         break;
     case WRAP:
         move.setStart(bMsg->getStartPos());
         break;
     case PLACERANDOMLY:
         move.setStart(bMsg->getStartPos());
         EV_TRACE << "new random position: " << move.getStartPos().info() << endl;
         break;
     case RAISEERROR:
         throw cRuntimeError("node moved outside the playground");
         break;
     default:
         throw cRuntimeError("Unknown BorderPolicy!");
         break;
     }
     fixIfHostGetsOutside();
     updatePosition();
     delete bMsg;
     EV_TRACE << "end MOVE_TO_BORDER:" << move.info() << endl;
 }
handleIfOutside()
bool BaseMobility::handleIfOutside (BorderPolicy policy, Coord & stepTarget, Coord & targetPos, Coord & step, double & angle) protected
Main border handling function.
This function takes the BorderPolicy and all variables to be modified in case a border is reached and invokes the appropriate action. Pass dummy variables if you do not need them.
The supported border policies are REFLECT, WRAP, PLACERANDOMLY, and RAISEERROR.
The policy and stepTarget are mandatory parameters to pass. stepTarget is used to check whether the host actually moved outside the playground.
Additional parameters to pass (in case of non atomic movements) can be targetPos (the target the host is moving to) and step (the size of a step).
Angle is the direction in which the host is moving.
Parameters
policy BorderPolicy to use
stepTarget target position of the next step of the host
targetPos target position of the host (for non atomic movement)
step step size of the host (for non atomic movement)
angle direction in which the host is moving
Returns
true if host was outside, false otherwise.
References checkIfOutside(), veins::Coord::distance(), veins::Move::getSpeed(), veins::Move::getStartPos(), goToBorder(), veins::Coord::info(), veins::Coord::length(), move, MOVE_TO_BORDER, NOWHERE, PLACERANDOMLY, placeRandomlyIfOutside(), RAISEERROR, REFLECT, reflectIfOutside(), WRAP, and wrapIfOutside().
Referenced by veins::LinearMobility::fixIfHostGetsOutside(), and veins::TraCIMobility::fixIfHostGetsOutside().
 {
     // where did the host leave the playground?
     BorderHandling wo;
     // step to reach the border
     Coord borderStep;
     wo = checkIfOutside(stepTarget, borderStep);
     // just return if the next step is not outside the playground
     if (wo == NOWHERE) return false;
     EV_TRACE << "handleIfOutside:stepTarget = " << stepTarget.info() << endl;
     // new start position after the host reaches the border
     Coord borderStart;
     // new direction the host has to move to
     Coord borderDirection;
     // time to reach the border
     simtime_t borderInterval;
     EV_TRACE << "old values: stepTarget: " << stepTarget.info() << " step: " << step.info() << " targetPos: " << targetPos.info() << " angle: " << angle << endl;
     // which border policy is to be followed
     switch (policy) {
     case REFLECT:
         reflectIfOutside(wo, stepTarget, targetPos, step, angle);
         break;
     case WRAP:
         wrapIfOutside(wo, stepTarget, targetPos);
         break;
     case PLACERANDOMLY:
         placeRandomlyIfOutside(targetPos);
         break;
     case RAISEERROR:
         break;
     }
     EV_TRACE << "new values: stepTarget: " << stepTarget.info() << " step: " << step.info() << " angle: " << angle << endl;
     // calculate the step to reach the border
     goToBorder(policy, wo, borderStep, borderStart);
     // calculate the time to reach the border
     borderInterval = (borderStep.length()) / move.getSpeed();
     // calculate new start position
     // NOTE: for WRAP this is done in goToBorder
     switch (policy) {
     case REFLECT: {
         borderStart = move.getStartPos() + borderStep;
         double d = stepTarget.distance(borderStart);
         borderDirection = (stepTarget - borderStart) / d;
         break;
     }
     case PLACERANDOMLY:
         borderStart = targetPos;
         stepTarget = targetPos;
         break;
     case WRAP:
     case RAISEERROR:
         break;
     default:
         throw cRuntimeError("unknown BorderPolicy");
         break;
     }
     EV_DEBUG << "border handled, borderStep: " << borderStep.info() << "borderStart: " << borderStart.info() << " stepTarget " << stepTarget.info() << endl;
     // create a border self message and schedule it appropriately
     BorderMsg* bMsg = new BorderMsg("borderMove", MOVE_TO_BORDER);
     bMsg->setPolicy(policy);
     bMsg->setStartPos(borderStart);
     bMsg->setDirection(borderDirection);
     scheduleAt(simTime() + borderInterval, bMsg);
     return true;
 }
handleMessage()
void BaseMobility::handleMessage (cMessage * msg) override
This modules should only receive self-messages.
Dispatches border messages to handleBorderMsg() and all other self-messages to handleSelfMsg()
References handleBorderMsg(), handleSelfMsg(), and MOVE_TO_BORDER.
 {
     if (!msg->isSelfMessage()) throw cRuntimeError("mobility modules can only receive self messages");
     if (msg->getKind() == MOVE_TO_BORDER) {
         handleBorderMsg(msg);
     }
     else {
         handleSelfMsg(msg);
     }
 }
handleSelfMsg()
void BaseMobility::handleSelfMsg (cMessage * msg) protected virtual
Called upon arrival of a self messages.
The only self message possible is to indicate a new movement. If the host is stationary this function is never called.
every time a self message arrives makeMove is called to handle the movement. Afterward updatePosition updates the position with the display.
Reimplemented in veins::TraCIMobility.
References veins::Move::getSpeed(), makeMove(), move, moveMsg, updateInterval, and updatePosition().
Referenced by handleMessage().
 {
     makeMove();
     updatePosition();
     if (!moveMsg->isScheduled() && move.getSpeed() > 0) {
         scheduleAt(simTime() + updateInterval, msg);
     }
     else {
         delete msg;
         moveMsg = nullptr;
     }
 }
iconSizeTagToSize()
int BaseMobility::iconSizeTagToSize (const char * tag) protected virtual
Maps the passed icon size tag (is) to an actual size in pixels.
Parameters
tag - the icon size tag to get the pixel size for
Returns
the size of the icon in pixels or -1 if the tag is unknown
Referenced by initialize().
 {
     if (strcmp(tag, "vs") == 0) {
         return 16;
     }
     else if (strcmp(tag, "s") == 0) {
         return 24;
     }
     else if (strcmp(tag, "n") == 0 || strcmp(tag, "") == 0) {
         return 40;
     }
     else if (strcmp(tag, "l") == 0) {
         return 60;
     }
     else if (strcmp(tag, "vl") == 0) {
         return 100;
     }
     return -1;
 }
iconSizeToTag()
const char * BaseMobility::iconSizeToTag (double size) protected virtual
Maps the passed size in pixels to an appropriate icon size tag (is).
Parameters
size - the icon size to get an appropriate tag for
Returns
an icon size tag
Referenced by updatePosition().
 {
     // returns the biggest icon smaller than the passed size (except sizes
     // smaller than the smallest icon
     if (size < 24) {
         return "vs";
     }
     else if (size < 40) {
         return "s";
     }
     else if (size < 60) {
         return "n";
     }
     else if (size < 100) {
         return "l";
     }
     else {
         return "vl";
     }
 }
initialize()
void BaseMobility::initialize (int stage) override
Initializes mobility model parameters.
Assigns a pointer to ConnectionManager and gets a pointer to its host.
Creates a random position for a host if the position is not given as a parameter in "omnetpp.ini".
Additionally the registration with ConnectionManager is done and it is assured that the position display string tag (p) exists and contains the exact (x) tag.
If the speed of the host is bigger than 0 a first MOVE_HOST self message is scheduled in stage 1
References veins::FindModule< T >::findGlobalModule(), veins::BaseModule::findHost(), veins::BaseWorldUtility::getPgs(), veins::BaseWorldUtility::getRandomPosition(), veins::Move::getSpeed(), veins::Move::getStartPos(), iconSizeTagToSize(), veins::Coord::info(), veins::BaseModule::initialize(), anonymous_namespace{BaseMobility.cc}::isInBoundary(), move, MOVE_HOST, moveMsg, origDisplayHeight, origDisplayWidth, origIconSize, playgroundScaleX, playgroundScaleY, playgroundSizeX(), playgroundSizeY(), scaleNodeByDepth, veins::Move::setDirectionByVector(), veins::Move::setOrientationByVector(), veins::Move::setSpeed(), veins::Move::setStart(), updateInterval, updatePosition(), veins::BaseWorldUtility::use2D(), world, veins::Coord::x, veins::Coord::y, veins::Coord::z, and veins::Coord::ZERO.
Referenced by veins::LinearMobility::initialize(), and veins::TraCIMobility::initialize().
 {
     BaseModule::initialize(stage);
     if (stage == 0) {
         EV_TRACE << "initializing BaseMobility stage " << stage << endl;
         hasPar("scaleNodeByDepth") ? scaleNodeByDepth = par("scaleNodeByDepth").boolValue() : scaleNodeByDepth = true;
         // get utility pointers (world and host)
         world = FindModule<BaseWorldUtility*>::findGlobalModule();
         if (world == nullptr) throw cRuntimeError("Could not find BaseWorldUtility module");
         EV_TRACE << "initializing BaseUtility stage " << stage << endl; // for node position
         if (hasPar("updateInterval")) {
             updateInterval = par("updateInterval");
         }
         else {
             updateInterval = 0;
         }
         // initialize Move parameter
         bool use2D = world->use2D();
         // initalize position with random values
         Coord pos = world->getRandomPosition();
         // read coordinates from parameters if available
         double x = hasPar("x") ? par("x").doubleValue() : -1;
         double y = hasPar("y") ? par("y").doubleValue() : -1;
         double z = hasPar("z") ? par("z").doubleValue() : -1;
         // set position with values from parameters if available
         if (x > -1) pos.x = x;
         if (y > -1) pos.y = y;
         if (!use2D && z > -1) pos.z = z;
         if (!hasPar("xOrientation") || !hasPar("yOrientation")) {
             throw cRuntimeError("Orientation coordinates in x and y direction have to specified (necessary for antenna gain calculation)");
         }
         else {
             double zOrient = hasPar("zOrientation") ? par("zOrientation").doubleValue() : 0;
             Coord orient(par("xOrientation").doubleValue(), par("yOrientation").doubleValue(), zOrient);
             move.setOrientationByVector(orient);
         }
         // set start-position and start-time (i.e. current simulation-time) of the Move
         move.setStart(pos);
         EV_TRACE << "start pos: " << move.getStartPos().info() << endl;
         // check whether position is within the playground
         if (!isInBoundary(move.getStartPos(), Coord::ZERO, *world->getPgs())) {
             throw cRuntimeError("node position specified in omnetpp.ini exceeds playgroundsize");
         }
         // set speed and direction of the Move
         move.setSpeed(0);
         move.setDirectionByVector(Coord::ZERO);
     }
     else if (stage == 1) {
         EV_TRACE << "initializing BaseMobility stage " << stage << endl;
         // get playground scaling
         if (world->getParentModule() != nullptr) {
             const cDisplayString& dispWorldOwner = world->getParentModule()->getDisplayString();
             if (dispWorldOwner.containsTag("bgb")) {
                 double origPGWidth = 0.0;
                 double origPGHeight = 0.0;
                 // normally this should be equal to playground size
                 std::istringstream(dispWorldOwner.getTagArg("bgb", 0)) >> origPGWidth;
                 std::istringstream(dispWorldOwner.getTagArg("bgb", 1)) >> origPGHeight;
                 // bgb of zero means size isn't set manually
                 if (origPGWidth > 0) {
                     playgroundScaleX = origPGWidth / playgroundSizeX();
                 }
                 if (origPGHeight > 0) {
                     playgroundScaleY = origPGHeight / playgroundSizeY();
                 }
             }
         }
         // get original display of host
         cDisplayString& disp = findHost()->getDisplayString();
         // get host width and height
         if (disp.containsTag("b")) {
             std::istringstream(disp.getTagArg("b", 0)) >> origDisplayWidth;
             std::istringstream(disp.getTagArg("b", 1)) >> origDisplayHeight;
         }
         // get hosts icon size
         if (disp.containsTag("i")) {
             // choose a appropriate icon size (only if a icon is specified)
             origIconSize = iconSizeTagToSize(disp.getTagArg("is", 0));
         }
         // print new host position on the screen and update bb info
         updatePosition();
         if (move.getSpeed() > 0 && updateInterval > 0) {
             EV_TRACE << "Host is moving, speed=" << move.getSpeed() << " updateInterval=" << updateInterval << endl;
             moveMsg = new cMessage("move", MOVE_HOST);
             // host moves the first time after some random delay to avoid synchronized movements
             scheduleAt(simTime() + uniform(0, updateInterval), moveMsg);
         }
     }
 }
makeMove()
virtual void veins::BaseMobility::makeMove () inline protected virtual
Moves the host.
This function is called every time a MOVE_HOST self message arrives. Here you can define the movement pattern for your host.
You should call fixIfHostGetsOutside here for border handling
Reimplemented in veins::LinearMobility.
Referenced by handleSelfMsg().
     {
         throw cRuntimeError("BaseMobility does not move the host");
     };
placeRandomlyIfOutside()
void BaseMobility::placeRandomlyIfOutside (Coord & targetPos) protected
Utility function to place the node randomly if it goes outside the playground.
Start the host at a new random position. Here the target position is set to the new start position.
You have to define a new target postion in fixIfHostGetsOutside to keep the host moving.
References veins::BaseWorldUtility::getRandomPosition(), and world.
Referenced by handleIfOutside().
 {
     targetPos = world->getRandomPosition();
 }
playgroundSizeX()
double veins::BaseMobility::playgroundSizeX () const inline protected
Returns the width of the playground.
References veins::BaseWorldUtility::getPgs(), and veins::Coord::x.
Referenced by checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), initialize(), reflectCoordinate(), and wrapIfOutside().
     {
         return world->getPgs()->x;
     }
playgroundSizeY()
double veins::BaseMobility::playgroundSizeY () const inline protected
Returns the height of the playground.
References veins::BaseWorldUtility::getPgs(), and veins::Coord::y.
Referenced by checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), initialize(), reflectCoordinate(), and wrapIfOutside().
     {
         return world->getPgs()->y;
     }
playgroundSizeZ()
double veins::BaseMobility::playgroundSizeZ () const inline protected
Returns the height of the playground.
References veins::BaseWorldUtility::getPgs(), and veins::Coord::z.
Referenced by checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), reflectCoordinate(), updatePosition(), and wrapIfOutside().
     {
         return world->getPgs()->z;
     }
reflectCoordinate()
void BaseMobility::reflectCoordinate (BorderHandling border, Coord & c) protected
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
Helper function for BaseMobility::reflectIfOutside().
Reflects a given coordinate according to the given BorderHandling.
References NOWHERE, playgroundSizeX(), playgroundSizeY(), playgroundSizeZ(), veins::Coord::x, X_BIGGER, X_SMALLER, veins::Coord::y, Y_BIGGER, Y_SMALLER, veins::Coord::z, Z_BIGGER, and Z_SMALLER.
Referenced by reflectIfOutside().
 {
     switch (border) {
     case X_SMALLER:
         c.x = (-c.x);
         break;
     case X_BIGGER:
         c.x = (2 * playgroundSizeX() - c.x);
         break;
     case Y_SMALLER:
         c.y = (-c.y);
         break;
     case Y_BIGGER:
         c.y = (2 * playgroundSizeY() - c.y);
         break;
     case Z_SMALLER:
         c.z = (-c.z);
         break;
     case Z_BIGGER:
         c.z = (2 * playgroundSizeZ() - c.z);
         break;
     case NOWHERE:
     default:
         throw cRuntimeError("wrong border handling case!");
         break;
     }
 }
reflectIfOutside()
void BaseMobility::reflectIfOutside (BorderHandling wo, Coord & stepTarget, Coord & targetPos, Coord & step, double & angle) protected
Utility function to reflect the node if it goes outside the playground.
Reflects the host from the playground border.
This function can update the target position, the step (for non atomic movements) and the angle.
Parameters
wo defines the border at which to reflect
stepTarget target position of the current step of the host
targetPos target position of the host (for non atomic movements)
step step size and direction of the host (for non atomic movements)
angle direction to which the host is moving
References NOWHERE, reflectCoordinate(), veins::Coord::x, X_BIGGER, X_SMALLER, veins::Coord::y, Y_BIGGER, Y_SMALLER, veins::Coord::z, Z_BIGGER, and Z_SMALLER.
Referenced by handleIfOutside().
 {
     reflectCoordinate(wo, targetPos);
     reflectCoordinate(wo, stepTarget);
     switch (wo) {
     case X_SMALLER:
     case X_BIGGER:
         step.x = (-step.x);
         angle = 180 - angle;
         break;
     case Y_SMALLER:
     case Y_BIGGER:
         step.y = (-step.y);
         angle = -angle;
         break;
     case Z_SMALLER:
     case Z_BIGGER:
         step.z = (-step.z);
         angle = -angle;
         break;
     case NOWHERE:
     default:
         throw cRuntimeError("wrong border handling case!");
         break;
     }
 }
updatePosition()
void BaseMobility::updatePosition () protected virtual
Update the position information for this node.
This function tells the Blackboard that the position has changed, and it also moves the host's icon to the new position on the screen.
This function has to be called every time the position of the host changes!
References veins::BaseModule::findHost(), veins::Move::getStartPos(), iconSizeToTag(), veins::Move::info(), mobilityStateChangedSignal, move, origDisplayHeight, origDisplayWidth, origIconSize, playgroundScaleX, playgroundScaleY, playgroundSizeZ(), scaleNodeByDepth, veins::BaseWorldUtility::use2D(), world, veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by veins::TraCIMobility::changePosition(), handleBorderMsg(), handleSelfMsg(), and initialize().
 {
     EV_DEBUG << "updatePosition: " << move.info() << endl;
     // publish the the new move
     emit(mobilityStateChangedSignal, this);
     if (hasGUI()) {
         std::ostringstream osDisplayTag;
 #ifdef __APPLE__
         const int iPrecis = 0;
 #else
         const int iPrecis = 5;
 #endif
         cDisplayString& disp = findHost()->getDisplayString();
         // setup output stream
         osDisplayTag << std::fixed;
         osDisplayTag.precision(iPrecis);
         if (playgroundScaleX != 1.0) {
             osDisplayTag << (move.getStartPos().x * playgroundScaleX);
         }
         else {
             osDisplayTag << (move.getStartPos().x);
         }
         disp.setTagArg("p", 0, osDisplayTag.str().data());
         osDisplayTag.str(""); // reset
         if (playgroundScaleY != 1.0) {
             osDisplayTag << (move.getStartPos().y * playgroundScaleY);
         }
         else {
             osDisplayTag << (move.getStartPos().y);
         }
         disp.setTagArg("p", 1, osDisplayTag.str().data());
         if (!world->use2D() && scaleNodeByDepth) {
             const double minScale = 0.25;
             const double maxScale = 1.0;
             // scale host dependent on their z coordinate to simulate a depth
             // effect
             // z-coordinate of zero maps to a scale of maxScale (very close)
             // z-coordinate of playground size z maps to size of minScale (far away)
             double depthScale = minScale + (maxScale - minScale) * (1.0 - move.getStartPos().z / playgroundSizeZ());
             if (origDisplayWidth > 0.0 && origDisplayHeight > 0.0) {
                 osDisplayTag.str(""); // reset
                 osDisplayTag << (origDisplayWidth * depthScale);
                 disp.setTagArg("b", 0, osDisplayTag.str().data());
                 osDisplayTag.str(""); // reset
                 osDisplayTag << (origDisplayHeight * depthScale);
                 disp.setTagArg("b", 1, osDisplayTag.str().data());
             }
             if (origIconSize > 0) {
                 // choose a appropriate icon size (only if a icon is specified)
                 disp.setTagArg("is", 0, iconSizeToTag(origIconSize * depthScale));
             }
         }
     }
 }
wrapIfOutside()
void BaseMobility::wrapIfOutside (BorderHandling wo, Coord & stepTarget, Coord & targetPos) protected
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
Wraps the host to the other playground size. Updates the target position.
Parameters
wo defines the border at which to reflect
stepTarget target position of the current step of the host
targetPos target position of the host (for non atomic movements)
References veins::FWMath::modulo(), NOWHERE, playgroundSizeX(), playgroundSizeY(), playgroundSizeZ(), veins::Coord::x, X_BIGGER, X_SMALLER, veins::Coord::y, Y_BIGGER, Y_SMALLER, veins::Coord::z, Z_BIGGER, and Z_SMALLER.
Referenced by handleIfOutside().
 {
     switch (wo) {
     case X_SMALLER:
     case X_BIGGER:
         targetPos.x = (FWMath::modulo(targetPos.x, playgroundSizeX()));
         stepTarget.x = (FWMath::modulo(stepTarget.x, playgroundSizeX()));
         break;
     case Y_SMALLER:
     case Y_BIGGER:
         targetPos.y = (FWMath::modulo(targetPos.y, playgroundSizeY()));
         stepTarget.y = (FWMath::modulo(stepTarget.y, playgroundSizeY()));
         break;
     case Z_SMALLER:
     case Z_BIGGER:
         targetPos.z = (FWMath::modulo(targetPos.z, playgroundSizeZ()));
         stepTarget.z = (FWMath::modulo(stepTarget.z, playgroundSizeZ()));
         break;
     case NOWHERE:
     default:
         throw cRuntimeError("wrong border handling case!");
         break;
     }
 }
Member Data Documentation
mobilityStateChangedSignal
const simsignal_t BaseMobility::mobilityStateChangedSignal = registerSignal("org_car2x_veins_base_modules_mobilityStateChanged") static
Store the category of HostMove.
Referenced by veins::DemoBaseApplLayer::initialize(), veins::ChannelAccess::initialize(), veins::DemoBaseApplLayer::receiveSignal(), veins::ChannelAccess::receiveSignal(), updatePosition(), and veins::DemoBaseApplLayer::~DemoBaseApplLayer().
move
Move veins::BaseMobility::move protected
Stores the current position and move pattern of the host.
Referenced by veins::TraCIMobility::changePosition(), checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), handleBorderMsg(), handleIfOutside(), handleSelfMsg(), veins::LinearMobility::initialize(), veins::TraCIMobility::initialize(), initialize(), veins::LinearMobility::makeMove(), veins::TraCIMobility::preInitialize(), and updatePosition().
moveMsg
cMessage* veins::BaseMobility::moveMsg protected
Self message to trigger movement.
Referenced by handleSelfMsg(), and initialize().
origDisplayHeight
double veins::BaseMobility::origDisplayHeight protected
The original height the node is displayed width.
Referenced by initialize(), and updatePosition().
origDisplayWidth
double veins::BaseMobility::origDisplayWidth protected
The original width the node is displayed width.
Referenced by initialize(), and updatePosition().
origIconSize
double veins::BaseMobility::origIconSize protected
The original size of the icon of the node.
Referenced by initialize(), and updatePosition().
playgroundScaleX
double veins::BaseMobility::playgroundScaleX protected
Scaling of the playground in X direction.
Referenced by initialize(), and updatePosition().
playgroundScaleY
double veins::BaseMobility::playgroundScaleY protected
Scaling of the playground in Y direction.
Referenced by initialize(), and updatePosition().
scaleNodeByDepth
bool veins::BaseMobility::scaleNodeByDepth protected
Enable depth dependent scaling of nodes when 3d and tkenv is used.
Referenced by initialize(), and updatePosition().
updateInterval
simtime_t veins::BaseMobility::updateInterval protected
Time interval (in seconds) to update the hosts position.
Referenced by veins::TraCIMobility::changePosition(), handleSelfMsg(), initialize(), and veins::LinearMobility::makeMove().
world
BaseWorldUtility* veins::BaseMobility::world protected
Pointer to BaseWorldUtility – these two must know each other.
Referenced by checkIfOutside(), veins::TraCIMobility::fixIfHostGetsOutside(), goToBorder(), initialize(), placeRandomlyIfOutside(), and updatePosition().
The documentation for this class was generated from the following files:
BaseMobility.h
BaseMobility.cc