Veins: veins::BatteryAccess Class Reference
veins::BatteryAccess Class Reference
Extends BaseModule by several methods which provide access to the battery module.
#include <BatteryAccess.h>
Public Member Functions
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Extends BaseModule by several methods which provide access to the battery module.
Author
Karl Wessel
Constructor & Destructor Documentation
BatteryAccess() [1/2]
BatteryAccess::BatteryAccess ()
     : BaseModule()
     , battery(nullptr)
 {
 }
BatteryAccess() [2/2]
BatteryAccess::BatteryAccess (unsigned stacksize)
     : BaseModule(stacksize)
     , battery(nullptr)
 {
 }
Member Function Documentation
draw()
void BatteryAccess::draw (DrawAmount & amount, int account) protected
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
If no battery module is available than nothing happens.
References battery, deviceID, and veins::BaseBattery::draw().
 {
     if (!battery) return;
     battery->draw(deviceID, amount, account);
 }
drawCurrent()
void BatteryAccess::drawCurrent (double amount, int account) protected
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
If no battery module is available than nothing happens.
References battery, veins::DrawAmount::CURRENT, deviceID, and veins::BaseBattery::draw().
 {
     if (!battery) return;
     DrawAmount val(DrawAmount::CURRENT, amount);
     battery->draw(deviceID, val, account);
 }
drawEnergy()
void BatteryAccess::drawEnergy (double amount, int account) protected
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
If no battery module is available than nothing happens.
References battery, deviceID, veins::BaseBattery::draw(), and veins::DrawAmount::ENERGY.
 {
     if (!battery) return;
     DrawAmount val(DrawAmount::ENERGY, amount);
     battery->draw(deviceID, val, account);
 }
registerWithBattery()
void BatteryAccess::registerWithBattery (const std::string & name, int numAccounts) protected
Registers this module as a device with the battery module.
If no battery module is available than nothing happens.
References battery, deviceID, veins::BaseModule::findHost(), veins::FindModule< T >::findSubModule(), and veins::BaseBattery::registerDevice().
 {
     battery = FindModule<BaseBattery*>::findSubModule(findHost());
     if (!battery) {
         throw cRuntimeError("No battery module defined!");
     }
     else {
         deviceID = battery->registerDevice(name, numAccounts);
     }
 }
Member Data Documentation
battery
BaseBattery* veins::BatteryAccess::battery protected
Stores pointer to the battery module.
Referenced by draw(), drawCurrent(), drawEnergy(), and registerWithBattery().
deviceID
int veins::BatteryAccess::deviceID protected
This devices id for the battery module.
Referenced by draw(), drawCurrent(), drawEnergy(), and registerWithBattery().
The documentation for this class was generated from the following files:
BatteryAccess.h
BatteryAccess.cc