Veins: veins::TraCIScenarioManagerForker Class Reference
veins::TraCIScenarioManagerForker Class Reference
Extends the TraCIScenarioManager to automatically fork an instance of SUMO when needed.
#include <TraCIScenarioManagerForker.h>
Public Member Functions
TraCIScenarioManagerForker ()
~TraCIScenarioManagerForker () override
void initialize (int stage) override
void finish () override
Public Member Functions inherited from veins::TraCIScenarioManager
TraCIScenarioManager ()
~TraCIScenarioManager () override
int numInitStages () const override
void initialize (int stage) override
void finish () override
void handleMessage (cMessage *msg) override
virtual void handleSelfMsg (cMessage *msg)
bool isConnected () const
TraCICommandInterface * getCommandInterface () const
TraCIConnection * getConnection () const
bool getAutoShutdownTriggered ()
const std::map< std::string, cModule * > & getManagedHosts ()
bool isUsable () const
Predicate indicating a successful connection to the TraCI server.
Protected Member Functions
virtual void startServer ()
virtual void killServer ()
int getPortNumber () const override
Protected Member Functions inherited from veins::TraCIScenarioManager
void executeOneTimestep ()
read and execute all commands for the next timestep
virtual void init_traci ()
virtual void preInitializeModule (cModule *mod, const std::string &nodeId, const Coord &position, const std::string &road_id, double speed, Heading heading, VehicleSignalSet signals)
virtual void updateModulePosition (cModule *mod, const Coord &p, const std::string &edge, double speed, Heading heading, VehicleSignalSet signals)
void addModule (std::string nodeId, std::string type, std::string name, std::string displayString, const Coord &position, std::string road_id="", double speed=-1, Heading heading=Heading::nan, VehicleSignalSet signals={VehicleSignal::undefined}, double length=0, double height=0, double width=0)
cModule * getManagedModule (std::string nodeId)
returns a pointer to the managed module named moduleName, or 0 if no module can be found
void deleteManagedModule (std::string nodeId)
bool isModuleUnequipped (std::string nodeId)
returns true if this vehicle is Unequipped
void subscribeToVehicleVariables (std::string vehicleId)
void unsubscribeFromVehicleVariables (std::string vehicleId)
void processSimSubscription (std::string objectId, TraCIBuffer &buf)
void processVehicleSubscription (std::string objectId, TraCIBuffer &buf)
void processSubcriptionResult (TraCIBuffer &buf)
void subscribeToTrafficLightVariables (std::string tlId)
void unsubscribeFromTrafficLightVariables (std::string tlId)
void processTrafficLightSubscription (std::string objectId, TraCIBuffer &buf)
void parseModuleTypes ()
parses the vector of module types in ini file
TypeMapping parseMappings (std::string parameter, std::string parameterName, bool allowEmpty=false)
transforms a list of mappings of an omnetpp.ini parameter in a list
Protected Attributes
std::string commandLine
command line for running TraCI server (substituting $configFile, $seed, $port)
std::string command
substitution for $command parameter
std::string configFile
substitution for $configFile parameter
int seed
substitution for $seed parameter (-1: current run number)
TraCILauncher * server
Protected Attributes inherited from veins::TraCIScenarioManager
bool traciInitialized = false
Flag indicating whether the init_traci routine has been run.
simtime_t connectAt
when to connect to TraCI server (must be the initial timestep of the server)
simtime_t firstStepAt
when to start synchronizing with the TraCI server (-1: immediately after connecting)
simtime_t updateInterval
time interval of hosts' position updates
TypeMapping moduleType
module type to be used in the simulation for each managed vehicle
TypeMapping moduleName
module name to be used in the simulation for each managed vehicle
TypeMapping moduleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::string host
int port
std::string trafficLightModuleType
module type to be used in the simulation for each managed traffic light
std::string trafficLightModuleName
module name to be used in the simulation for each managed traffic light
std::string trafficLightModuleDisplayString
module displayString to be used in the simulation for each managed vehicle
std::vector< std::string > trafficLightModuleIds
list of traffic light module ids that is subscribed to (whitelist)
bool autoShutdown
Shutdown module as soon as no more vehicles are in the simulation.
double penetrationRate
bool ignoreGuiCommands
whether to ignore all TraCI commands that only make sense when the server has a graphical user interface
TraCIRegionOfInterest roi
Can return whether a given position lies within the simulation's region of interest.
double areaSum
AnnotationManager * annotations
std::unique_ptr< TraCIConnection > connection
std::unique_ptr< TraCICommandInterface > commandIfc
size_t nextNodeVectorIndex
next OMNeT++ module vector index to use
std::map< std::string, cModule * > hosts
vector of all hosts managed by us
std::set< std::string > unEquippedHosts
std::set< std::string > subscribedVehicles
all vehicles we have already subscribed to
std::map< std::string, cModule * > trafficLights
vector of all traffic lights managed by us
uint32_t activeVehicleCount
number of vehicles, be it parking or driving
uint32_t parkingVehicleCount
number of parking vehicles, derived from parking start/end events
uint32_t drivingVehicleCount
number of driving, as reported by sumo
bool autoShutdownTriggered
cMessage * connectAndStartTrigger
self-message scheduled for when to connect to TraCI server and start running
cMessage * executeOneTimestepTrigger
self-message scheduled for when to next call executeOneTimestep
BaseWorldUtility * world
std::map< const BaseMobility *, const MobileHostObstacle * > vehicleObstacles
VehicleObstacleControl * vehicleObstacleControl
Additional Inherited Members
Static Public Attributes inherited from veins::TraCIScenarioManager
static const simsignal_t traciInitializedSignal = registerSignal("org_car2x_veins_modules_mobility_traciInitialized")
static const simsignal_t traciModuleAddedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleAdded")
static const simsignal_t traciModuleRemovedSignal = registerSignal("org_car2x_veins_modules_mobility_traciModuleRemoved")
static const simsignal_t traciTimestepBeginSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepBegin")
static const simsignal_t traciTimestepEndSignal = registerSignal("org_car2x_veins_modules_mobility_traciTimestepEnd")
Protected Types inherited from veins::TraCIScenarioManager
typedef std::map< std::string, std::string > TypeMapping
Detailed Description
Extends the TraCIScenarioManager to automatically fork an instance of SUMO when needed.
All other functionality is provided by the TraCIScenarioManager.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, Florian Hagenauer
See also
TraCIMobility
TraCIScenarioManager
Constructor & Destructor Documentation
TraCIScenarioManagerForker()
TraCIScenarioManagerForker::TraCIScenarioManagerForker ()
References server.
 {
     server = nullptr;
 }
~TraCIScenarioManagerForker()
TraCIScenarioManagerForker::~TraCIScenarioManagerForker () override
References killServer().
 {
     killServer();
 }
Member Function Documentation
finish()
void TraCIScenarioManagerForker::finish () override
References veins::TraCIScenarioManager::finish(), and killServer().
 {
     TraCIScenarioManager::finish();
     killServer();
 }
getPortNumber()
int TraCIScenarioManagerForker::getPortNumber () const override protected virtual
Reimplemented from veins::TraCIScenarioManager.
References veins::TraCIScenarioManager::getPortNumber(), veins::TraCIScenarioManager::port, and veins::socket().
 {
     int port = TraCIScenarioManager::getPortNumber();
     if (port != -1) {
         return port;
     }
     // find a free port for the forker if port is still -1
     if (initsocketlibonce() != 0) throw cRuntimeError("Could not init socketlib");
     SOCKET sock = ::socket(AF_INET, SOCK_STREAM, 0);
     if (sock < 0) {
         throw cRuntimeError("Failed to create socket: %s", strerror(errno));
     }
     struct sockaddr_in serv_addr;
     struct sockaddr* serv_addr_p = (struct sockaddr*) &serv_addr;
     memset(serv_addr_p, 0, sizeof(serv_addr));
     serv_addr.sin_family = AF_INET;
     serv_addr.sin_addr.s_addr = htonl(INADDR_ANY);
     serv_addr.sin_port = 0;
     if (::bind(sock, serv_addr_p, sizeof(serv_addr)) < 0) {
         throw cRuntimeError("Failed to bind socket: %s", strerror(errno));
     }
     socklen_t len = sizeof(serv_addr);
     if (getsockname(sock, serv_addr_p, &len) < 0) {
         throw cRuntimeError("Failed to get hostname: %s", strerror(errno));
     }
     port = ntohs(serv_addr.sin_port);
     closesocket(sock);
     return port;
 }
initialize()
void TraCIScenarioManagerForker::initialize (int stage) override
References command, commandLine, configFile, veins::TraCIScenarioManager::initialize(), killServer(), seed, and startServer().
 {
     if (stage == 1) {
         commandLine = par("commandLine").stringValue();
         command = par("command").stringValue();
         configFile = par("configFile").stringValue();
         seed = par("seed");
         killServer();
     }
     TraCIScenarioManager::initialize(stage);
     if (stage == 1) {
         startServer();
     }
 }
killServer()
void TraCIScenarioManagerForker::killServer () protected virtual
References server.
Referenced by finish(), initialize(), and ~TraCIScenarioManagerForker().
 {
     if (server) {
         delete server;
         server = nullptr;
     }
 }
startServer()
void TraCIScenarioManagerForker::startServer () protected virtual
References command, commandLine, configFile, veins::TraCIScenarioManager::port, anonymous_namespace{TraCIScenarioManagerForker.cc}::replace(), seed, and server.
Referenced by initialize().
 {
     // autoset seed, if requested
     if (seed == -1) {
         const char* seed_s = cSimulation::getActiveSimulation()->getEnvir()->getConfigEx()->getVariable(CFGVAR_RUNNUMBER);
         seed = atoi(seed_s);
     }
     // assemble commandLine
     commandLine = replace(commandLine, "$command", command);
     commandLine = replace(commandLine, "$configFile", configFile);
     commandLine = replace(commandLine, "$seed", seed);
     commandLine = replace(commandLine, "$port", port);
     server = new TraCILauncher(commandLine);
 }
Member Data Documentation
command
std::string veins::TraCIScenarioManagerForker::command protected
substitution for $command parameter
Referenced by initialize(), and startServer().
commandLine
std::string veins::TraCIScenarioManagerForker::commandLine protected
command line for running TraCI server (substituting $configFile, $seed, $port)
Referenced by initialize(), and startServer().
configFile
std::string veins::TraCIScenarioManagerForker::configFile protected
substitution for $configFile parameter
Referenced by initialize(), and startServer().
seed
int veins::TraCIScenarioManagerForker::seed protected
substitution for $seed parameter (-1: current run number)
Referenced by initialize(), and startServer().
server
TraCILauncher* veins::TraCIScenarioManagerForker::server protected
Referenced by killServer(), startServer(), and TraCIScenarioManagerForker().
The documentation for this class was generated from the following files:
TraCIScenarioManagerForker.h
TraCIScenarioManagerForker.cc