Veins: veins::TraCIVehicleInserter Class Reference
veins::TraCIVehicleInserter Class Reference
Uses the TraCIScenarioManager to programmatically insert new vehicles at the TraCI server.
#include <TraCIVehicleInserter.h>
Public Member Functions
TraCIVehicleInserter ()
~TraCIVehicleInserter () override
int numInitStages () const override
void initialize (int stage) override
void finish () override
void finish (cComponent *component, simsignal_t signalID) override
void handleMessage (cMessage *msg) override
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
void receiveSignal (cComponent *source, simsignal_t signalID, const SimTime &t, cObject *details) override
Protected Member Functions
void insertNewVehicle ()
adds a new vehicle to the queue which are tried to be inserted at the next SUMO time step;
void insertVehicles ()
tries to add all vehicles in the vehicle queue to SUMO;
Protected Attributes
int vehicleRngIndex
int numVehicles
TraCIScenarioManager * manager
cRNG * mobRng
std::map< int, std::queue< std::string > > vehicleInsertQueue
std::set< std::string > queuedVehicles
std::vector< std::string > routeIds
uint32_t vehicleNameCounter
std::vector< std::string > vehicleTypeIds
Detailed Description
Uses the TraCIScenarioManager to programmatically insert new vehicles at the TraCI server.
This is done whenever the total number of active vehicles drops below a given number.
See the Veins website for a tutorial, documentation, and publications .
Author
Christoph Sommer, David Eckhoff, Falko Dressler, Zheng Yao, Tobias Mayer, Alvaro Torres Cortes, Luca Bedogni
See also
TraCIScenarioManager
Constructor & Destructor Documentation
TraCIVehicleInserter()
TraCIVehicleInserter::TraCIVehicleInserter ()
     : mobRng(nullptr)
 {
 }
~TraCIVehicleInserter()
TraCIVehicleInserter::~TraCIVehicleInserter () override
 {
 }
Member Function Documentation
finish() [1/2]
void TraCIVehicleInserter::finish () override
References veins::TraCIScenarioManager::traciModuleAddedSignal, and veins::TraCIScenarioManager::traciTimestepBeginSignal.
 {
     unsubscribe(TraCIScenarioManager::traciModuleAddedSignal, this);
     unsubscribe(TraCIScenarioManager::traciTimestepBeginSignal, this);
 }
finish() [2/2]
void TraCIVehicleInserter::finish (cComponent * component, simsignal_t signalID) override
 {
     cListener::finish(component, signalID);
 }
handleMessage()
void TraCIVehicleInserter::handleMessage (cMessage * msg) override
 {
 }
initialize()
void TraCIVehicleInserter::initialize (int stage) override
References veins::TraCIScenarioManagerAccess::get(), manager, mobRng, numVehicles, veins::TraCIScenarioManager::traciModuleAddedSignal, veins::TraCIScenarioManager::traciTimestepBeginSignal, vehicleNameCounter, and vehicleRngIndex.
 {
     cSimpleModule::initialize(stage);
     if (stage != 1) {
         return;
     }
     // internal 1
     manager = TraCIScenarioManagerAccess().get();
     // signals
     manager->subscribe(TraCIScenarioManager::traciModuleAddedSignal, this);
     manager->subscribe(TraCIScenarioManager::traciTimestepBeginSignal, this);
     // parameters
     vehicleRngIndex = par("vehicleRngIndex");
     numVehicles = par("numVehicles");
     // internal 2
     vehicleNameCounter = 0;
     mobRng = getRNG(vehicleRngIndex);
 }
insertNewVehicle()
void TraCIVehicleInserter::insertNewVehicle () protected
adds a new vehicle to the queue which are tried to be inserted at the next SUMO time step;
References mobRng, routeIds, vehicleInsertQueue, and vehicleTypeIds.
Referenced by receiveSignal().
 {
     std::string type;
     if (vehicleTypeIds.size()) {
         int vehTypeId = mobRng->intRand(vehicleTypeIds.size());
         type = vehicleTypeIds[vehTypeId];
     }
     else {
         type = "DEFAULT_VEHTYPE";
     }
     int routeId = mobRng->intRand(routeIds.size());
     vehicleInsertQueue[routeId].push(type);
 }
insertVehicles()
void TraCIVehicleInserter::insertVehicles () protected
tries to add all vehicles in the vehicle queue to SUMO;
References veins::TraCICommandInterface::addVehicle(), veins::TraCIScenarioManager::getCommandInterface(), manager, queuedVehicles, routeIds, vehicleInsertQueue, and vehicleNameCounter.
Referenced by receiveSignal().
 {
     for (std::map<int, std::queue<std::string>>::iterator i = vehicleInsertQueue.begin(); i != vehicleInsertQueue.end();) {
         std::string route = routeIds[i->first];
         EV_DEBUG << "process " << route << std::endl;
         std::queue<std::string> vehicles = i->second;
         while (!i->second.empty()) {
             bool suc = false;
             std::string type = i->second.front();
             std::stringstream veh;
             veh << type << "_" << vehicleNameCounter;
             EV_DEBUG << "trying to add " << veh.str() << " with " << route << " vehicle type " << type << std::endl;
             suc = manager->getCommandInterface()->addVehicle(veh.str(), type, route, simTime());
             if (!suc) {
                 i->second.pop();
             }
             else {
                 EV_DEBUG << "successful inserted " << veh.str() << std::endl;
                 queuedVehicles.insert(veh.str());
                 i->second.pop();
                 vehicleNameCounter++;
             }
         }
         std::map<int, std::queue<std::string>>::iterator tmp = i;
         ++tmp;
         vehicleInsertQueue.erase(i);
         i = tmp;
     }
 }
numInitStages()
int TraCIVehicleInserter::numInitStages () const override
 {
     return std::max(cSimpleModule::numInitStages(), 2);
 }
receiveSignal() [1/2]
void TraCIVehicleInserter::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override
References veins::FindModule< T >::findSubModule(), veins::TraCIScenarioManager::isConnected(), manager, queuedVehicles, and veins::TraCIScenarioManager::traciModuleAddedSignal.
 {
     if (signalID == TraCIScenarioManager::traciModuleAddedSignal) {
         ASSERT(manager->isConnected());
         cModule* mod = check_and_cast<cModule*>(obj);
         auto* mob = FindModule<TraCIMobility*>::findSubModule(mod);
         ASSERT(mob != nullptr);
         std::string nodeId = mob->getExternalId();
         if (queuedVehicles.find(nodeId) != queuedVehicles.end()) {
             queuedVehicles.erase(nodeId);
         }
     }
 }
receiveSignal() [2/2]
void TraCIVehicleInserter::receiveSignal (cComponent * source, simsignal_t signalID, const SimTime & t, cObject * details) override
References veins::TraCIScenarioManager::getCommandInterface(), veins::TraCIScenarioManager::getManagedHosts(), veins::TraCICommandInterface::getRouteIds(), veins::TraCICommandInterface::getVehicleTypeIds(), insertNewVehicle(), insertVehicles(), veins::TraCIScenarioManager::isConnected(), manager, numVehicles, queuedVehicles, routeIds, veins::TraCIScenarioManager::traciTimestepBeginSignal, and vehicleTypeIds.
 {
     if (signalID == TraCIScenarioManager::traciTimestepBeginSignal) {
         ASSERT(manager->isConnected());
         if (simTime() > 1) {
             if (vehicleTypeIds.size() == 0) {
                 std::list<std::string> vehTypes = manager->getCommandInterface()->getVehicleTypeIds();
                 for (std::list<std::string>::const_iterator i = vehTypes.begin(); i != vehTypes.end(); ++i) {
                     if (i->substr(0, 8).compare("DEFAULT_") != 0) {
                         EV_DEBUG << *i << std::endl;
                         vehicleTypeIds.push_back(*i);
                     }
                 }
             }
             if (routeIds.size() == 0) {
                 std::list<std::string> routes = manager->getCommandInterface()->getRouteIds();
                 for (std::list<std::string>::const_iterator i = routes.begin(); i != routes.end(); ++i) {
                     std::string routeId = *i;
                     if (par("useRouteDistributions").boolValue() == true) {
                         if (std::count(routeId.begin(), routeId.end(), '#') >= 1) {
                             EV_DEBUG << "Omitting route " << routeId << " as it seems to be a member of a route distribution (found '#' in name)" << std::endl;
                             continue;
                         }
                     }
                     EV_DEBUG << "Adding " << routeId << " to list of possible routes" << std::endl;
                     routeIds.push_back(routeId);
                 }
             }
             for (int i = manager->getManagedHosts().size() + queuedVehicles.size(); i < numVehicles; i++) {
                 insertNewVehicle();
             }
         }
         insertVehicles();
     }
 }
Member Data Documentation
manager
TraCIScenarioManager* veins::TraCIVehicleInserter::manager protected
Referenced by initialize(), insertVehicles(), and receiveSignal().
mobRng
cRNG* veins::TraCIVehicleInserter::mobRng protected
Referenced by initialize(), and insertNewVehicle().
numVehicles
int veins::TraCIVehicleInserter::numVehicles protected
Referenced by initialize(), and receiveSignal().
queuedVehicles
std::set<std::string> veins::TraCIVehicleInserter::queuedVehicles protected
Referenced by insertVehicles(), and receiveSignal().
routeIds
std::vector<std::string> veins::TraCIVehicleInserter::routeIds protected
Referenced by insertNewVehicle(), insertVehicles(), and receiveSignal().
vehicleInsertQueue
std::map<int, std::queue<std::string> > veins::TraCIVehicleInserter::vehicleInsertQueue protected
Referenced by insertNewVehicle(), and insertVehicles().
vehicleNameCounter
uint32_t veins::TraCIVehicleInserter::vehicleNameCounter protected
Referenced by initialize(), and insertVehicles().
vehicleRngIndex
int veins::TraCIVehicleInserter::vehicleRngIndex protected
Referenced by initialize().
vehicleTypeIds
std::vector<std::string> veins::TraCIVehicleInserter::vehicleTypeIds protected
Referenced by insertNewVehicle(), and receiveSignal().
The documentation for this class was generated from the following files:
TraCIVehicleInserter.h
TraCIVehicleInserter.cc