Veins: veins::Heading Class Reference
veins::Heading Class Reference
Stores a Heading in rad, with 0 degrees being east and 90 degrees being north.
#include <Heading.h>
Public Member Functions
Heading ()
Creates an undefined Heading.
Heading (double rad)
Creates a new Heading from an angle (in rad, with 0 degrees being east and 90 degrees being north).
double getRad () const
Returns the angle (in rad, with 0 degrees being east and 90 degrees being north).
bool isNan () const
Test for nan.
Coord toCoord (double length=1) const
Returns Coord of a unit vector (with x pointing east and y pointing south).
Static Public Member Functions
static Heading fromCoord (Coord o)
Converts Coord to heading (with x pointing east and y pointing south).
Static Public Attributes
static const Heading nan = Heading(std::numeric_limits<double>::quiet_NaN())
Protected Attributes
double rad
Detailed Description
Stores a Heading in rad, with 0 degrees being east and 90 degrees being north.
Constructor & Destructor Documentation
Heading() [1/2]
veins::Heading::Heading () inline
Creates an undefined Heading.
         : rad(std::numeric_limits<double>::quiet_NaN())
     {
     }
Heading() [2/2]
veins::Heading::Heading (double rad) inline explicit
Creates a new Heading from an angle (in rad, with 0 degrees being east and 90 degrees being north).
         : rad(rad)
     {
     }
Member Function Documentation
fromCoord()
static Heading veins::Heading::fromCoord (Coord o) inline static
Converts Coord to heading (with x pointing east and y pointing south).
References veins::Coord::x, and veins::Coord::y.
Referenced by veins::MobileHostObstacle::getShape(), and veins::ChannelAccess::receiveSignal().
     {
         return Heading(atan2(-o.y, o.x));
     }
getRad()
double veins::Heading::getRad () const inline
Returns the angle (in rad, with 0 degrees being east and 90 degrees being north).
Referenced by veins::TraCICoordinateTransformation::omnet2traciHeading(), and veins::operator<<().
     {
         return rad;
     }
isNan()
bool veins::Heading::isNan () const inline
Test for nan.
     {
         return std::isnan(rad);
     }
toCoord()
Coord veins::Heading::toCoord (double length = 1) const inline
Returns Coord of a unit vector (with x pointing east and y pointing south).
Parameters
length length of vector (dimensionless)
Referenced by veins::TraCIMobility::calculateHostPosition(), veins::TraCIMobility::changePosition(), veins::BasePhyLayer::filterSignal(), veins::BasePhyLayer::handleUpperMessage(), veins::TraCIMobility::initialize(), veins::TraCIMobility::nextPosition(), and veins::TraCIMobility::preInitialize().
     {
         return Coord(cos(rad) * length, -sin(rad) * length);
     }
Member Data Documentation
nan
const Heading veins::Heading::nan = Heading(std::numeric_limits<double>::quiet_NaN()) static
Referenced by veins::TraCIMobility::~TraCIMobility().
rad
double veins::Heading::rad protected
The documentation for this class was generated from the following files:
Heading.h
Heading.cc