Veins: veins::TraCIDemo11p Class Reference
veins::TraCIDemo11p Class Reference
A tutorial demo for TraCI.
#include <TraCIDemo11p.h>
Public Member Functions
void initialize (int stage) override
Public Member Functions inherited from veins::DemoBaseApplLayer
~DemoBaseApplLayer () override
void initialize (int stage) override
void finish () override
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Public Member Functions inherited from veins::BaseApplLayer
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
void initialize (int) override
Initialization of the module and some variables.
Public Member Functions inherited from veins::BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
void onWSM (BaseFrame1609_4 *wsm) override
this function is called upon receiving a BaseFrame1609_4
void onWSA (DemoServiceAdvertisment *wsa) override
this function is called upon receiving a DemoServiceAdvertisement
void handleSelfMsg (cMessage *msg) override
handle self messages
void handlePositionUpdate (cObject *obj) override
this function is called every time the vehicle receives a position update signal
Protected Member Functions inherited from veins::DemoBaseApplLayer
void handleLowerMsg (cMessage *msg) override
handle messages from below and calls the onWSM, onBSM, and onWSA functions accordingly
virtual void populateWSM (BaseFrame1609_4 *wsm, LAddress::L2Type rcvId=LAddress::L2BROADCAST(), int serial=0)
sets all the necessary fields in the WSM, BSM, or WSA.
virtual void onBSM (DemoSafetyMessage *bsm)
this function is called upon receiving a DemoSafetyMessage, also referred to as a beacon
virtual void handleParkingUpdate (cObject *obj)
this function is called every time the vehicle parks or starts moving again
virtual void startService (Channel channel, int serviceId, std::string serviceDescription)
This will start the periodic advertising of the new service on the CCH.
virtual void stopService ()
stopping the service and advertising for it
virtual simtime_t computeAsynchronousSendingTime (simtime_t interval, ChannelType chantype)
compute a point in time that is guaranteed to be in the correct channel interval plus a random offset
virtual void sendDown (cMessage *msg)
overloaded for error handling and stats recording purposes
virtual void sendDelayedDown (cMessage *msg, simtime_t delay)
overloaded for error handling and stats recording purposes
virtual void checkAndTrackPacket (cMessage *msg)
helper function for error handling and stats recording purposes
Protected Member Functions inherited from veins::BaseApplLayer
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
void handleLowerControl (cMessage *msg) override
Handle control messages from lower layer.
void handleUpperMsg (cMessage *msg) override
Handle messages from upper layer.
void handleUpperControl (cMessage *msg) override
Handle control messages from upper layer.
Protected Member Functions inherited from veins::BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
simtime_t lastDroveAt
bool sentMessage
int currentSubscribedServiceId
Protected Attributes inherited from veins::DemoBaseApplLayer
TraCIMobility * mobility
TraCICommandInterface * traci
TraCICommandInterface::Vehicle * traciVehicle
AnnotationManager * annotations
DemoBaseApplLayerToMac1609_4Interface * mac
bool isParked
uint32_t beaconLengthBits
uint32_t beaconUserPriority
simtime_t beaconInterval
bool sendBeacons
uint32_t dataLengthBits
uint32_t dataUserPriority
bool dataOnSch
int currentOfferedServiceId
std::string currentServiceDescription
Channel currentServiceChannel
simtime_t wsaInterval
Coord curPosition
Coord curSpeed
LAddress::L2Type myId = 0
int mySCH
uint32_t generatedWSMs
uint32_t generatedWSAs
uint32_t generatedBSMs
uint32_t receivedWSMs
uint32_t receivedWSAs
uint32_t receivedBSMs
cMessage * sendBeaconEvt
cMessage * sendWSAEvt
Protected Attributes inherited from veins::BaseApplLayer
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from veins::BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from veins::DemoBaseApplLayer
enum DemoApplMessageKinds { SEND_BEACON_EVT, SEND_WSA_EVT }
Public Types inherited from veins::BaseApplLayer
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Static Public Attributes inherited from veins::BaseLayer
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
A tutorial demo for TraCI.
When the car is stopped for longer than 10 seconds it will send a message out to other cars containing the blocked road id. Receiving cars will then trigger a reroute via TraCI. When channel switching between SCH and CCH is enabled on the MAC, the message is instead send out on a service channel following a Service Advertisement on the CCH.
Author
Christoph Sommer : initial DemoApp
David Eckhoff : rewriting, moving functionality to DemoBaseApplLayer, adding WSA
Member Function Documentation
handlePositionUpdate()
void TraCIDemo11p::handlePositionUpdate (cObject * obj) override protected virtual
this function is called every time the vehicle receives a position update signal
Reimplemented from veins::DemoBaseApplLayer.
References veins::DemoBaseApplLayer::computeAsynchronousSendingTime(), veins::DemoBaseApplLayer::dataOnSch, veins::BaseModule::findHost(), veins::TraCIMobility::getRoadId(), veins::TraCIMobility::getSpeed(), veins::DemoBaseApplLayer::handlePositionUpdate(), lastDroveAt, veins::DemoBaseApplLayer::mobility, veins::DemoBaseApplLayer::populateWSM(), veins::sch2, veins::DemoBaseApplLayer::sendDown(), sentMessage, veins::service, and veins::DemoBaseApplLayer::startService().
 {
     DemoBaseApplLayer::handlePositionUpdate(obj);
     // stopped for for at least 10s?
     if (mobility->getSpeed() < 1) {
         if (simTime() - lastDroveAt >= 10 && sentMessage == false) {
             findHost()->getDisplayString().setTagArg("i", 1, "red");
             sentMessage = true;
             TraCIDemo11pMessage* wsm = new TraCIDemo11pMessage();
             populateWSM(wsm);
             wsm->setDemoData(mobility->getRoadId().c_str());
             // host is standing still due to crash
             if (dataOnSch) {
                 startService(Channel::sch2, 42, "Traffic Information Service");
                 // started service and server advertising, schedule message to self to send later
                 scheduleAt(computeAsynchronousSendingTime(1, ChannelType::service), wsm);
             }
             else {
                 // send right away on CCH, because channel switching is disabled
                 sendDown(wsm);
             }
         }
     }
     else {
         lastDroveAt = simTime();
     }
 }
handleSelfMsg()
void TraCIDemo11p::handleSelfMsg (cMessage * msg) override protected virtual
handle self messages
Reimplemented from veins::DemoBaseApplLayer.
References veins::DemoBaseApplLayer::handleSelfMsg(), veins::DemoBaseApplLayer::sendDown(), and veins::DemoBaseApplLayer::stopService().
 {
     if (TraCIDemo11pMessage* wsm = dynamic_cast<TraCIDemo11pMessage*>(msg)) {
         // send this message on the service channel until the counter is 3 or higher.
         // this code only runs when channel switching is enabled
         sendDown(wsm->dup());
         wsm->setSerial(wsm->getSerial() + 1);
         if (wsm->getSerial() >= 3) {
             // stop service advertisements
             stopService();
             delete (wsm);
         }
         else {
             scheduleAt(simTime() + 1, wsm);
         }
     }
     else {
         DemoBaseApplLayer::handleSelfMsg(msg);
     }
 }
initialize()
void TraCIDemo11p::initialize (int stage) override
References currentSubscribedServiceId, veins::DemoBaseApplLayer::initialize(), lastDroveAt, and sentMessage.
 {
     DemoBaseApplLayer::initialize(stage);
     if (stage == 0) {
         sentMessage = false;
         lastDroveAt = simTime();
         currentSubscribedServiceId = -1;
     }
 }
onWSA()
void TraCIDemo11p::onWSA (DemoServiceAdvertisment * wsa) override protected virtual
this function is called upon receiving a DemoServiceAdvertisement
Reimplemented from veins::DemoBaseApplLayer.
References veins::DemoBaseApplLayerToMac1609_4Interface::changeServiceChannel(), veins::DemoBaseApplLayer::currentOfferedServiceId, currentSubscribedServiceId, veins::DemoBaseApplLayer::mac, veins::DemoBaseApplLayer::startService(), and veins::DemoBaseApplLayer::stopService().
 {
     if (currentSubscribedServiceId == -1) {
         mac->changeServiceChannel(static_cast<Channel>(wsa->getTargetChannel()));
         currentSubscribedServiceId = wsa->getPsid();
         if (currentOfferedServiceId != wsa->getPsid()) {
             stopService();
             startService(static_cast<Channel>(wsa->getTargetChannel()), wsa->getPsid(), "Mirrored Traffic Service");
         }
     }
 }
onWSM()
void TraCIDemo11p::onWSM (BaseFrame1609_4 * wsm) override protected virtual
this function is called upon receiving a BaseFrame1609_4
Reimplemented from veins::DemoBaseApplLayer.
References veins::TraCICommandInterface::Vehicle::changeRoute(), veins::BaseModule::findHost(), veins::TraCIMobility::getRoadId(), veins::DemoBaseApplLayer::mobility, veins::DemoBaseApplLayer::myId, sentMessage, and veins::DemoBaseApplLayer::traciVehicle.
 {
     TraCIDemo11pMessage* wsm = check_and_cast<TraCIDemo11pMessage*>(frame);
     findHost()->getDisplayString().setTagArg("i", 1, "green");
     if (mobility->getRoadId()[0] != ':') traciVehicle->changeRoute(wsm->getDemoData(), 9999);
     if (!sentMessage) {
         sentMessage = true;
         // repeat the received traffic update once in 2 seconds plus some random delay
         wsm->setSenderAddress(myId);
         wsm->setSerial(3);
         scheduleAt(simTime() + 2 + uniform(0.01, 0.2), wsm->dup());
     }
 }
Member Data Documentation
currentSubscribedServiceId
int veins::TraCIDemo11p::currentSubscribedServiceId protected
Referenced by initialize(), and onWSA().
lastDroveAt
simtime_t veins::TraCIDemo11p::lastDroveAt protected
Referenced by handlePositionUpdate(), and initialize().
sentMessage
bool veins::TraCIDemo11p::sentMessage protected
Referenced by handlePositionUpdate(), initialize(), and onWSM().
The documentation for this class was generated from the following files:
TraCIDemo11p.h
TraCIDemo11p.cc