Veins: veins::Mac80211pToPhy11pInterface Class Reference
veins::Mac80211pToPhy11pInterface Class Reference abstract
Interface of PhyLayer80211p exposed to Mac1609_4.
#include <Mac80211pToPhy11pInterface.h>
Public Types
enum BasePhyMessageKinds { CHANNEL_IDLE, CHANNEL_BUSY }
Public Member Functions
virtual ~Mac80211pToPhy11pInterface ()=default
virtual void changeListeningChannel (Channel channel)=0
virtual void setCCAThreshold (double ccaThreshold_dBm)=0
virtual void notifyMacAboutRxStart (bool enable)=0
virtual void requestChannelStatusIfIdle ()=0
virtual simtime_t getFrameDuration (int payloadLengthBits, MCS mcs) const =0
Detailed Description
Interface of PhyLayer80211p exposed to Mac1609_4.
Author
Christopher Saloman
David Eckhoff
Member Enumeration Documentation
BasePhyMessageKinds
enum veins::Mac80211pToPhy11pInterface::BasePhyMessageKinds
Enumerator
CHANNEL_IDLE
CHANNEL_BUSY
{
         CHANNEL_IDLE,
         CHANNEL_BUSY,
     };
Constructor & Destructor Documentation
~Mac80211pToPhy11pInterface()
virtual veins::Mac80211pToPhy11pInterface::~Mac80211pToPhy11pInterface () virtual default
Member Function Documentation
changeListeningChannel()
virtual void veins::Mac80211pToPhy11pInterface::changeListeningChannel (Channel channel) pure virtual
Implemented in veins::PhyLayer80211p.
Referenced by veins::Mac1609_4::changeServiceChannel(), and veins::Mac1609_4::handleSelfMsg().
getFrameDuration()
virtual simtime_t veins::Mac80211pToPhy11pInterface::getFrameDuration (int payloadLengthBits, MCS mcs) const pure virtual
Implemented in veins::PhyLayer80211p.
Referenced by veins::Mac1609_4::handleSelfMsg(), and veins::Mac1609_4::sendAck().
notifyMacAboutRxStart()
virtual void veins::Mac80211pToPhy11pInterface::notifyMacAboutRxStart (bool enable) pure virtual
Implemented in veins::PhyLayer80211p.
Referenced by veins::Mac1609_4::handleAck(), veins::Mac1609_4::handleAckTimeOut(), veins::Mac1609_4::handleLowerControl(), and veins::Mac1609_4::handleLowerMsg().
requestChannelStatusIfIdle()
virtual void veins::Mac80211pToPhy11pInterface::requestChannelStatusIfIdle () pure virtual
Implemented in veins::PhyLayer80211p.
Referenced by veins::Mac1609_4::handleAckTimeOut().
setCCAThreshold()
virtual void veins::Mac80211pToPhy11pInterface::setCCAThreshold (double ccaThreshold_dBm) pure virtual
Implemented in veins::PhyLayer80211p.
Referenced by veins::Mac1609_4::setCCAThreshold().
The documentation for this class was generated from the following file:
Mac80211pToPhy11pInterface.h