Veins: veins::AntennaPosition Class Reference
veins::AntennaPosition Class Reference
Stores the position of the host's antenna along with its speed, so that it can be linearly extrapolated.
#include <AntennaPosition.h>
Public Member Functions
AntennaPosition ()
AntennaPosition (int id, Coord p, Coord v, simtime_t t)
Store a position p that changes by v for every second after t.
Coord getPositionAt (simtime_t t=simTime()) const
Get the (linearly extrapolated) position at time t.
bool isSameAntenna (const AntennaPosition &o) const
Protected Attributes
int id
unique identifier of antenna returned by ChannelAccess::getId()
Coord p
position for linear extrapolation
Coord v
speed for linear extrapolation
simtime_t t
time for linear extrapolation
bool undef
true if created using default constructor
Detailed Description
Stores the position of the host's antenna along with its speed, so that it can be linearly extrapolated.
Constructor & Destructor Documentation
AntennaPosition() [1/2]
veins::AntennaPosition::AntennaPosition () inline
         : id(-1)
         , p()
         , v()
         , t()
         , undef(true)
     {
     }
AntennaPosition() [2/2]
veins::AntennaPosition::AntennaPosition (int id, Coord p, Coord v, simtime_t t) inline
Store a position p that changes by v for every second after t.
         : id(id)
         , p(p)
         , v(v)
         , t(t)
         , undef(false)
     {
     }
Member Function Documentation
getPositionAt()
Coord veins::AntennaPosition::getPositionAt (simtime_t t = simTime()) const inline
Get the (linearly extrapolated) position at time t.
Referenced by veins::ChannelAccess::calculatePropagationDelay(), veins::PERModel::filterSignal(), veins::TwoRayInterferenceModel::filterSignal(), veins::NakagamiFading::filterSignal(), veins::VehicleObstacleShadowing::filterSignal(), veins::SimpleObstacleShadowing::filterSignal(), veins::SimplePathlossModel::filterSignal(), veins::BreakpointPathlossModel::filterSignal(), veins::BasePhyLayer::filterSignal(), and veins::VehicleObstacleControl::getPotentialObstacles().
     {
         ASSERT(t >= this->t);
         ASSERT(!undef);
         auto dt = t - this->t;
         return p + v * dt.dbl();
     }
isSameAntenna()
bool veins::AntennaPosition::isSameAntenna (const AntennaPosition & o) const inline
References id, and undef.
     {
         ASSERT(!undef);
         ASSERT(!o.undef);
         return (id == o.id);
     }
Member Data Documentation
id
int veins::AntennaPosition::id protected
unique identifier of antenna returned by ChannelAccess::getId()
Referenced by isSameAntenna().
p
Coord veins::AntennaPosition::p protected
position for linear extrapolation
t
simtime_t veins::AntennaPosition::t protected
time for linear extrapolation
undef
bool veins::AntennaPosition::undef protected
true if created using default constructor
Referenced by isSameAntenna().
v
Coord veins::AntennaPosition::v protected
speed for linear extrapolation
The documentation for this class was generated from the following file:
AntennaPosition.h