Veins: veins::BaseApplLayer Class Reference
veins::BaseApplLayer Class Reference
Base class for the application layer.
#include <BaseApplLayer.h>
Public Types
enum BaseApplMessageKinds { LAST_BASE_APPL_MESSAGE_KIND = 25000 }
The message kinds this layer uses.
enum BaseApplControlKinds { LAST_BASE_APPL_CONTROL_KIND = 25500 }
The control message kinds this layer uses.
Public Member Functions
BaseApplLayer ()
BaseApplLayer (unsigned stacksize)
void initialize (int) override
Initialization of the module and some variables.
Public Member Functions inherited from veins::BaseLayer
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
void sendDelayedDown (cMessage *, simtime_t_cref)
Sends a message delayed to the lower layer.
virtual const LAddress::L3Type myApplAddr () const
Return my application layer address.
Handle Messages
Functions to redefine by the programmer
These are the functions provided to add own functionality to your modules. These functions are called whenever a self message or a data message from the upper or lower layer arrives respectively.
void handleSelfMsg (cMessage *msg) override
Handle self messages such as timer...
void handleLowerMsg (cMessage *msg) override
Handle messages from lower layer.
void handleLowerControl (cMessage *msg) override
Handle control messages from lower layer.
void handleUpperMsg (cMessage *msg) override
Handle messages from upper layer.
void handleUpperControl (cMessage *msg) override
Handle control messages from upper layer.
Protected Member Functions inherited from veins::BaseLayer
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
int headerLength
Length of the ApplPkt header.
Protected Attributes inherited from veins::BaseLayer
PassedMessage * passedMsg
The last message passed through this layer.
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Public Attributes inherited from veins::BaseLayer
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Base class for the application layer.
This is the generic class for all application layer modules. If you want to implement your own application layer you have to subclass your module from this class.
Author
Daniel Willkomm
Member Enumeration Documentation
BaseApplControlKinds
enum veins::BaseApplLayer::BaseApplControlKinds
The control message kinds this layer uses.
Enumerator
LAST_BASE_APPL_CONTROL_KIND
Stores the id on which classes extending BaseAppl should continue their own control kinds.
{
         /** Stores the id on which classes extending BaseAppl should
          * continue their own control kinds.*/
         LAST_BASE_APPL_CONTROL_KIND = 25500,
     };
BaseApplMessageKinds
enum veins::BaseApplLayer::BaseApplMessageKinds
The message kinds this layer uses.
Enumerator
LAST_BASE_APPL_MESSAGE_KIND
Stores the id on which classes extending BaseAppl should continue their own message kinds.
{
         /** Stores the id on which classes extending BaseAppl should
          * continue their own message kinds.*/
         LAST_BASE_APPL_MESSAGE_KIND = 25000,
     };
Constructor & Destructor Documentation
BaseApplLayer() [1/2]
veins::BaseApplLayer::BaseApplLayer () inline
         : BaseLayer()
     {
     }
BaseApplLayer() [2/2]
veins::BaseApplLayer::BaseApplLayer (unsigned stacksize) inline
         : BaseLayer(stacksize)
     {
     }
Member Function Documentation
handleLowerControl()
void veins::BaseApplLayer::handleLowerControl (cMessage * msg) inline override protected virtual
Handle control messages from lower layer.
The basic application layer just silently deletes all messages it receives.
Implements veins::BaseLayer.
     {
         EV << "BaseApplLayer: handleLowerControl not redefined; delete msg\n";
         delete msg;
     };
handleLowerMsg()
void veins::BaseApplLayer::handleLowerMsg (cMessage * msg) inline override protected virtual
Handle messages from lower layer.
Redefine this function if you want to process messages from lower layers.
The basic application layer just silently deletes all messages it receives.
Implements veins::BaseLayer.
Reimplemented in veins::DemoBaseApplLayer.
     {
         EV << "BaseApplLayer: handleLowerMsg not redefined; delete msg\n";
         delete msg;
     };
handleSelfMsg()
void veins::BaseApplLayer::handleSelfMsg (cMessage * msg) inline override protected virtual
Handle self messages such as timer...
Define this function if you want to process timer or other kinds of self messages
Implements veins::BaseLayer.
Reimplemented in veins::DemoBaseApplLayer, veins::TraCIDemo11p, and veins::MyVeinsApp.
     {
         EV << "BaseApplLayer: handleSelfMsg not redefined; delete msg\n";
         delete msg;
     };
handleUpperControl()
void veins::BaseApplLayer::handleUpperControl (cMessage * msg) inline override protected virtual
Handle control messages from upper layer.
Implements veins::BaseLayer.
     {
         ASSERT(false);
         throw cRuntimeError("Application has no upper layers!");
         delete msg;
     }
handleUpperMsg()
void veins::BaseApplLayer::handleUpperMsg (cMessage * msg) inline override protected virtual
Handle messages from upper layer.
This function is pure virtual here, because there is no reasonable guess what to do with it by default.
Implements veins::BaseLayer.
     {
         ASSERT(false);
         throw cRuntimeError("Application has no upper layers!");
         delete msg;
     }
initialize()
void BaseApplLayer::initialize (int stage) override
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseLayer.
Then we have to intialize the gates and - if necessary - some own variables.
References headerLength, and veins::BaseLayer::initialize().
Referenced by veins::DemoBaseApplLayer::initialize().
 {
     BaseLayer::initialize(stage);
     if (stage == 0) {
         headerLength = par("headerLength");
     }
 }
myApplAddr()
virtual const LAddress::L3Type veins::BaseApplLayer::myApplAddr () const inline protected virtual
Return my application layer address.
We use the node module index as application address
     {
         return LAddress::L3Type(getParentModule()->getIndex());
     };
sendDelayedDown()
void BaseApplLayer::sendDelayedDown (cMessage * msg, simtime_t_cref delay) protected
Sends a message delayed to the lower layer.
Send message down to lower layer.
References veins::PassedMessage::LOWER_DATA, veins::BaseLayer::lowerLayerOut, veins::PassedMessage::OUTGOING, and veins::BaseLayer::recordPacket().
Referenced by veins::DemoBaseApplLayer::sendDelayedDown().
 {
     recordPacket(PassedMessage::OUTGOING, PassedMessage::LOWER_DATA, msg);
     sendDelayed(msg, delay, lowerLayerOut);
 }
Member Data Documentation
headerLength
int veins::BaseApplLayer::headerLength protected
Length of the ApplPkt header.
Referenced by veins::DemoBaseApplLayer::initialize(), initialize(), and veins::DemoBaseApplLayer::populateWSM().
The documentation for this class was generated from the following files:
BaseApplLayer.h
BaseApplLayer.cc