Veins: veins::DeciderToPhyInterface Class Reference
veins::DeciderToPhyInterface Class Reference abstract
This class is the interface for a Decider to the BasePhyLayer.
#include <DeciderToPhyInterface.h>
Public Types
using AirFrameVector = std::list< AirFrame * >
Type for container of AirFrames.
Public Member Functions
virtual ~DeciderToPhyInterface ()
virtual void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out)=0
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
virtual double getNoiseFloorValue ()=0
Returns a constant which defines the noise floor in the passed time frame (in mW).
virtual void sendControlMsgToMac (cMessage *msg)=0
Called by the Decider to send a control message to the MACLayer.
virtual void sendUp (AirFrame *packet, DeciderResult *result)=0
Called to send an AirFrame with DeciderResult to the MACLayer.
virtual BaseWorldUtility * getWorldUtility ()=0
Returns a pointer to the simulations world-utility-module.
virtual void recordScalar (const char *name, double value, const char *unit=nullptr)=0
Utility method to enable a Decider, which isn't an OMNeT-module, to use the OMNeT-method 'recordScalar' with the help of and through its interface to BasePhyLayer.
virtual int getCurrentRadioChannel ()=0
Returns the channel currently used by the radio.
Detailed Description
This class is the interface for a Decider to the BasePhyLayer.
The Decider can do the following things using it:
   - get the current simulation time
    - get the list of AirFrames that intersect with a specific time interval (to
        calculate SNR)
    - tell the BasePhyLayer to hand an AirFrame up to the MACLayer
    - tell the BasePhyLayer to send a control message to the MACLayer
Member Typedef Documentation
AirFrameVector
using veins::DeciderToPhyInterface::AirFrameVector = std::list<AirFrame*>
Type for container of AirFrames.
Used as out-value in "getChannelInfo" method.
Constructor & Destructor Documentation
~DeciderToPhyInterface()
virtual veins::DeciderToPhyInterface::~DeciderToPhyInterface () inline virtual
     {
     }
Member Function Documentation
getChannelInfo()
virtual void veins::DeciderToPhyInterface::getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector & out) pure virtual
Fills the passed AirFrameVector with all AirFrames that intersect with the time interval [from, to].
Implemented in veins::BasePhyLayer.
Referenced by veins::BaseDecider::getChannelInfo().
getCurrentRadioChannel()
virtual int veins::DeciderToPhyInterface::getCurrentRadioChannel () pure virtual
Returns the channel currently used by the radio.
Implemented in veins::BasePhyLayer.
getNoiseFloorValue()
virtual double veins::DeciderToPhyInterface::getNoiseFloorValue () pure virtual
Returns a constant which defines the noise floor in the passed time frame (in mW).
Implemented in veins::BasePhyLayer.
Referenced by veins::Decider80211p::cca(), and veins::Decider80211p::checkIfSignalOk().
getWorldUtility()
virtual BaseWorldUtility* veins::DeciderToPhyInterface::getWorldUtility () pure virtual
Returns a pointer to the simulations world-utility-module.
Implemented in veins::BasePhyLayer.
recordScalar()
virtual void veins::DeciderToPhyInterface::recordScalar (const char * name, double value, const char * unit = nullptr) pure virtual
Utility method to enable a Decider, which isn't an OMNeT-module, to use the OMNeT-method 'recordScalar' with the help of and through its interface to BasePhyLayer.
The method-signature is taken from OMNeTs 'ccomponent.h' but made pure virtual here. See the original method-description below:
Records a double into the scalar result file.
Implemented in veins::BasePhyLayer.
Referenced by veins::Decider80211p::finish().
sendControlMsgToMac()
virtual void veins::DeciderToPhyInterface::sendControlMsgToMac (cMessage * msg) pure virtual
Called by the Decider to send a control message to the MACLayer.
Implemented in veins::BasePhyLayer.
Referenced by veins::Decider80211p::processNewSignal(), veins::Decider80211p::processSignalEnd(), and veins::Decider80211p::setChannelIdleStatus().
sendUp()
virtual void veins::DeciderToPhyInterface::sendUp (AirFrame * packet, DeciderResult * result) pure virtual
Called to send an AirFrame with DeciderResult to the MACLayer.
When a packet is completely received and not noise, the Decider call this function to send the packet together with the corresponding DeciderResult up to MACLayer
Implemented in veins::BasePhyLayer.
Referenced by veins::Decider80211p::processSignalEnd(), and veins::BaseDecider::processSignalEnd().
The documentation for this class was generated from the following file:
DeciderToPhyInterface.h