Veins: veins::NistErrorRate Class Reference
veins::NistErrorRate Class Reference
Model the error rate for different modulations and coding schemes.
#include <NistErrorRate.h>
Public Member Functions
NistErrorRate ()
Static Public Member Functions
static double getChunkSuccessRate (unsigned int datarate, enum Bandwidth bw, double snr_mW, uint32_t nbits)
Static Private Member Functions
static double calculatePe (double p, uint32_t bValue)
Return the coded BER for the given p and b.
static double getBpskBer (double snr)
Return BER of BPSK at the given SNR.
static double getQpskBer (double snr)
Return BER of QPSK at the given SNR.
static double get16QamBer (double snr)
Return BER of QAM16 at the given SNR.
static double get64QamBer (double snr)
Return BER of QAM64 at the given SNR.
static double getFecBpskBer (double snr, uint32_t nbits, uint32_t bValue)
Return BER of BPSK at the given SNR after applying FEC.
static double getFecQpskBer (double snr, uint32_t nbits, uint32_t bValue)
Return BER of QPSK at the given SNR after applying FEC.
static double getFec16QamBer (double snr, uint32_t nbits, uint32_t bValue)
Return BER of QAM16 at the given SNR after applying FEC.
static double getFec64QamBer (double snr, uint32_t nbits, uint32_t bValue)
Return BER of QAM64 at the given SNR after applying FEC.
Detailed Description
Model the error rate for different modulations and coding schemes.
Taken from the nist wifi model of ns-3
Constructor & Destructor Documentation
NistErrorRate()
NistErrorRate::NistErrorRate ()
 {
 }
Member Function Documentation
calculatePe()
double NistErrorRate::calculatePe (double p, uint32_t bValue) static private
Return the coded BER for the given p and b.
Parameters
p
bValue
Returns
BER
Referenced by getFec16QamBer(), getFec64QamBer(), getFecBpskBer(), and getFecQpskBer().
 {
     double D = std::sqrt(4.0 * p * (1.0 - p));
     double pe = 1.0;
     if (bValue == 1) {
         // code rate 1/2, use table 3.1.1
         pe = 0.5 * (36.0 * std::pow(D, 10) + 211.0 * std::pow(D, 12) + 1404.0 * std::pow(D, 14) + 11633.0 * std::pow(D, 16) + 77433.0 * std::pow(D, 18) + 502690.0 * std::pow(D, 20) + 3322763.0 * std::pow(D, 22) + 21292910.0 * std::pow(D, 24) + 134365911.0 * std::pow(D, 26));
     }
     else if (bValue == 2) {
         // code rate 2/3, use table 3.1.2
         pe = 1.0 / (2.0 * bValue) * (3.0 * std::pow(D, 6) + 70.0 * std::pow(D, 7) + 285.0 * std::pow(D, 8) + 1276.0 * std::pow(D, 9) + 6160.0 * std::pow(D, 10) + 27128.0 * std::pow(D, 11) + 117019.0 * std::pow(D, 12) + 498860.0 * std::pow(D, 13) + 2103891.0 * std::pow(D, 14) + 8784123.0 * std::pow(D, 15));
     }
     else if (bValue == 3) {
         // code rate 3/4, use table 3.1.2
         pe = 1.0 / (2.0 * bValue) * (42.0 * std::pow(D, 5) + 201.0 * std::pow(D, 6) + 1492.0 * std::pow(D, 7) + 10469.0 * std::pow(D, 8) + 62935.0 * std::pow(D, 9) + 379644.0 * std::pow(D, 10) + 2253373.0 * std::pow(D, 11) + 13073811.0 * std::pow(D, 12) + 75152755.0 * std::pow(D, 13) + 428005675.0 * std::pow(D, 14));
     }
     else {
         ASSERT(false);
     }
     return pe;
 }
get16QamBer()
double NistErrorRate::get16QamBer (double snr) static private
Return BER of QAM16 at the given SNR.
Parameters
snr snr value
Returns
BER of QAM16 at the given SNR
Referenced by getFec16QamBer().
 {
     double z = std::sqrt(snr / (5.0 * 2.0));
     double ber = 0.75 * 0.5 * erfc(z);
     return ber;
 }
get64QamBer()
double NistErrorRate::get64QamBer (double snr) static private
Return BER of QAM64 at the given SNR.
Parameters
snr snr value
Returns
BER of QAM64 at the given SNR
Referenced by getFec64QamBer().
 {
     double z = std::sqrt(snr / (21.0 * 2.0));
     double ber = 7.0 / 12.0 * 0.5 * erfc(z);
     return ber;
 }
getBpskBer()
double NistErrorRate::getBpskBer (double snr) static private
Return BER of BPSK at the given SNR.
Parameters
snr snr value
Returns
BER of BPSK at the given SNR
Referenced by getFecBpskBer().
 {
     double z = std::sqrt(snr);
     double ber = 0.5 * erfc(z);
     return ber;
 }
getChunkSuccessRate()
double NistErrorRate::getChunkSuccessRate (unsigned int datarate, enum Bandwidth bw, double snr_mW, uint32_t nbits) static
References getFec16QamBer(), getFec64QamBer(), getFecBpskBer(), getFecQpskBer(), veins::getMCS(), veins::ofdm_bpsk_r_1_2, veins::ofdm_bpsk_r_3_4, veins::ofdm_qam16_r_1_2, veins::ofdm_qam16_r_3_4, veins::ofdm_qam64_r_2_3, veins::ofdm_qam64_r_3_4, veins::ofdm_qpsk_r_1_2, and veins::ofdm_qpsk_r_3_4.
Referenced by veins::Decider80211p::packetOk().
 {
     // get mcs from datarate and bw
     MCS mcs = getMCS(datarate, bw);
     // compute success rate depending on mcs
     switch (mcs) {
     case MCS::ofdm_bpsk_r_1_2:
         return getFecBpskBer(snr_mW, nbits, 1);
         break;
     case MCS::ofdm_bpsk_r_3_4:
         return getFecBpskBer(snr_mW, nbits, 3);
         break;
     case MCS::ofdm_qpsk_r_1_2:
         return getFecQpskBer(snr_mW, nbits, 1);
         break;
     case MCS::ofdm_qpsk_r_3_4:
         return getFecQpskBer(snr_mW, nbits, 3);
         break;
     case MCS::ofdm_qam16_r_1_2:
         return getFec16QamBer(snr_mW, nbits, 1);
         break;
     case MCS::ofdm_qam16_r_3_4:
         return getFec16QamBer(snr_mW, nbits, 3);
         break;
     case MCS::ofdm_qam64_r_2_3:
         return getFec64QamBer(snr_mW, nbits, 2);
         break;
     case MCS::ofdm_qam64_r_3_4:
         return getFec64QamBer(snr_mW, nbits, 3);
         break;
     default:
         ASSERT2(false, "Invalid MCS chosen");
         break;
     }
     return 0;
 }
getFec16QamBer()
double NistErrorRate::getFec16QamBer (double snr, uint32_t nbits, uint32_t bValue) static private
Return BER of QAM16 at the given SNR after applying FEC.
Parameters
snr snr value
nbits the number of bits in the chunk
bValue
Returns
BER of QAM16 at the given SNR after applying FEC
References calculatePe(), and get16QamBer().
Referenced by getChunkSuccessRate().
 {
     double ber = get16QamBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = std::min(pe, 1.0);
     double pms = std::pow(1 - pe, static_cast<double>(nbits));
     return pms;
 }
getFec64QamBer()
double NistErrorRate::getFec64QamBer (double snr, uint32_t nbits, uint32_t bValue) static private
Return BER of QAM64 at the given SNR after applying FEC.
Parameters
snr snr value
nbits the number of bits in the chunk
bValue
Returns
BER of QAM64 at the given SNR after applying FEC
References calculatePe(), and get64QamBer().
Referenced by getChunkSuccessRate().
 {
     double ber = get64QamBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = std::min(pe, 1.0);
     double pms = std::pow(1 - pe, static_cast<double>(nbits));
     return pms;
 }
getFecBpskBer()
double NistErrorRate::getFecBpskBer (double snr, uint32_t nbits, uint32_t bValue) static private
Return BER of BPSK at the given SNR after applying FEC.
Parameters
snr snr value
nbits the number of bits in the chunk
bValue
Returns
BER of BPSK at the given SNR after applying FEC
References calculatePe(), and getBpskBer().
Referenced by getChunkSuccessRate().
 {
     double ber = getBpskBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = std::min(pe, 1.0);
     double pms = std::pow(1 - pe, (double) nbits);
     return pms;
 }
getFecQpskBer()
double NistErrorRate::getFecQpskBer (double snr, uint32_t nbits, uint32_t bValue) static private
Return BER of QPSK at the given SNR after applying FEC.
Parameters
snr snr value
nbits the number of bits in the chunk
bValue
Returns
BER of QPSK at the given SNR after applying FEC
References calculatePe(), and getQpskBer().
Referenced by getChunkSuccessRate().
 {
     double ber = getQpskBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = std::min(pe, 1.0);
     double pms = std::pow(1 - pe, (double) nbits);
     return pms;
 }
getQpskBer()
double NistErrorRate::getQpskBer (double snr) static private
Return BER of QPSK at the given SNR.
Parameters
snr snr value
Returns
BER of QPSK at the given SNR
Referenced by getFecQpskBer().
 {
     double z = std::sqrt(snr / 2.0);
     double ber = 0.5 * erfc(z);
     return ber;
 }
The documentation for this class was generated from the following files:
NistErrorRate.h
NistErrorRate.cc