Veins: veins::LinearMobility Class Reference
veins::LinearMobility Class Reference
Linear movement model.
#include <LinearMobility.h>
Public Member Functions
void initialize (int) override
Initializes mobility model parameters.
Public Member Functions inherited from veins::BaseMobility
BaseMobility ()
BaseMobility (unsigned stacksize)
void handleMessage (cMessage *msg) override
This modules should only receive self-messages.
void initialize (int) override
Initializes mobility model parameters.
void finish () override
Delete dynamically allocated objects.
virtual Coord getPositionAt (simtime_t_cref stWhen) const
Returns the current position at the given simulation time.
virtual Coord getCurrentOrientation () const
virtual Coord getCurrentSpeed () const
Returns the current speed at the current simulation time.
virtual Coord getCurrentDirection () const
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Protected Member Functions
void makeMove () override
Move the host.
void fixIfHostGetsOutside () override
Should be redefined in subclasses.
Protected Member Functions inherited from veins::BaseMobility
virtual int iconSizeTagToSize (const char *tag)
Maps the passed icon size tag (is) to an actual size in pixels.
virtual const char * iconSizeToTag (double size)
Maps the passed size in pixels to an appropriate icon size tag (is).
virtual void handleSelfMsg (cMessage *)
Called upon arrival of a self messages.
virtual void handleBorderMsg (cMessage *)
Called upon arrival of a border messages.
virtual void updatePosition ()
Update the position information for this node.
double playgroundSizeX () const
Returns the width of the playground.
double playgroundSizeY () const
Returns the height of the playground.
double playgroundSizeZ () const
Returns the height of the playground.
Coord getRandomPosition ()
Random position somewhere in the playground.
bool handleIfOutside (BorderPolicy, Coord &, Coord &, Coord &, double &)
Main border handling function.
BorderHandling checkIfOutside (Coord, Coord &)
Checks whether the host is outside the playground and returns where.
void goToBorder (BorderPolicy, BorderHandling, Coord &, Coord &)
calculate the step to reach the border
void reflectCoordinate (BorderHandling border, Coord &c)
helperfunction for reflectIfOutside() to reflect a Coordinate at a given border
void reflectIfOutside (BorderHandling, Coord &, Coord &, Coord &, double &)
Utility function to reflect the node if it goes outside the playground.
void wrapIfOutside (BorderHandling, Coord &, Coord &)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the playground.
void placeRandomlyIfOutside (Coord &)
Utility function to place the node randomly if it goes outside the playground.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
double angle
angle of linear motion
double acceleration
acceleration of linear motion
Coord stepTarget
always stores the last step for position display update
Protected Attributes inherited from veins::BaseMobility
BaseWorldUtility * world
Pointer to BaseWorldUtility – these two must know each other.
Move move
Stores the current position and move pattern of the host.
simtime_t updateInterval
Time interval (in seconds) to update the hosts position.
cMessage * moveMsg
Self message to trigger movement.
bool scaleNodeByDepth
Enable depth dependent scaling of nodes when 3d and tkenv is used.
double playgroundScaleX
Scaling of the playground in X direction.
double playgroundScaleY
Scaling of the playground in Y direction.
double origDisplayWidth
The original width the node is displayed width.
double origDisplayHeight
The original height the node is displayed width.
double origIconSize
The original size of the icon of the node.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from veins::BaseMobility
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Selects how a node should behave if it reaches the edge of the playground.
enum BaseMobilityMsgKinds { MOVE_HOST = 21311, MOVE_TO_BORDER, LAST_BASE_MOBILITY_KIND }
The kind field of messages.
enum BorderHandling {
NOWHERE, X_SMALLER, X_BIGGER, Y_SMALLER,
Y_BIGGER, Z_SMALLER, Z_BIGGER
}
Specifies which border actually has been reached.
Static Public Attributes inherited from veins::BaseMobility
static const simsignal_t mobilityStateChangedSignal = registerSignal("org_car2x_veins_base_modules_mobilityStateChanged")
Store the category of HostMove.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Linear movement model.
See NED file for more info.
This mobility module expects a torus as playground ("useTorus" Parameter of BaseWorldUtility module).
NOTE: Does not yet support 3-dimensional movement.
Author
Emin Ilker Cetinbas
Member Function Documentation
fixIfHostGetsOutside()
void LinearMobility::fixIfHostGetsOutside () override protected virtual
Should be redefined in subclasses.
Should invoke handleIfOutside() and pass the references to the parameters to be modified.
Additional action after border handling (such as choosing a new target position if the BorderPolicy is PLACERANDOMLY) should be implemented here.
See also
HandleIfOutside
Reimplemented from veins::BaseMobility.
References angle, veins::BaseMobility::handleIfOutside(), stepTarget, veins::BaseMobility::WRAP, and veins::Coord::ZERO.
Referenced by makeMove().
 {
     Coord dummy = Coord::ZERO;
     handleIfOutside(WRAP, stepTarget, dummy, dummy, angle);
 }
initialize()
void LinearMobility::initialize (int stage) override
Initializes mobility model parameters.
References acceleration, angle, veins::Move::getStartPos(), veins::BaseMobility::initialize(), veins::BaseMobility::move, veins::Move::setSpeed(), and stepTarget.
 {
     BaseMobility::initialize(stage);
     EV_TRACE << "initializing LinearMobility stage " << stage << endl;
     if (stage == 0) {
         move.setSpeed(par("speed").doubleValue());
         acceleration = par("acceleration");
         angle = par("angle");
         angle = fmod(angle, 360);
     }
     else if (stage == 1) {
         stepTarget = move.getStartPos();
     }
 }
makeMove()
void LinearMobility::makeMove () override protected virtual
Move the host.
Move the host if the destination is not reached yet.
Otherwise calculate a new random position
Reimplemented from veins::BaseMobility.
References acceleration, angle, fixIfHostGetsOutside(), veins::Move::getSpeed(), veins::Move::getStartPos(), veins::Coord::info(), veins::Move::info(), M_PI, veins::BaseMobility::move, veins::Move::setDirectionByTarget(), veins::Move::setSpeed(), veins::Move::setStart(), stepTarget, veins::BaseMobility::updateInterval, veins::Coord::x, and veins::Coord::y.
 {
     EV_TRACE << "start makeMove " << move.info() << endl;
     move.setStart(stepTarget, simTime());
     stepTarget.x = (move.getStartPos().x + move.getSpeed() * cos(M_PI * angle / 180) * SIMTIME_DBL(updateInterval));
     stepTarget.y = (move.getStartPos().y + move.getSpeed() * sin(M_PI * angle / 180) * SIMTIME_DBL(updateInterval));
     move.setDirectionByTarget(stepTarget);
     EV_TRACE << "new stepTarget: " << stepTarget.info() << endl;
     // accelerate
     move.setSpeed(move.getSpeed() + acceleration * SIMTIME_DBL(updateInterval));
     fixIfHostGetsOutside();
 }
Member Data Documentation
acceleration
double veins::LinearMobility::acceleration protected
acceleration of linear motion
Referenced by initialize(), and makeMove().
angle
double veins::LinearMobility::angle protected
angle of linear motion
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
stepTarget
Coord veins::LinearMobility::stepTarget protected
always stores the last step for position display update
Referenced by fixIfHostGetsOutside(), initialize(), and makeMove().
The documentation for this class was generated from the following files:
LinearMobility.h
LinearMobility.cc