Veins: veins::PERModel Class Reference
veins::PERModel Class Reference
This class applies a parameterized packet error rate to incoming packets.
#include <PERModel.h>
Public Member Functions
PERModel (cComponent *owner, double per)
The PERModel constructor takes as argument the packet error rate to apply (must be between 0 and 1).
void filterSignal (Signal *) override
Has to be overriden by every implementation.
Public Member Functions inherited from veins::AnalogueModel
AnalogueModel (cComponent *owner)
virtual ~AnalogueModel ()
virtual bool neverIncreasesPower ()
If the model never increases the power level of any signal given to filterSignal, it returns true here.
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Attributes
double packetErrorRate
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
This class applies a parameterized packet error rate to incoming packets.
This allows the user to easily study the robustness of its system to packet loss.
Author
Jérôme Rousselot jerom.nosp@m.e.ro.nosp@m.ussel.nosp@m.ot@c.nosp@m.sem.c.nosp@m.h
Constructor & Destructor Documentation
PERModel()
veins::PERModel::PERModel (cComponent * owner, double per) inline
The PERModel constructor takes as argument the packet error rate to apply (must be between 0 and 1).
         : AnalogueModel(owner)
         , packetErrorRate(per)
     {
         ASSERT(per <= 1 && per >= 0);
     }
Member Function Documentation
filterSignal()
void PERModel::filterSignal (Signal * signal) override virtual
Has to be overriden by every implementation.
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Parameters
signal The signal to filter.
Implements veins::AnalogueModel.
References veins::AntennaPosition::getPositionAt(), veins::Signal::getReceiverPoa(), veins::Signal::getSenderPoa(), packetErrorRate, veins::POA::pos, and RNGCONTEXT.
 {
     auto senderPos = signal->getSenderPoa().pos.getPositionAt();
     auto receiverPos = signal->getReceiverPoa().pos.getPositionAt();
     double attenuationFactor = 1; // no attenuation
     if (packetErrorRate > 0 && RNGCONTEXT uniform(0, 1) < packetErrorRate) {
         attenuationFactor = 0; // absorb all energy so that the receveir cannot receive anything
     }
     *signal *= attenuationFactor;
 }
Member Data Documentation
packetErrorRate
double veins::PERModel::packetErrorRate protected
Referenced by filterSignal().
The documentation for this class was generated from the following files:
PERModel.h
PERModel.cc