Veins: veins::TraCITrafficLightAbstractLogic Class Reference
veins::TraCITrafficLightAbstractLogic Class Reference abstract
Base class to simplify implementation of traffic light logics.
#include <TraCITrafficLightAbstractLogic.h>
Public Member Functions
TraCITrafficLightAbstractLogic ()
~TraCITrafficLightAbstractLogic () override
Protected Member Functions
void initialize () override
void handleMessage (cMessage *msg) override
virtual void handleSelfMsg (cMessage *msg)
virtual void handleApplMsg (cMessage *msg)=0
virtual void handleTlIfMsg (TraCITrafficLightMessage *tlMsg)=0
virtual void handlePossibleSwitch ()=0
Protected Attributes
cMessage * switchTimer
Detailed Description
Base class to simplify implementation of traffic light logics.
already provides multiplexing of different message types to message handlers and a special handler to be executed right before the TraCI server performs a phase switch
Constructor & Destructor Documentation
TraCITrafficLightAbstractLogic()
TraCITrafficLightAbstractLogic::TraCITrafficLightAbstractLogic ()
     : cSimpleModule()
     , switchTimer(nullptr)
 {
 }
~TraCITrafficLightAbstractLogic()
TraCITrafficLightAbstractLogic::~TraCITrafficLightAbstractLogic () override
References switchTimer.
 {
     cancelAndDelete(switchTimer);
 }
Member Function Documentation
handleApplMsg()
virtual void veins::TraCITrafficLightAbstractLogic::handleApplMsg (cMessage * msg) protected pure virtual
Implemented in veins::TraCITrafficLightSimpleLogic.
Referenced by handleMessage().
handleMessage()
void TraCITrafficLightAbstractLogic::handleMessage (cMessage * msg) override protected
References handleApplMsg(), handleSelfMsg(), handleTlIfMsg(), and switchTimer.
 {
     if (msg->isSelfMessage()) {
         handleSelfMsg(msg);
     }
     else if (msg->arrivedOn("interface$i")) {
         TraCITrafficLightMessage* tlMsg = check_and_cast<TraCITrafficLightMessage*>(msg);
         // always check for changed switch time and (re-)schedule switch handler if so
         if (tlMsg->getChangedAttribute() == TrafficLightAtrributeType::SWITCHTIME) {
             // schedule handler right before the switch
             cancelEvent(switchTimer);
             // make sure the message is not scheduled to the past
             simtime_t nextTick = std::max(SimTime(std::stoi(tlMsg->getNewValue()), SIMTIME_MS), simTime());
             scheduleAt(nextTick, switchTimer);
         }
         // defer further handling to subclass implementation
         handleTlIfMsg(tlMsg);
     }
     else if (msg->arrivedOn("applLayer$i")) {
         handleApplMsg(msg);
     }
     else {
         throw cRuntimeError("Unknown message arrived on %s", msg->getArrivalGate()->getName());
     }
 }
handlePossibleSwitch()
virtual void veins::TraCITrafficLightAbstractLogic::handlePossibleSwitch () protected pure virtual
Implemented in veins::TraCITrafficLightSimpleLogic.
Referenced by handleSelfMsg().
handleSelfMsg()
void TraCITrafficLightAbstractLogic::handleSelfMsg (cMessage * msg) protected virtual
References handlePossibleSwitch(), and switchTimer.
Referenced by handleMessage().
 {
     if (msg == switchTimer) {
         handlePossibleSwitch();
     }
 }
handleTlIfMsg()
virtual void veins::TraCITrafficLightAbstractLogic::handleTlIfMsg (TraCITrafficLightMessage * tlMsg) protected pure virtual
Implemented in veins::TraCITrafficLightSimpleLogic.
Referenced by handleMessage().
initialize()
void TraCITrafficLightAbstractLogic::initialize () override protected
References switchTimer.
 {
     switchTimer = new cMessage("trySwitch");
 }
Member Data Documentation
switchTimer
cMessage* veins::TraCITrafficLightAbstractLogic::switchTimer protected
Referenced by handleMessage(), handleSelfMsg(), initialize(), and ~TraCITrafficLightAbstractLogic().
The documentation for this class was generated from the following files:
TraCITrafficLightAbstractLogic.h
TraCITrafficLightAbstractLogic.cc