Veins: veins::NicEntryDebug Class Reference
veins::NicEntryDebug Class Reference
NicEntry is used by ConnectionManager to store the necessary information for each nic.
#include <NicEntryDebug.h>
Public Member Functions
NicEntryDebug (cComponent *owner)
Constructor, initializes all members.
~NicEntryDebug () override
Removes all dynamically created out-/ingates.
void connectTo (NicEntry *other) override
Connect two nics.
void disconnectFrom (NicEntry *other) override
Disconnect two nics.
Public Member Functions inherited from veins::NicEntry
NicEntry (cComponent *owner)
Constructor, initializes all members.
virtual ~NicEntry ()
Destructor – needs to be there...
const GateList & getGateList ()
return the actual gateList
bool isConnected (const NicEntry *other)
Checks if this nic is connected to the "other" nic.
const cGate * getOutGateTo (const NicEntry *to)
Called by P2PPhyLayer.
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Types
using GateStack = std::vector< cGate * >
Protected Member Functions
cGate * requestInGate (void)
Returns a free in gate of the nic.
cGate * requestOutGate (void)
Returns a free out gate of the nic.
int collectGates (const char *pattern, GateStack &gates)
Collects all free gates with a certain pattern as names and puts them on a stack.
void collectFreeGates ()
Iterates over all existing gates of this NicEntries nic and host and checks wether they are useable by this nic entry.
Protected Attributes
int inCnt
Number of in gates allocated for the nic so far.
int outCnt
Number of out gates allocated for the nic so far.
bool checkFreeGates
Check for unknown free gates before next gate request.
GateStack freeInGates
In Gates that were once used but are not connected now.
GateStack freeOutGates
Out Gates that were once used but are not connected now.
Protected Attributes inherited from veins::NicEntry
GateList outConns
Outgoing connections of this nic.
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Additional Inherited Members
Public Types inherited from veins::NicEntry
typedef std::map< const NicEntry *, cGate *, NicEntryComparator > GateList
Type for map from NicEntry pointer to a gate.
Public Attributes inherited from veins::NicEntry
int nicId
module id of the nic for which information is stored
cModule * nicPtr
Pointer to the NIC module.
int hostId
Module id of the host module this nic belongs to.
Coord pos
Geographic location of the nic.
Heading heading
Heading (angle) of the nic.
ChannelAccess * chAccess
Points to this nics ChannelAccess module.
Detailed Description
NicEntry is used by ConnectionManager to store the necessary information for each nic.
Author
Daniel Willkomm
See also
ConnectionManager, NicEntry
Member Typedef Documentation
GateStack
using veins::NicEntryDebug::GateStack = std::vector<cGate*> protected
Constructor & Destructor Documentation
NicEntryDebug()
veins::NicEntryDebug::NicEntryDebug (cComponent * owner) inline
Constructor, initializes all members.
         : NicEntry(owner)
         , inCnt(0)
         , outCnt(0)
         , checkFreeGates(true){};
~NicEntryDebug()
veins::NicEntryDebug::~NicEntryDebug () inline override
Removes all dynamically created out-/ingates.
     {
     }
Member Function Documentation
collectFreeGates()
void NicEntryDebug::collectFreeGates () protected
Iterates over all existing gates of this NicEntries nic and host and checks wether they are useable by this nic entry.
This method is necessary if a nic was unregistered from its connection manager during a simulation and is then again registered with one. When unregistered the gates created by this NicEntryDebug are not deleted so they can be collected and reused again when the nic is registered again.
References checkFreeGates, collectGates(), freeInGates, freeOutGates, inCnt, and outCnt.
Referenced by requestInGate(), and requestOutGate().
 {
     if (!checkFreeGates) return;
     inCnt = collectGates("in%d-%d", freeInGates);
     EV_TRACE << "found " << inCnt << " already existing usable in-gates." << endl;
     outCnt = collectGates("out%d-%d", freeOutGates);
     EV_TRACE << "found " << inCnt << " already existing usable out-gates." << endl;
     checkFreeGates = false;
 }
collectGates()
int NicEntryDebug::collectGates (const char * pattern, GateStack & gates) protected
Collects all free gates with a certain pattern as names and puts them on a stack.
Parameters
pattern The naming pattern of the gates, something like "out%d-%d" where the first d is filled with the nic id and the second with an incrementing counter.
gates The gate stack in which to put the found gates.
Returns
the number of free gates found.
References veins::NicEntry::nicId, and veins::NicEntry::nicPtr.
Referenced by collectFreeGates().
 {
     cModule* host = nicPtr->getParentModule();
     int i = 1;
     char gateName[20];
     // create the unique name for the gate (composed of the nic module id and a counter)
     sprintf(gateName, pattern, nicId, i);
     while (host->hasGate(gateName)) {
         cGate* hostGate = host->gate(gateName);
         if (hostGate->isConnectedOutside()) {
             throw cRuntimeError("Gate %s is still connected but not registered with this NicEntry. Either the last NicEntry for this NIC did not clean up correctly or another gate creation module is interfering with this one!", gateName);
         }
         ASSERT(hostGate->isConnectedInside());
         gates.push_back(hostGate);
         ++i;
         sprintf(gateName, pattern, nicId, i);
     }
     return i - 1;
 }
connectTo()
void NicEntryDebug::connectTo (NicEntry * other) override virtual
Connect two nics.
Establish unidirectional connection with other nic
Parameters
other reference to remote nic (other NicEntry)
This function acquires an in gate at the remote nic and an out gate at this nic, connects the two and updates the freeInGate, freeOutGate and outConns data sets.
Implements veins::NicEntry.
References veins::NicEntry::nicId, veins::NicEntry::outConns, requestInGate(), and requestOutGate().
 {
     EV_TRACE << "connecting nic #" << nicId << " and #" << other->nicId << endl;
     NicEntryDebug* otherNic = (NicEntryDebug*) other;
     cGate* localoutgate = requestOutGate();
     localoutgate->connectTo(otherNic->requestInGate());
     outConns[other] = localoutgate->getPathStartGate();
 }
disconnectFrom()
void NicEntryDebug::disconnectFrom (NicEntry * other) override virtual
Disconnect two nics.
Release unidirectional connection with other nic
Parameters
other reference to remote nic (other NicEntry)
Implements veins::NicEntry.
References freeInGates, freeOutGates, veins::NicEntry::nicId, and veins::NicEntry::outConns.
 {
     EV_TRACE << "disconnecting nic #" << nicId << " and #" << other->nicId << endl;
     NicEntryDebug* otherNic = (NicEntryDebug*) other;
     // search the connection in the outConns list
     GateList::iterator p = outConns.find(other);
     // no need to check whether entry is valid; is already check by ConnectionManager isConnected
     // get the hostGate
     // order is phyGate->nicGate->hostGate
     cGate* hostGate = p->second->getNextGate()->getNextGate();
     // release local out gate
     freeOutGates.push_back(hostGate);
     // release remote in gate
     otherNic->freeInGates.push_back(hostGate->getNextGate());
     // reset gates
     // hostGate->getNextGate()->connectTo(0);
     hostGate->disconnect();
     // delete the connection
     outConns.erase(p);
 }
requestInGate()
cGate * NicEntryDebug::requestInGate (void) protected
Returns a free in gate of the nic.
This checks the list of free in gates, if one is available it is returned. Otherwise, a new in gate is added to the nic.
References collectFreeGates(), freeInGates, inCnt, veins::NicEntry::nicId, and veins::NicEntry::nicPtr.
Referenced by connectTo().
 {
     collectFreeGates();
     // gate of the host
     cGate* hostGate;
     if (!freeInGates.empty()) {
         hostGate = freeInGates.back();
         freeInGates.pop_back();
     }
     else {
         char gateName[20];
         // we will have one more in gate
         ++inCnt;
         // get a unique name for the gate (composed of the nic module id and a counter)
         sprintf(gateName, "in%d-%d", nicId, inCnt);
         // create a new gate for the host module
         nicPtr->getParentModule()->addGate(gateName, cGate::INPUT);
         hostGate = nicPtr->getParentModule()->gate(gateName);
         // gate of the nic
         cGate* nicGate;
         // create a new gate for the nic module
         nicPtr->addGate(gateName, cGate::INPUT);
         nicGate = nicPtr->gate(gateName);
         // connect the hist gate with the nic gate
         hostGate->connectTo(nicGate);
         // pointer to the phy module
         ChannelAccess* phyModule;
         // gate of the phy module
         cGate* phyGate;
         // to avoid unnecessary dynamic_casting we check for a "phy"-named submodule first
         if ((phyModule = dynamic_cast<ChannelAccess*>(nicPtr->getSubmodule("phy"))) == nullptr) phyModule = FindModule<ChannelAccess*>::findSubModule(nicPtr);
         ASSERT(phyModule != nullptr);
         // create a new gate for the phy module
         phyModule->addGate(gateName, cGate::INPUT);
         phyGate = phyModule->gate(gateName);
         // connect the nic gate (the gate of the compound module) to
         // a "real" gate -- the gate of the phy module
         nicGate->connectTo(phyGate);
     }
     return hostGate;
 }
requestOutGate()
cGate * NicEntryDebug::requestOutGate (void) protected
Returns a free out gate of the nic.
returns a free out gate. If none is available it is created. See NicEntry::requestInGate for a detailed description
References collectFreeGates(), freeOutGates, veins::NicEntry::nicId, veins::NicEntry::nicPtr, and outCnt.
Referenced by connectTo().
 {
     collectFreeGates();
     // gate of the host
     cGate* hostGate;
     if (!freeOutGates.empty()) {
         hostGate = freeOutGates.back();
         freeOutGates.pop_back();
     }
     else {
         char gateName[20];
         // we will have one more out gate
         ++outCnt;
         // get a unique name for the gate (composed of the nic module id and a counter)
         sprintf(gateName, "out%d-%d", nicId, outCnt);
         // create a new gate for the host module
         nicPtr->getParentModule()->addGate(gateName, cGate::OUTPUT);
         hostGate = nicPtr->getParentModule()->gate(gateName);
         // gate of the nic
         cGate* nicGate;
         // create a new gate for the nic module
         nicPtr->addGate(gateName, cGate::OUTPUT);
         nicGate = nicPtr->gate(gateName);
         // connect the hist gate with the nic gate
         nicGate->connectTo(hostGate);
         // pointer to the phy module
         ChannelAccess* phyModule;
         // gate of the phy module
         cGate* phyGate;
         // to avoid unnecessary dynamic_casting we check for a "phy"-named submodule first
         if ((phyModule = dynamic_cast<ChannelAccess*>(nicPtr->getSubmodule("phy"))) == nullptr) phyModule = FindModule<ChannelAccess*>::findSubModule(nicPtr);
         ASSERT(phyModule != nullptr);
         // create a new gate for the phy module
         phyModule->addGate(gateName, cGate::OUTPUT);
         phyGate = phyModule->gate(gateName);
         // connect the nic gate (the gate of the compound module) to
         // a "real" gate -- the gate of the phy module
         phyGate->connectTo(nicGate);
     }
     return hostGate;
 }
Member Data Documentation
checkFreeGates
bool veins::NicEntryDebug::checkFreeGates protected
Check for unknown free gates before next gate request.
This flag is true after creation of the NicEntryDebug and assures that it checks for already existing in- and out-gates from a previous NicEntryDebug (which can happen if the same NIC is unregistered and later again registered with a connection manager.
Referenced by collectFreeGates().
freeInGates
GateStack veins::NicEntryDebug::freeInGates protected
In Gates that were once used but are not connected now.
Referenced by collectFreeGates(), disconnectFrom(), and requestInGate().
freeOutGates
GateStack veins::NicEntryDebug::freeOutGates protected
Out Gates that were once used but are not connected now.
Referenced by collectFreeGates(), disconnectFrom(), and requestOutGate().
inCnt
int veins::NicEntryDebug::inCnt protected
Number of in gates allocated for the nic so far.
Referenced by collectFreeGates(), and requestInGate().
outCnt
int veins::NicEntryDebug::outCnt protected
Number of out gates allocated for the nic so far.
Referenced by collectFreeGates(), and requestOutGate().
The documentation for this class was generated from the following files:
NicEntryDebug.h
NicEntryDebug.cc