Veins: veins::BaseBattery Class Reference
veins::BaseBattery Class Reference abstract
Base class for any power source.
#include <BaseBattery.h>
Public Member Functions
BaseBattery ()
BaseBattery (unsigned stacksize)
virtual int registerDevice (const std::string &name, int numAccounts)=0
Registers a power draining device with this battery.
virtual void draw (int drainID, DrawAmount &amount, int account)=0
Draws power from the battery.
State-of-charge interface
Other host modules should use these interfaces to obtain the state-of-charge of the battery.
Do NOT use BatteryState interfaces, which should be used only by Battery Stats modules.
virtual double getVoltage () const =0
get voltage (future support for non-voltage regulated h/w
virtual double estimateResidualRelative () const =0
current state of charge of the battery, relative to its rated nominal capacity [0..1]
virtual double estimateResidualAbs () const =0
current state of charge of the battery (mW-s)
virtual HostState::States getState () const =0
Current state of the battery.
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Additional Inherited Members
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Base class for any power source.
See "SimpleBattery" for an example implementation.
See also
SimpleBattery
Constructor & Destructor Documentation
BaseBattery() [1/2]
veins::BaseBattery::BaseBattery () inline
         : BaseModule()
     {
     }
BaseBattery() [2/2]
veins::BaseBattery::BaseBattery (unsigned stacksize) inline
         : BaseModule(stacksize)
     {
     }
Member Function Documentation
draw()
virtual void veins::BaseBattery::draw (int drainID, DrawAmount & amount, int account) pure virtual
Draws power from the battery.
The actual amount and type of power drawn is defined by the passed DrawAmount parameter. Can be an fixed single amount or an amount drawn over time. The drainID identifies the device which drains the power. "Account" identifies the account the power is drawn from. It is used for statistical evaluation only to see which activity of a device has used how much power. It does not affect functionality.
Referenced by veins::BatteryAccess::draw(), veins::BatteryAccess::drawCurrent(), and veins::BatteryAccess::drawEnergy().
estimateResidualAbs()
virtual double veins::BaseBattery::estimateResidualAbs () const pure virtual
current state of charge of the battery (mW-s)
estimateResidualRelative()
virtual double veins::BaseBattery::estimateResidualRelative () const pure virtual
current state of charge of the battery, relative to its rated nominal capacity [0..1]
getState()
virtual HostState::States veins::BaseBattery::getState () const pure virtual
Current state of the battery.
getVoltage()
virtual double veins::BaseBattery::getVoltage () const pure virtual
get voltage (future support for non-voltage regulated h/w
registerDevice()
virtual int veins::BaseBattery::registerDevice (const std::string & name, int numAccounts) pure virtual
Registers a power draining device with this battery.
Takes the name of the device as well as a number of accounts the devices draws power for (like rx, tx, idle for a radio device).
Returns an ID by which the device can identify itself to the battery.
Has to be implemented by actual battery implementations.
Referenced by veins::BatteryAccess::registerWithBattery().
The documentation for this class was generated from the following file:
BaseBattery.h