Veins: veins::Obstacle Class Reference
veins::Obstacle Class Reference
stores information about an Obstacle for ObstacleControl
#include <Obstacle.h>
Public Types
using Coords = std::vector< Coord >
Public Member Functions
Obstacle (std::string id, std::string type, double attenuationPerCut, double attenuationPerMeter)
void setShape (Coords shape)
const Coords & getShape () const
const Coord getBboxP1 () const
const Coord getBboxP2 () const
bool containsPoint (Coord Point) const
std::string getType () const
std::string getId () const
double getAttenuationPerCut () const
double getAttenuationPerMeter () const
std::vector< double > getIntersections (const Coord &senderPos, const Coord &receiverPos) const
get a list of points (in [0, 1]) along the line between sender and receiver where the beam intersects with this obstacle
Public Attributes
AnnotationManager::Annotation * visualRepresentation
Protected Attributes
std::string id
std::string type
double attenuationPerCut
in dB.
double attenuationPerMeter
in dB / m.
Coords coords
Coord bboxP1
Coord bboxP2
Detailed Description
stores information about an Obstacle for ObstacleControl
Member Typedef Documentation
Coords
using veins::Obstacle::Coords = std::vector<Coord>
Constructor & Destructor Documentation
Obstacle()
Obstacle::Obstacle (std::string id, std::string type, double attenuationPerCut, double attenuationPerMeter)
     : visualRepresentation(nullptr)
     , id(id)
     , type(type)
     , attenuationPerCut(attenuationPerCut)
     , attenuationPerMeter(attenuationPerMeter)
 {
 }
Member Function Documentation
containsPoint()
bool Obstacle::containsPoint (Coord Point) const
References getShape(), anonymous_namespace{BBoxLookup.cc}::intersects(), veins::Coord::x, and veins::Coord::y.
 {
     bool isInside = false;
     const Obstacle::Coords& shape = getShape();
     Obstacle::Coords::const_iterator i = shape.begin();
     Obstacle::Coords::const_iterator j = (shape.rbegin() + 1).base();
     for (; i != shape.end(); j = i++) {
         bool inYRangeUp = (point.y >= i->y) && (point.y < j->y);
         bool inYRangeDown = (point.y >= j->y) && (point.y < i->y);
         bool inYRange = inYRangeUp || inYRangeDown;
         if (!inYRange) continue;
         bool intersects = point.x < (i->x + ((point.y - i->y) * (j->x - i->x) / (j->y - i->y)));
         if (!intersects) continue;
         isInside = !isInside;
     }
     return isInside;
 }
getAttenuationPerCut()
double Obstacle::getAttenuationPerCut () const
References attenuationPerCut.
 {
     return attenuationPerCut;
 }
getAttenuationPerMeter()
double Obstacle::getAttenuationPerMeter () const
References attenuationPerMeter.
 {
     return attenuationPerMeter;
 }
getBboxP1()
const Coord Obstacle::getBboxP1 () const
References bboxP1.
 {
     return bboxP1;
 }
getBboxP2()
const Coord Obstacle::getBboxP2 () const
References bboxP2.
 {
     return bboxP2;
 }
getId()
std::string Obstacle::getId () const
References id.
 {
     return id;
 }
getIntersections()
std::vector< double > Obstacle::getIntersections (const Coord & senderPos, const Coord & receiverPos) const
get a list of points (in [0, 1]) along the line between sender and receiver where the beam intersects with this obstacle
References getShape(), and anonymous_namespace{Obstacle.cc}::segmentsIntersectAt().
 {
     std::vector<double> intersectAt;
     const Obstacle::Coords& shape = getShape();
     Obstacle::Coords::const_iterator i = shape.begin();
     Obstacle::Coords::const_iterator j = (shape.rbegin() + 1).base();
     for (; i != shape.end(); j = i++) {
         const Coord& c1 = *i;
         const Coord& c2 = *j;
         double i = segmentsIntersectAt(senderPos, receiverPos, c1, c2);
         if (i != -1) {
             intersectAt.push_back(i);
         }
     }
     std::sort(intersectAt.begin(), intersectAt.end());
     return intersectAt;
 }
getShape()
const Obstacle::Coords & Obstacle::getShape () const
References coords.
Referenced by veins::ObstacleControl::add(), containsPoint(), and getIntersections().
 {
     return coords;
 }
getType()
std::string Obstacle::getType () const
References type.
 {
     return type;
 }
setShape()
void Obstacle::setShape (Coords shape)
References bboxP1, bboxP2, coords, veins::Coord::x, and veins::Coord::y.
Referenced by veins::ObstacleControl::addFromXml().
 {
     coords = shape;
     bboxP1 = Coord(1e7, 1e7);
     bboxP2 = Coord(-1e7, -1e7);
     for (Coords::const_iterator i = coords.begin(); i != coords.end(); ++i) {
         bboxP1.x = std::min(i->x, bboxP1.x);
         bboxP1.y = std::min(i->y, bboxP1.y);
         bboxP2.x = std::max(i->x, bboxP2.x);
         bboxP2.y = std::max(i->y, bboxP2.y);
     }
 }
Member Data Documentation
attenuationPerCut
double veins::Obstacle::attenuationPerCut protected
in dB.
attenuation per exterior border of obstacle
Referenced by getAttenuationPerCut().
attenuationPerMeter
double veins::Obstacle::attenuationPerMeter protected
in dB / m.
to account for attenuation caused by interior of obstacle
Referenced by getAttenuationPerMeter().
bboxP1
Coord veins::Obstacle::bboxP1 protected
Referenced by getBboxP1(), and setShape().
bboxP2
Coord veins::Obstacle::bboxP2 protected
Referenced by getBboxP2(), and setShape().
coords
Coords veins::Obstacle::coords protected
Referenced by getShape(), and setShape().
id
std::string veins::Obstacle::id protected
Referenced by getId().
type
std::string veins::Obstacle::type protected
Referenced by getType().
visualRepresentation
AnnotationManager::Annotation* veins::Obstacle::visualRepresentation
Referenced by veins::ObstacleControl::add(), and veins::ObstacleControl::erase().
The documentation for this class was generated from the following files:
Obstacle.h
Obstacle.cc