Veins: veins::BaseLayer Class Reference
veins::BaseLayer Class Reference abstract
A very simple layer template.
#include <BaseLayer.h>
Public Member Functions
BaseLayer ()
BaseLayer (unsigned stacksize)
~BaseLayer () override
void initialize (int) override
Initialization of the module and some variables.
void handleMessage (cMessage *) override
Called every time a message arrives.
void finish () override
Called when the simulation has finished.
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Static Public Attributes
static const simsignal_t catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet")
SignalID for packets.
static const simsignal_t catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg")
Signal for passed messages.
static const simsignal_t catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket")
Signal for dropped packets.
Protected Member Functions
Handle Messages
Functions to be redefined by the programmer
These are the functions provided to add own functionality to your modules. These functions are called whenever a self message or a data message from the upper or lower layer arrives respectively.
virtual void handleSelfMsg (cMessage *msg)=0
Handle self messages such as timer...
virtual void handleUpperMsg (cMessage *msg)=0
Handle messages from upper layer.
virtual void handleLowerMsg (cMessage *msg)=0
Handle messages from lower layer.
virtual void handleLowerControl (cMessage *msg)=0
Handle control messages from lower layer.
virtual void handleUpperControl (cMessage *msg)=0
Handle control messages from upper layer.
Convenience Functions
Functions for convenience - NOT to be modified
These are functions taking care of message encapsulation and message sending. Normally you should not need to alter these.
All these functions assume that YOU do all the necessary handling of control information etc. before you use them.
void sendDown (cMessage *msg)
Sends a message to the lower layer.
void sendUp (cMessage *msg)
Sends a message to the upper layer.
void sendControlUp (cMessage *msg)
Sends a control message to an upper layer.
void sendControlDown (cMessage *msg)
Sends a control message to a lower layer.
void recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage *m)
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Attributes
PassedMessage * passedMsg
The last message passed through this layer.
gate ids
int upperLayerIn
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
int upperControlIn
int upperControlOut
int lowerControlIn
int lowerControlOut
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
A very simple layer template.
This module provides basic abstractions that ease development of a network or MAC layer.
Author
Andreas Koepke
Constructor & Destructor Documentation
BaseLayer() [1/2]
veins::BaseLayer::BaseLayer () inline
         : BatteryAccess()
         , passedMsg(nullptr)
     {
     }
BaseLayer() [2/2]
veins::BaseLayer::BaseLayer (unsigned stacksize) inline
         : BatteryAccess(stacksize)
         , passedMsg(nullptr)
     {
     }
~BaseLayer()
BaseLayer::~BaseLayer () override
References passedMsg.
 {
     if (passedMsg != nullptr) {
         delete passedMsg;
     }
 }
Member Function Documentation
finish()
void BaseLayer::finish () override
Called when the simulation has finished.
 {
 }
handleLowerControl()
virtual void veins::BaseLayer::handleLowerControl (cMessage * msg) protected pure virtual
Handle control messages from lower layer.
Implemented in veins::Mac1609_4, veins::BaseMacLayer, and veins::BaseApplLayer.
Referenced by handleMessage().
handleLowerMsg()
virtual void veins::BaseLayer::handleLowerMsg (cMessage * msg) protected pure virtual
Handle messages from lower layer.
Implemented in veins::Mac1609_4, veins::BaseMacLayer, veins::BaseApplLayer, and veins::DemoBaseApplLayer.
Referenced by handleMessage().
handleMessage()
void BaseLayer::handleMessage (cMessage * msg) override
Called every time a message arrives.
The basic handle message function.
Depending on the gate a message arrives handleMessage just calls different handle*Msg functions to further process the message.
You should not make any changes in this function but implement all your functionality into the handle*Msg functions called from here.
See also
handleUpperMsg, handleLowerMsg, handleSelfMsg
References handleLowerControl(), handleLowerMsg(), handleSelfMsg(), handleUpperControl(), handleUpperMsg(), veins::PassedMessage::INCOMING, veins::PassedMessage::LOWER_CONTROL, veins::PassedMessage::LOWER_DATA, lowerControlIn, lowerLayerIn, recordPacket(), veins::PassedMessage::UPPER_CONTROL, veins::PassedMessage::UPPER_DATA, upperControlIn, and upperLayerIn.
 {
     if (msg->isSelfMessage()) {
         handleSelfMsg(msg);
     }
     else if (msg->getArrivalGateId() == upperLayerIn) {
         recordPacket(PassedMessage::INCOMING, PassedMessage::UPPER_DATA, msg);
         handleUpperMsg(msg);
     }
     else if (msg->getArrivalGateId() == upperControlIn) {
         recordPacket(PassedMessage::INCOMING, PassedMessage::UPPER_CONTROL, msg);
         handleUpperControl(msg);
     }
     else if (msg->getArrivalGateId() == lowerControlIn) {
         recordPacket(PassedMessage::INCOMING, PassedMessage::LOWER_CONTROL, msg);
         handleLowerControl(msg);
     }
     else if (msg->getArrivalGateId() == lowerLayerIn) {
         recordPacket(PassedMessage::INCOMING, PassedMessage::LOWER_DATA, msg);
         handleLowerMsg(msg);
     }
     else if (msg->getArrivalGateId() == -1) {
         /* Classes extending this class may not use all the gates, f.e.
          * BaseApplLayer has no upper gates. In this case all upper gate-
          * handles are initialized to -1. When getArrivalGateId() equals -1,
          * it would be wrong to forward the message to one of these gates,
          * as they actually don't exist, so raise an error instead.
          */
         throw cRuntimeError("No self message and no gateID?? Check configuration.");
     }
     else {
         /* msg->getArrivalGateId() should be valid, but it isn't recognized
          * here. This could signal the case that this class is extended
          * with extra gates, but handleMessage() isn't overridden to
          * check for the new gate(s).
          */
         throw cRuntimeError("Unknown gateID?? Check configuration or override handleMessage().");
     }
 }
handleSelfMsg()
virtual void veins::BaseLayer::handleSelfMsg (cMessage * msg) protected pure virtual
Handle self messages such as timer...
Implemented in veins::Mac1609_4, veins::BaseMacLayer, veins::BaseApplLayer, veins::DemoBaseApplLayer, veins::TraCIDemo11p, and veins::MyVeinsApp.
Referenced by handleMessage().
handleUpperControl()
virtual void veins::BaseLayer::handleUpperControl (cMessage * msg) protected pure virtual
Handle control messages from upper layer.
Implemented in veins::Mac1609_4, veins::BaseApplLayer, and veins::BaseMacLayer.
Referenced by handleMessage().
handleUpperMsg()
virtual void veins::BaseLayer::handleUpperMsg (cMessage * msg) protected pure virtual
Handle messages from upper layer.
This function is pure virtual here, because there is no reasonable guess what to do with it by default.
Implemented in veins::Mac1609_4, veins::BaseApplLayer, and veins::BaseMacLayer.
Referenced by handleMessage().
initialize()
void BaseLayer::initialize (int stage) override
Initialization of the module and some variables.
First we have to initialize the module from which we derived ours, in this case BaseModule.
This module takes care of the gate initialization.
References veins::PassedMessage::fromModule, veins::BaseModule::initialize(), lowerControlIn, lowerControlOut, lowerLayerIn, lowerLayerOut, passedMsg, upperControlIn, upperControlOut, upperLayerIn, and upperLayerOut.
Referenced by veins::BaseApplLayer::initialize(), and veins::BaseMacLayer::initialize().
 {
     BatteryAccess::initialize(stage);
     if (stage == 0) {
         passedMsg = nullptr;
         if (hasPar("stats") && par("stats").boolValue()) {
             passedMsg = new PassedMessage();
             if (passedMsg != nullptr) {
                 passedMsg->fromModule = getId();
             }
         }
         upperLayerIn = findGate("upperLayerIn");
         upperLayerOut = findGate("upperLayerOut");
         lowerLayerIn = findGate("lowerLayerIn");
         lowerLayerOut = findGate("lowerLayerOut");
         upperControlIn = findGate("upperControlIn");
         upperControlOut = findGate("upperControlOut");
         lowerControlIn = findGate("lowerControlIn");
         lowerControlOut = findGate("lowerControlOut");
     }
 }
recordPacket()
void BaseLayer::recordPacket (PassedMessage::direction_t dir, PassedMessage::gates_t gate, const cMessage * m) protected
References catPassedMsgSignal, veins::PassedMessage::direction, veins::PassedMessage::gateType, veins::PassedMessage::kind, veins::PassedMessage::name, and passedMsg.
Referenced by handleMessage(), sendControlDown(), sendControlUp(), veins::BaseApplLayer::sendDelayedDown(), sendDown(), and sendUp().
 {
     if (passedMsg == nullptr) return;
     passedMsg->direction = dir;
     passedMsg->gateType = gate;
     passedMsg->kind = msg->getKind();
     passedMsg->name = msg->getName();
     emit(catPassedMsgSignal, passedMsg);
 }
sendControlDown()
void BaseLayer::sendControlDown (cMessage * msg) protected
Sends a control message to a lower layer.
References veins::PassedMessage::LOWER_CONTROL, lowerControlOut, veins::PassedMessage::OUTGOING, and recordPacket().
 {
     recordPacket(PassedMessage::OUTGOING, PassedMessage::LOWER_CONTROL, msg);
     if (gate(lowerControlOut)->isPathOK())
         send(msg, lowerControlOut);
     else {
         EV << "BaseLayer: lowerControlOut is not connected; dropping message" << std::endl;
         delete msg;
     }
 }
sendControlUp()
void BaseLayer::sendControlUp (cMessage * msg) protected
Sends a control message to an upper layer.
References veins::PassedMessage::OUTGOING, recordPacket(), veins::PassedMessage::UPPER_CONTROL, and upperControlOut.
Referenced by veins::BaseMacLayer::handleLowerControl().
 {
     recordPacket(PassedMessage::OUTGOING, PassedMessage::UPPER_CONTROL, msg);
     if (gate(upperControlOut)->isPathOK())
         send(msg, upperControlOut);
     else {
         EV << "BaseLayer: upperControlOut is not connected; dropping message" << std::endl;
         delete msg;
     }
 }
sendDown()
void BaseLayer::sendDown (cMessage * msg) protected
Sends a message to the lower layer.
Short hand for send(msg, lowerLayerOut);
You have to take care of encapsulation We recommend that you use a pair of functions called encapsMsg/decapsMsg.
References veins::PassedMessage::LOWER_DATA, lowerLayerOut, veins::PassedMessage::OUTGOING, and recordPacket().
Referenced by veins::BaseMacLayer::handleUpperMsg(), and veins::DemoBaseApplLayer::sendDown().
 {
     recordPacket(PassedMessage::OUTGOING, PassedMessage::LOWER_DATA, msg);
     send(msg, lowerLayerOut);
 }
sendUp()
void BaseLayer::sendUp (cMessage * msg) protected
Sends a message to the upper layer.
Short hand for send(msg, upperLayerOut); You have to take care of decapsulation and deletion of superflous frames. We recommend that you use a pair of functions decapsMsg/encapsMsg.
References veins::PassedMessage::OUTGOING, recordPacket(), veins::PassedMessage::UPPER_DATA, and upperLayerOut.
Referenced by veins::Mac1609_4::handleBroadcast(), veins::BaseMacLayer::handleLowerMsg(), and veins::Mac1609_4::handleUnicast().
 {
     recordPacket(PassedMessage::OUTGOING, PassedMessage::UPPER_DATA, msg);
     send(msg, upperLayerOut);
 }
Member Data Documentation
catDroppedPacketSignal
const simsignal_t BaseLayer::catDroppedPacketSignal = registerSignal("org_car2x_veins_modules_utility_droppedpacket") static
Signal for dropped packets.
catPacketSignal
const simsignal_t BaseLayer::catPacketSignal = registerSignal("org_car2x_veins_modules_utility_packet") static
SignalID for packets.
catPassedMsgSignal
const simsignal_t BaseLayer::catPassedMsgSignal = registerSignal("org_car2x_veins_base_utils_passedmsg") static
Signal for passed messages.
Referenced by recordPacket().
lowerControlIn
int veins::BaseLayer::lowerControlIn protected
Referenced by handleMessage(), and initialize().
lowerControlOut
int veins::BaseLayer::lowerControlOut protected
Referenced by initialize(), and sendControlDown().
lowerLayerIn
int veins::BaseLayer::lowerLayerIn protected
Referenced by handleMessage(), and initialize().
lowerLayerOut
int veins::BaseLayer::lowerLayerOut protected
Referenced by initialize(), veins::BaseApplLayer::sendDelayedDown(), sendDown(), and veins::Mac1609_4::sendFrame().
passedMsg
PassedMessage* veins::BaseLayer::passedMsg protected
The last message passed through this layer.
This variable will be only not NULL if we are in statistic recording mode.
Referenced by initialize(), recordPacket(), and ~BaseLayer().
upperControlIn
int veins::BaseLayer::upperControlIn protected
Referenced by handleMessage(), and initialize().
upperControlOut
int veins::BaseLayer::upperControlOut protected
Referenced by initialize(), and sendControlUp().
upperLayerIn
int veins::BaseLayer::upperLayerIn protected
Referenced by handleMessage(), and initialize().
upperLayerOut
int veins::BaseLayer::upperLayerOut protected
Referenced by initialize(), and sendUp().
The documentation for this class was generated from the following files:
BaseLayer.h
BaseLayer.cc