Veins: veins::TraCIRegionOfInterest Class Reference
veins::TraCIRegionOfInterest Class Reference
Can return whether a given position lies within the simulation's region of interest.
#include <TraCIRegionOfInterest.h>
Public Types
enum ConstraintResult { NONE, SATISFY, BREAK }
Public Member Functions
TraCIRegionOfInterest ()
void addRoads (const std::string &roads)
Add roads to contraints.
void addRectangles (const std::string &rects)
Add rectangles to constraints.
void clear ()
Remove all constraints.
bool onAnyRectangle (const TraCICoord &pos) const
Check if position lies on any ROI rectangle.
bool partOfRoads (const std::string &road_id) const
Check if a given road is part of interest roads.
bool hasConstraints () const
Check if any constraints are defined.
const std::list< std::pair< TraCICoord, TraCICoord > > & getRectangles () const
Private Attributes
std::set< std::string > roiRoads
which roads (e.g.
std::list< std::pair< TraCICoord, TraCICoord > > roiRects
which rectangles (e.g.
Detailed Description
Can return whether a given position lies within the simulation's region of interest.
Modules are destroyed and re-created as managed vehicles leave and re-enter the ROI
Member Enumeration Documentation
ConstraintResult
enum veins::TraCIRegionOfInterest::ConstraintResult
Enumerator
NONE
SATISFY
BREAK
{
         NONE, // when no constraints exist
         SATISFY,
         BREAK
     };
Constructor & Destructor Documentation
TraCIRegionOfInterest()
veins::TraCIRegionOfInterest::TraCIRegionOfInterest ()
 {
 }
Member Function Documentation
addRectangles()
void veins::TraCIRegionOfInterest::addRectangles (const std::string & rects)
Add rectangles to constraints.
Parameters
rects given as x1,y1-x2,y2 pairs separated by spaces
References roiRects.
Referenced by veins::TraCIScenarioManager::initialize().
 {
     std::istringstream rectsStream(rects);
     std::string rect;
     while (std::getline(rectsStream, rect, ' ')) {
         std::istringstream rectStream(rect);
         double x1;
         rectStream >> x1;
         char c1;
         rectStream >> c1;
         double y1;
         rectStream >> y1;
         char c2;
         rectStream >> c2;
         double x2;
         rectStream >> x2;
         char c3;
         rectStream >> c3;
         double y2;
         rectStream >> y2;
         if (rectStream.good()) {
             throw cRuntimeError("Parsing ROI rectangle failed");
         }
         roiRects.push_back(std::pair<TraCICoord, TraCICoord>(TraCICoord(x1, y1), TraCICoord(x2, y2)));
     }
 }
addRoads()
void veins::TraCIRegionOfInterest::addRoads (const std::string & roads)
Add roads to contraints.
Parameters
roads given as road ids separated by spaces
References roiRoads.
Referenced by veins::TraCIScenarioManager::initialize().
 {
     std::istringstream roadsStream(roads);
     std::string road;
     while (std::getline(roadsStream, road, ' ')) {
         roiRoads.insert(road);
     }
 }
clear()
void veins::TraCIRegionOfInterest::clear ()
Remove all constraints.
References roiRects, and roiRoads.
Referenced by veins::TraCIScenarioManager::initialize().
 {
     roiRoads.clear();
     roiRects.clear();
 }
getRectangles()
const std::list< std::pair< TraCICoord, TraCICoord > > & veins::TraCIRegionOfInterest::getRectangles () const
References roiRects.
Referenced by veins::TraCIScenarioManager::init_traci().
 {
     return roiRects;
 }
hasConstraints()
bool veins::TraCIRegionOfInterest::hasConstraints () const
Check if any constraints are defined.
Returns
true if constraints exist
References roiRects, and roiRoads.
Referenced by veins::TraCIScenarioManager::processVehicleSubscription().
 {
     return !roiRoads.empty() || !roiRects.empty();
 }
onAnyRectangle()
bool veins::TraCIRegionOfInterest::onAnyRectangle (const TraCICoord & pos) const
Check if position lies on any ROI rectangle.
Parameters
pos Position to check
Returns
true if on any rectangle
References roiRects, veins::TraCICoord::x, and veins::TraCICoord::y.
Referenced by veins::TraCIScenarioManager::processVehicleSubscription().
 {
     struct RectangleTest {
         RectangleTest(const TraCICoord& position_)
             : position(position_)
         {
         }
         bool operator()(const std::pair<TraCICoord, TraCICoord>& rect) const
         {
             return (position.x >= rect.first.x && position.y >= rect.first.y) && (position.x <= rect.second.x && position.y <= rect.second.y);
         }
         const TraCICoord& position;
     };
     std::list<std::pair<TraCICoord, TraCICoord>>::const_iterator found = std::find_if(roiRects.begin(), roiRects.end(), RectangleTest(position));
     return found != roiRects.end();
 }
partOfRoads()
bool veins::TraCIRegionOfInterest::partOfRoads (const std::string & road_id) const
Check if a given road is part of interest roads.
Parameters
road_id
Returns
true if part of ROI roads
References roiRoads.
Referenced by veins::TraCIScenarioManager::processVehicleSubscription().
 {
     return roiRoads.count(road) > 0;
 }
Member Data Documentation
roiRects
std::list<std::pair<TraCICoord, TraCICoord> > veins::TraCIRegionOfInterest::roiRects private
which rectangles (e.g.
"0,0-10,10 20,20-30,30) are considered to consitute the region of interest, if not empty
Referenced by addRectangles(), clear(), getRectangles(), hasConstraints(), and onAnyRectangle().
roiRoads
std::set<std::string> veins::TraCIRegionOfInterest::roiRoads private
which roads (e.g.
"hwy1 hwy2") are considered to consitute the region of interest, if not empty
Referenced by addRoads(), clear(), hasConstraints(), and partOfRoads().
The documentation for this class was generated from the following files:
TraCIRegionOfInterest.h
TraCIRegionOfInterest.cc