Veins: veins::Signal Class Reference
veins::Signal Class Reference
A Signal represents the power measured on a channel.
#include <Signal.h>
Public Member Functions
Signal ()=default
Signal (const Signal &other)
Copy another Signal.
Signal (Spectrum spec)
Create a Signal with zero power and without timing information.
Signal (Spectrum spec, simtime_t start, simtime_t duration)
Create a Signal with zero power for a time interval.
~Signal ()=default
const Spectrum & getSpectrum () const
Get the Spectrum this Signal is defined on.
Signal & operator= (const double value)
Assign a constant power level to all defined frequencies.
Signal & operator= (const Signal &other)
Create a copy of another signal.
Element access
double & at (size_t index)
Get the power in milliwatt for the given frequency index.
const double & at (size_t index) const
Get the power in milliwatt for the given frequency index.
double & atFrequency (double freq)
Get the power in milliwatt for the given frequency.
const double & atFrequency (double freq) const
Get the power in milliwatt for the given frequency.
double * getValues ()
Access the underlying power values directly.
size_t getNumValues () const
Returns the number of power values stored in this signal.
double getMax () const
Return the maximum power level of any frequency.
Element access on the defined data interval
The data interval is a subrange of frequencies, which are used to transmit the actual data.
This range is relevant for computing signal power since power on other frequencies does not influence the encoded data.
double & dataAt (size_t index)
Get the power in milliwatt for the given data frequency index.
const double & dataAt (size_t index) const
Get the power in milliwatt for the given data frequency index.
size_t getDataStart () const
Get the absolute frequency index of the first data frequency.
size_t getDataEnd () const
Get the absolute frequency index of first past-the-end data frequency.
double * getDataValues ()
Access the underlying data range power levels directly.
size_t getNumDataValues () const
The number of values in the data frequency subrange.
size_t getDataOffset () const
Get the offset of the data frequency range in the absolute frequency range.
double getDataMin () const
Minimum power level in milliwatt in the data frequency range.
double getDataMax () const
Maximum power level in milliwatt in the data frequency range.
void setDataStart (size_t index)
Change the data frequency range's start.
void setDataEnd (size_t index)
Change the data frequency range's end.
void setDataNumValues (size_t num)
Change the data frequency range's length.
Center frequency access
size_t getCenterFrequencyIndex () const
Get the center frequency's index.
double getAtCenterFrequency () const
Get the center frequency's power level in milliwatt.
void setCenterFrequencyIndex (size_t index)
Set the center frequency position.
bool greaterAtCenterFrequency (double threshold)
Predicate testing whether the power level at the center frequency exceeds a threshold.
bool smallerAtCenterFrequency (double threshold)
Predicate testing whether the power level at the center frequency does not exceed a threshold.
Analogue models
uint16_t getNumAnalogueModelsApplied () const
Get the number of AnalogueModels that have already been applied to the Signal.
AnalogueModelList * getAnalogueModelList () const
Get the AnalogueModels associated with this Signal.
void setAnalogueModelList (AnalogueModelList *list)
Set the AnalogueModels associated with this Signal.
void applyAnalogueModel (uint16_t index)
Apply a specific AnalogueModel.
void applyAllAnalogueModels ()
Apply all AnalogueModels.
Sender and receiver POAs
POA getSenderPoa () const
Get this signal's sender POA.
POA getReceiverPoa () const
Get this signal's receiver POA.
void setSenderPoa (const POA &poa)
Set this signal's sender POA.
void setReceiverPoa (const POA &poa)
Set this signal's receiver POA.
simtime_t_cref getSendingStart () const
Timing.
simtime_t getSendingEnd () const
Get the point in time at which the signal ends.
simtime_t getReceptionStart () const
Get the point in time at which the signal reception starts.
simtime_t getReceptionEnd () const
Get the point in time at which the signal reception ends.
simtime_t_cref getDuration () const
Get the duration.
simtime_t_cref getPropagationDelay () const
Get the propagation delay.
bool hasTiming () const
Predicate which indicates presence of timing information.
void setPropagationDelay (simtime_t_cref delay)
Set the propagation delay.
void setTiming (simtime_t start, simtime_t duration)
Set the signal's timing information.
Arithmetic operators
Signal & operator+= (const Signal &other)
Increment the power levels by another signal's power levels.
Signal & operator+= (const double value)
Increment the power levels by a constant.
Signal & operator-= (const Signal &other)
Decrement the power levels by another signal's power levels.
Signal & operator-= (const double value)
Decrement the power levels by a constant.
Signal & operator*= (const Signal &other)
Multiply the power levels by another signal's power levels.
Signal & operator*= (const double value)
Multiply the power levels by a constant.
Signal & operator/= (const Signal &other)
Divide the power levels by another signal's power levels.
Signal & operator/= (const double value)
Divide the power levels by a constant.
Private Member Functions
double getMinInRange (size_t freqIndexLow, size_t freqIndexHigh) const
double getMaxInRange (size_t freqIndexLow, size_t freqIndexHigh) const
Private Attributes
Spectrum spectrum
std::vector< double > values
size_t numDataValues = 0
size_t dataOffset = 0
size_t centerFrequencyIndex = 0
bool timingUsed = false
simtime_t sendingStart = 0
The start of the signal transmission at the sender module.
simtime_t duration = 0
The duration of the signal transmission.
simtime_t propagationDelay = 0
The propagation delay of the transmission.
AnalogueModelList * analogueModelList = nullptr
uint16_t numAnalogueModelsApplied = 0
POA senderPoa
POA receiverPoa
Friends
std::ostream & operator<< (std::ostream &os, const Signal &s)
Convert a signal to a human readable representation.
simtime_t calculateStart (const Signal &lhs, const Signal &rhs)
Calculate the common start of two signals, i.e.
simtime_t calculateDuration (const Signal &lhs, const Signal &rhs)
Calculate the combined duration of two signals.
Detailed Description
A Signal represents the power measured on a channel.
The Signal is parameterized by the frequency range, time interval and spatial posititon. The signal power is stored in milliwatt. Signals can be combined arithmetically to, e.g., compute interference introduced by several overlapping signals.
See also
SignalUtils
Spectrum
Constructor & Destructor Documentation
Signal() [1/4]
veins::Signal::Signal () default
Signal() [2/4]
veins::Signal::Signal (const Signal & other)
Copy another Signal.
     : spectrum(other.spectrum)
     , values(other.values)
     , numDataValues(other.numDataValues)
     , dataOffset(other.dataOffset)
     , centerFrequencyIndex(other.centerFrequencyIndex)
     , timingUsed(other.timingUsed)
     , sendingStart(other.sendingStart)
     , duration(other.duration)
     , propagationDelay(other.propagationDelay)
     , analogueModelList(other.analogueModelList)
     , numAnalogueModelsApplied(other.numAnalogueModelsApplied)
     , senderPoa(other.senderPoa)
     , receiverPoa(other.receiverPoa)
 {
 }
Signal() [3/4]
veins::Signal::Signal (Spectrum spec) explicit
Create a Signal with zero power and without timing information.
     : spectrum(spec)
     , values(spectrum.getNumFreqs(), 0)
 {
 }
Signal() [4/4]
veins::Signal::Signal (Spectrum spec, simtime_t start, simtime_t duration)
Create a Signal with zero power for a time interval.
     : spectrum(spec)
     , values(spectrum.getNumFreqs(), 0)
     , timingUsed(true)
     , sendingStart(start)
     , duration(dur)
 {
 }
~Signal()
veins::Signal::~Signal () default
Member Function Documentation
applyAllAnalogueModels()
void veins::Signal::applyAllAnalogueModels ()
Apply all AnalogueModels.
The models are applied in the same order of the AnalogueModel list.
See also
getAnalogueModelList()
AnalogueModel::filterSignal()
References analogueModelList, and numAnalogueModelsApplied.
 {
     uint16_t maxAnalogueModels = analogueModelList->size();
     while (numAnalogueModelsApplied < maxAnalogueModels) {
         (*analogueModelList)[numAnalogueModelsApplied]->filterSignal(this);
         numAnalogueModelsApplied++;
     }
 }
applyAnalogueModel()
void veins::Signal::applyAnalogueModel (uint16_t index)
Apply a specific AnalogueModel.
Parameters
index the index in the analogue model list of the model to be applied
See also
getAnalogueModelList()
AnalogueModel::filterSignal()
References analogueModelList, and numAnalogueModelsApplied.
 {
     uint16_t maxAnalogueModels = analogueModelList->size();
     if (index >= maxAnalogueModels || index < numAnalogueModelsApplied) return;
     (*analogueModelList)[index]->filterSignal(this);
     numAnalogueModelsApplied++;
 }
at() [1/2]
double & veins::Signal::at (size_t index)
Get the power in milliwatt for the given frequency index.
Parameters
index index of the power level to return
Returns
a reference to the power level
References values.
Referenced by veins::PhyLayer80211p::attachSignal(), veins::VehicleObstacleShadowing::filterSignal(), veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), veins::SignalUtils::getMinSINR(), and veins::VehicleObstacleControl::getVehicleAttenuationSingle().
 {
     return values.at(index);
 }
at() [2/2]
const double & veins::Signal::at (size_t index) const
Get the power in milliwatt for the given frequency index.
Parameters
index index of the power level to return
Returns
a reference to the power level
References values.
 {
     return values.at(index);
 }
atFrequency() [1/2]
double & veins::Signal::atFrequency (double freq)
Get the power in milliwatt for the given frequency.
Parameters
freq frequency of the power level to return
Returns
a reference to the power level
References veins::Spectrum::indexOf(), spectrum, and values.
 {
     size_t index = spectrum.indexOf(frequency);
     return values.at(index);
 }
atFrequency() [2/2]
const double & veins::Signal::atFrequency (double freq) const
Get the power in milliwatt for the given frequency.
Parameters
freq frequency of the power level to return
Returns
a reference to the power level
References veins::Spectrum::indexOf(), spectrum, and values.
 {
     size_t index = spectrum.indexOf(frequency);
     return values.at(index);
 }
dataAt() [1/2]
double & veins::Signal::dataAt (size_t index)
Get the power in milliwatt for the given data frequency index.
Parameters
index index of the power level to return
Returns
a reference to the power level
References dataOffset, and values.
 {
     return values.at(dataOffset + index);
 }
dataAt() [2/2]
const double & veins::Signal::dataAt (size_t index) const
Get the power in milliwatt for the given data frequency index.
Parameters
index index of the power level to return
Returns
a reference to the power level
References dataOffset, and values.
 {
     return values.at(dataOffset + index);
 }
getAnalogueModelList()
AnalogueModelList * veins::Signal::getAnalogueModelList () const
Get the AnalogueModels associated with this Signal.
References analogueModelList.
Referenced by veins::SignalUtils::isChannelPowerBelowThreshold(), and operator=().
 {
     return analogueModelList;
 }
getAtCenterFrequency()
double veins::Signal::getAtCenterFrequency () const
Get the center frequency's power level in milliwatt.
References centerFrequencyIndex, and values.
 {
     return values[centerFrequencyIndex];
 }
getCenterFrequencyIndex()
size_t veins::Signal::getCenterFrequencyIndex () const
Get the center frequency's index.
References centerFrequencyIndex.
Referenced by operator=().
 {
     return centerFrequencyIndex;
 }
getDataEnd()
size_t veins::Signal::getDataEnd () const
Get the absolute frequency index of first past-the-end data frequency.
References dataOffset, and numDataValues.
Referenced by veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), and veins::SignalUtils::getMinSINR().
 {
     return dataOffset + numDataValues;
 }
getDataMax()
double veins::Signal::getDataMax () const
Maximum power level in milliwatt in the data frequency range.
References dataOffset, getMaxInRange(), and numDataValues.
 {
     return getMaxInRange(dataOffset, dataOffset + numDataValues);
 }
getDataMin()
double veins::Signal::getDataMin () const
Minimum power level in milliwatt in the data frequency range.
References dataOffset, getMinInRange(), and numDataValues.
 {
     return getMinInRange(dataOffset, dataOffset + numDataValues);
 }
getDataOffset()
size_t veins::Signal::getDataOffset () const
Get the offset of the data frequency range in the absolute frequency range.
Synonym for getDataStart()
References dataOffset.
Referenced by operator=().
 {
     return dataOffset;
 }
getDataStart()
size_t veins::Signal::getDataStart () const
Get the absolute frequency index of the first data frequency.
References dataOffset.
Referenced by veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), and veins::SignalUtils::getMinSINR().
 {
     return dataOffset;
 }
getDataValues()
double * veins::Signal::getDataValues ()
Access the underlying data range power levels directly.
See also
getNumDataValues()
References dataOffset, and values.
 {
     return values.data() + dataOffset;
 }
getDuration()
simtime_t_cref veins::Signal::getDuration () const
Get the duration.
Only valid if hasTiming() returns true.
References duration.
Referenced by veins::PhyLayer80211p::attachSignal(), veins::BasePhyLayer::handleAirFrameReceiving(), and operator=().
 {
     return duration;
 }
getMax()
double veins::Signal::getMax () const
Return the maximum power level of any frequency.
References getMaxInRange(), and values.
Referenced by veins::NakagamiFading::filterSignal(), and veins::BaseDecider::processNewSignal().
 {
     return getMaxInRange(0, values.size());
 }
getMaxInRange()
double veins::Signal::getMaxInRange (size_t freqIndexLow, size_t freqIndexHigh) const private
References values.
Referenced by getDataMax(), and getMax().
 {
     return *(std::max_element(values.begin() + freqIndexLow, values.begin() + freqIndexHigh));
 }
getMinInRange()
double veins::Signal::getMinInRange (size_t freqIndexLow, size_t freqIndexHigh) const private
References values.
Referenced by getDataMin().
 {
     return *(std::min_element(values.begin() + freqIndexLow, values.begin() + freqIndexHigh));
 }
getNumAnalogueModelsApplied()
uint16_t veins::Signal::getNumAnalogueModelsApplied () const
Get the number of AnalogueModels that have already been applied to the Signal.
References numAnalogueModelsApplied.
Referenced by operator=().
 {
     return numAnalogueModelsApplied;
 }
getNumDataValues()
size_t veins::Signal::getNumDataValues () const
The number of values in the data frequency subrange.
References numDataValues.
Referenced by operator=().
 {
     return numDataValues;
 }
getNumValues()
size_t veins::Signal::getNumValues () const
Returns the number of power values stored in this signal.
Corresponds to the associated Spectrum's number of defined frequencies.
References values.
Referenced by veins::TwoRayInterferenceModel::filterSignal(), veins::SimplePathlossModel::filterSignal(), and veins::VehicleObstacleControl::getVehicleAttenuationSingle().
 {
     return values.size();
 }
getPropagationDelay()
simtime_t_cref veins::Signal::getPropagationDelay () const
Get the propagation delay.
The propagation delay is the time taken for the signal to travel from sender to receiver with the speed of light. Only valid if hasTiming() returns true.
Note
this value is explicly set and not necessarily computed based on the sender and receiver positions.
References propagationDelay.
Referenced by operator=().
 {
     return propagationDelay;
 }
getReceiverPoa()
POA veins::Signal::getReceiverPoa () const
Get this signal's receiver POA.
References receiverPoa.
Referenced by veins::PERModel::filterSignal(), veins::TwoRayInterferenceModel::filterSignal(), veins::NakagamiFading::filterSignal(), veins::VehicleObstacleShadowing::filterSignal(), veins::SimpleObstacleShadowing::filterSignal(), veins::SimplePathlossModel::filterSignal(), veins::BreakpointPathlossModel::filterSignal(), and operator=().
 {
     return receiverPoa;
 }
getReceptionEnd()
simtime_t veins::Signal::getReceptionEnd () const
Get the point in time at which the signal reception ends.
This corresponds to the singal's end time, but is shifted by its propagation delay. Only valid if hasTiming() returns true.
See also
getPropagationDelay()
References duration, propagationDelay, and sendingStart.
Referenced by veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), veins::SignalUtils::isChannelPowerBelowThreshold(), veins::operator<<(), and veins::BaseDecider::processNewSignal().
 {
     return sendingStart + propagationDelay + duration;
 }
getReceptionStart()
simtime_t veins::Signal::getReceptionStart () const
Get the point in time at which the signal reception starts.
This corresponds to the singal's start time, but is shifted by its propagation delay. Only valid if hasTiming() returns true.
See also
getPropagationDelay()
References propagationDelay, and sendingStart.
Referenced by veins::Decider80211p::checkIfSignalOk(), veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), veins::BasePhyLayer::handleAirFrameReceiving(), veins::BasePhyLayer::handleAirFrameStartReceive(), veins::SignalUtils::isChannelPowerBelowThreshold(), and veins::operator<<().
 {
     return sendingStart + propagationDelay;
 }
getSenderPoa()
POA veins::Signal::getSenderPoa () const
Get this signal's sender POA.
References senderPoa.
Referenced by veins::PERModel::filterSignal(), veins::TwoRayInterferenceModel::filterSignal(), veins::NakagamiFading::filterSignal(), veins::VehicleObstacleShadowing::filterSignal(), veins::SimpleObstacleShadowing::filterSignal(), veins::SimplePathlossModel::filterSignal(), veins::BreakpointPathlossModel::filterSignal(), and operator=().
 {
     return senderPoa;
 }
getSendingEnd()
simtime_t veins::Signal::getSendingEnd () const
Get the point in time at which the signal ends.
Only valid if hasTiming() returns true.
References duration, and sendingStart.
 {
     return sendingStart + duration;
 }
getSendingStart()
simtime_t_cref veins::Signal::getSendingStart () const
Timing.
Get the point in time at which the signal starts.
Only valid if hasTiming() returns true.
References sendingStart.
Referenced by veins::VehicleObstacleControl::getPotentialObstacles(), veins::BasePhyLayer::handleAirFrameStartReceive(), and operator=().
 {
     return sendingStart;
 }
getSpectrum()
const Spectrum & veins::Signal::getSpectrum () const
Get the Spectrum this Signal is defined on.
References spectrum.
Referenced by veins::TwoRayInterferenceModel::filterSignal(), veins::VehicleObstacleShadowing::filterSignal(), veins::SimplePathlossModel::filterSignal(), veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), veins::SignalUtils::getMinSINR(), veins::VehicleObstacleControl::getVehicleAttenuationDZ(), veins::VehicleObstacleControl::getVehicleAttenuationSingle(), operator*=(), operator+=(), operator-=(), veins::operator/(), operator/=(), and operator=().
 {
     return spectrum;
 }
getValues()
double * veins::Signal::getValues ()
Access the underlying power values directly.
See also
getNumValues()
Returns
A pointer to the individual values. The amount of valid entries is defined by getNumValues.
References values.
 {
     return values.data();
 }
greaterAtCenterFrequency()
bool veins::Signal::greaterAtCenterFrequency (double threshold)
Predicate testing whether the power level at the center frequency exceeds a threshold.
Parameters
threshold the threshold to test
References analogueModelList, centerFrequencyIndex, numAnalogueModelsApplied, and values.
 {
     if (values[centerFrequencyIndex] < threshold) return false;
     uint16_t maxAnalogueModels = analogueModelList->size();
     while (numAnalogueModelsApplied < maxAnalogueModels) {
         // Apply filter here
         (*analogueModelList)[numAnalogueModelsApplied]->filterSignal(this);
         numAnalogueModelsApplied++;
         if (values[centerFrequencyIndex] < threshold) return false;
     }
     return true;
 }
hasTiming()
bool veins::Signal::hasTiming () const
Predicate which indicates presence of timing information.
References timingUsed.
Referenced by operator=().
 {
     return timingUsed;
 }
operator*=() [1/2]
Signal & veins::Signal::operator*= (const Signal & other)
Multiply the power levels by another signal's power levels.
Parameters
other the other signal
References duration, getSpectrum(), sendingStart, timingUsed, and values.
 {
     ASSERT(this->getSpectrum() == other.getSpectrum());
     ASSERT(!(this->timingUsed && other.timingUsed) || (this->sendingStart == other.sendingStart && this->duration == other.duration));
     std::transform(values.begin(), values.end(), other.values.begin(), values.begin(), std::multiplies<double>());
     return *this;
 }
operator*=() [2/2]
Signal & veins::Signal::operator*= (const double value)
Multiply the power levels by a constant.
Parameters
value power level to multiply by in milliwatt
References values.
 {
     std::transform(values.begin(), values.end(), values.begin(), [value](double other) { return other * value; });
     return *this;
 }
operator+=() [1/2]
Signal & veins::Signal::operator+= (const Signal & other)
Increment the power levels by another signal's power levels.
Parameters
other the other signal
References duration, getSpectrum(), sendingStart, timingUsed, and values.
 {
     ASSERT(this->getSpectrum() == other.getSpectrum());
     ASSERT(!(this->timingUsed && other.timingUsed) || (this->sendingStart == other.sendingStart && this->duration == other.duration));
     std::transform(values.begin(), values.end(), other.values.begin(), values.begin(), std::plus<double>());
     return *this;
 }
operator+=() [2/2]
Signal & veins::Signal::operator+= (const double value)
Increment the power levels by a constant.
Parameters
value power level to add in milliwatt
References values.
 {
     std::transform(values.begin(), values.end(), values.begin(), [value](double other) { return other + value; });
     return *this;
 }
operator-=() [1/2]
Signal & veins::Signal::operator-= (const Signal & other)
Decrement the power levels by another signal's power levels.
Parameters
other the other signal
References duration, getSpectrum(), sendingStart, timingUsed, and values.
 {
     ASSERT(this->getSpectrum() == other.getSpectrum());
     ASSERT(!(this->timingUsed && other.timingUsed) || (this->sendingStart == other.sendingStart && this->duration == other.duration));
     std::transform(values.begin(), values.end(), other.values.begin(), values.begin(), std::minus<double>());
     return *this;
 }
operator-=() [2/2]
Signal & veins::Signal::operator-= (const double value)
Decrement the power levels by a constant.
Parameters
value power level to substract in milliwatt
References values.
 {
     std::transform(values.begin(), values.end(), values.begin(), [value](double other) { return other - value; });
     return *this;
 }
operator/=() [1/2]
Signal & veins::Signal::operator/= (const Signal & other)
Divide the power levels by another signal's power levels.
Parameters
other the other signal
References duration, getSpectrum(), sendingStart, timingUsed, and values.
 {
     ASSERT(this->getSpectrum() == other.getSpectrum());
     ASSERT(!(this->timingUsed && other.timingUsed) || (this->sendingStart == other.sendingStart && this->duration == other.duration));
     std::transform(values.begin(), values.end(), other.values.begin(), values.begin(), std::divides<double>());
     return *this;
 }
operator/=() [2/2]
Signal & veins::Signal::operator/= (const double value)
Divide the power levels by a constant.
Parameters
value power level to divide by in milliwatt
References values.
 {
     std::transform(values.begin(), values.end(), values.begin(), [value](double other) { return other / value; });
     return *this;
 }
operator=() [1/2]
Signal & veins::Signal::operator= (const double value)
Assign a constant power level to all defined frequencies.
Parameters
value the power level in milliwatt
References values.
 {
     std::fill(values.begin(), values.end(), value);
     return *this;
 }
operator=() [2/2]
Signal & veins::Signal::operator= (const Signal & other)
Create a copy of another signal.
Parameters
other the other signal
References analogueModelList, centerFrequencyIndex, dataOffset, duration, getAnalogueModelList(), getCenterFrequencyIndex(), getDataOffset(), getDuration(), getNumAnalogueModelsApplied(), getNumDataValues(), getPropagationDelay(), getReceiverPoa(), getSenderPoa(), getSendingStart(), getSpectrum(), hasTiming(), numAnalogueModelsApplied, numDataValues, propagationDelay, receiverPoa, senderPoa, sendingStart, spectrum, timingUsed, and values.
 {
     if (this == &other) return *this;
     spectrum = other.getSpectrum();
     dataOffset = other.getDataOffset();
     centerFrequencyIndex = other.getCenterFrequencyIndex();
     numDataValues = other.getNumDataValues();
     values = other.values;
     analogueModelList = other.getAnalogueModelList();
     numAnalogueModelsApplied = other.getNumAnalogueModelsApplied();
     senderPoa = other.getSenderPoa();
     receiverPoa = other.getReceiverPoa();
     timingUsed = other.hasTiming();
     sendingStart = other.getSendingStart();
     duration = other.getDuration();
     propagationDelay = other.getPropagationDelay();
     return *this;
 }
setAnalogueModelList()
void veins::Signal::setAnalogueModelList (AnalogueModelList * list)
Set the AnalogueModels associated with this Signal.
Parameters
list the new list of AnalogueModels
References analogueModelList.
Referenced by veins::BasePhyLayer::filterSignal().
 {
     analogueModelList = list;
 }
setCenterFrequencyIndex()
void veins::Signal::setCenterFrequencyIndex (size_t index)
Set the center frequency position.
Parameters
index the new center frequency's absolute frequency index
References centerFrequencyIndex.
Referenced by veins::PhyLayer80211p::attachSignal().
 {
     centerFrequencyIndex = index;
 }
setDataEnd()
void veins::Signal::setDataEnd (size_t index)
Change the data frequency range's end.
This implicitly changes the number of values in the data frequncey range.
Parameters
index new data frequency range's absolute end index
References dataOffset, and numDataValues.
Referenced by veins::PhyLayer80211p::attachSignal().
 {
     numDataValues = 1 + index - dataOffset;
 }
setDataNumValues()
void veins::Signal::setDataNumValues (size_t num)
Change the data frequency range's length.
This implicitly changes the data frequncey range's end.
Parameters
num new data frequency range's length
References numDataValues.
 {
     numDataValues = num;
 }
setDataStart()
void veins::Signal::setDataStart (size_t index)
Change the data frequency range's start.
Parameters
index new data frequency range's absolute start index
References dataOffset.
Referenced by veins::PhyLayer80211p::attachSignal().
 {
     dataOffset = index;
 }
setPropagationDelay()
void veins::Signal::setPropagationDelay (simtime_t_cref delay)
Set the propagation delay.
Parameters
delay new propagation delay
References propagationDelay.
Referenced by veins::BasePhyLayer::handleAirFrameStartReceive().
 {
     propagationDelay = delay;
 }
setReceiverPoa()
void veins::Signal::setReceiverPoa (const POA & poa)
Set this signal's receiver POA.
Parameters
poa the new receiver POA
References receiverPoa.
Referenced by veins::BasePhyLayer::filterSignal().
 {
     receiverPoa = poa;
 }
setSenderPoa()
void veins::Signal::setSenderPoa (const POA & poa)
Set this signal's sender POA.
Parameters
poa the new sender POA
References senderPoa.
Referenced by veins::BasePhyLayer::filterSignal().
 {
     senderPoa = poa;
 }
setTiming()
void veins::Signal::setTiming (simtime_t start, simtime_t duration)
Set the signal's timing information.
Parameters
start the new start time
duration the new duration
References duration, sendingStart, and timingUsed.
 {
     sendingStart = start;
     duration = dur;
     timingUsed = true;
 }
smallerAtCenterFrequency()
bool veins::Signal::smallerAtCenterFrequency (double threshold)
Predicate testing whether the power level at the center frequency does not exceed a threshold.
Parameters
threshold the threshold to test
References analogueModelList, centerFrequencyIndex, numAnalogueModelsApplied, and values.
 {
     if (values[centerFrequencyIndex] < threshold) return true;
     uint16_t maxAnalogueModels = analogueModelList->size();
     while (numAnalogueModelsApplied < maxAnalogueModels) {
         // Apply filter here
         (*analogueModelList)[numAnalogueModelsApplied]->filterSignal(this);
         numAnalogueModelsApplied++;
         if (values[centerFrequencyIndex] < threshold) return true;
     }
     return false;
 }
Friends And Related Function Documentation
calculateDuration
simtime_t calculateDuration (const Signal & lhs, const Signal & rhs) friend
Calculate the combined duration of two signals.
Parameters
lhs the first signal
rhs the second signal
 {
     simtime_t temp = std::min(lhs.sendingStart + lhs.duration, rhs.sendingStart + rhs.duration) - std::max(lhs.sendingStart, rhs.sendingStart);
     return (temp > 0) ? temp : 0;
 }
calculateStart
simtime_t calculateStart (const Signal & lhs, const Signal & rhs) friend
Calculate the common start of two signals, i.e.
their minimum start times.
Parameters
lhs the first signal
rhs the second signal
 {
     return std::max(lhs.sendingStart, rhs.sendingStart);
 }
operator<<
std::ostream& operator<< (std::ostream & os, const Signal & s) friend
Convert a signal to a human readable representation.
Parameters
os the outputstream to write to
s the signal to convert
 {
     os << "Signal(";
     if (s.timingUsed) {
         os << "interval: (" << s.getReceptionStart() << ", " << s.getReceptionEnd() << "), ";
     }
     os << s.spectrum << ", ";
     std::ostringstream ss;
     for (auto&& value : s.values) {
         if (ss.tellp() != 0) {
             ss << ", ";
         }
         ss << value;
     }
     os << ss.str();
     os << ")";
     return os;
 }
Member Data Documentation
analogueModelList
AnalogueModelList* veins::Signal::analogueModelList = nullptr private
Referenced by applyAllAnalogueModels(), applyAnalogueModel(), getAnalogueModelList(), greaterAtCenterFrequency(), operator=(), setAnalogueModelList(), and smallerAtCenterFrequency().
centerFrequencyIndex
size_t veins::Signal::centerFrequencyIndex = 0 private
Referenced by getAtCenterFrequency(), getCenterFrequencyIndex(), greaterAtCenterFrequency(), operator=(), setCenterFrequencyIndex(), and smallerAtCenterFrequency().
dataOffset
size_t veins::Signal::dataOffset = 0 private
Referenced by dataAt(), getDataEnd(), getDataMax(), getDataMin(), getDataOffset(), getDataStart(), getDataValues(), operator=(), setDataEnd(), and setDataStart().
duration
simtime_t veins::Signal::duration = 0 private
The duration of the signal transmission.
Referenced by veins::calculateDuration(), getDuration(), getReceptionEnd(), getSendingEnd(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and setTiming().
numAnalogueModelsApplied
uint16_t veins::Signal::numAnalogueModelsApplied = 0 private
Referenced by applyAllAnalogueModels(), applyAnalogueModel(), getNumAnalogueModelsApplied(), greaterAtCenterFrequency(), operator=(), and smallerAtCenterFrequency().
numDataValues
size_t veins::Signal::numDataValues = 0 private
Referenced by getDataEnd(), getDataMax(), getDataMin(), getNumDataValues(), operator=(), setDataEnd(), and setDataNumValues().
propagationDelay
simtime_t veins::Signal::propagationDelay = 0 private
The propagation delay of the transmission.
Referenced by getPropagationDelay(), getReceptionEnd(), getReceptionStart(), operator=(), and setPropagationDelay().
receiverPoa
POA veins::Signal::receiverPoa private
Referenced by getReceiverPoa(), operator=(), and setReceiverPoa().
senderPoa
POA veins::Signal::senderPoa private
Referenced by getSenderPoa(), operator=(), and setSenderPoa().
sendingStart
simtime_t veins::Signal::sendingStart = 0 private
The start of the signal transmission at the sender module.
Referenced by veins::calculateDuration(), veins::calculateStart(), getReceptionEnd(), getReceptionStart(), getSendingEnd(), getSendingStart(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and setTiming().
spectrum
Spectrum veins::Signal::spectrum private
Referenced by atFrequency(), getSpectrum(), veins::operator<<(), and operator=().
timingUsed
bool veins::Signal::timingUsed = false private
Referenced by hasTiming(), operator*=(), operator+=(), operator-=(), operator/=(), veins::operator<<(), operator=(), and setTiming().
values
std::vector<double> veins::Signal::values private
Referenced by at(), atFrequency(), dataAt(), getAtCenterFrequency(), getDataValues(), getMax(), getMaxInRange(), getMinInRange(), getNumValues(), getValues(), greaterAtCenterFrequency(), operator*=(), operator+=(), operator-=(), operator/=(), veins::operator<<(), operator=(), and smallerAtCenterFrequency().
The documentation for this class was generated from the following files:
Signal.h
Signal.cc