Veins: veins::MacToNetwControlInfo Class Reference
veins::MacToNetwControlInfo Class Reference
Stores control information from mac to upper layer.
#include <MacToNetwControlInfo.h>
Public Member Functions
MacToNetwControlInfo (const LAddress::L2Type &lastHop, double ber=0, double rssi=0)
Initializes with the passed last hop address and bit error rate.
~MacToNetwControlInfo () override
double getBitErrorRate () const
Returns the bit error rate for this packet.
virtual void setBitErrorRate (double ber)
Sets the bit error rate for this control infos packet.
const LAddress::L2Type & getLastHopMac () const
Returns the MAC address of the packets last hop.
virtual void setLastHopMac (const LAddress::L2Type &lastHop)
Sets the MAC address of the packets last hop.
virtual const double getRSSI ()
Returns the packets received signal strength.
void setRSSI (double _rssi)
Sets the packets received signal strength.
Static Public Member Functions
static cObject *const setControlInfo (cMessage *const pMsg, const LAddress::L2Type &pSrcAddr)
Attaches a "control info" structure (object) to the message pMsg.
static const LAddress::L2Type & getAddress (cMessage *const pMsg)
static const LAddress::L2Type & getAddressFromControlInfo (cObject *const pCtrlInfo)
Protected Attributes
double bitErrorRate
The bit error rate for this packet.
LAddress::L2Type lastHopMac
MAC address of the last hop of this packet.
double rssi
The received signal strength for this packet.
Detailed Description
Stores control information from mac to upper layer.
Holds the bit error rate of the transmission as well as the MAC address of the last hop.
Author
Karl Wessel
Constructor & Destructor Documentation
MacToNetwControlInfo()
veins::MacToNetwControlInfo::MacToNetwControlInfo (const LAddress::L2Type & lastHop, double ber = 0, double rssi = 0) inline
Initializes with the passed last hop address and bit error rate.
         : bitErrorRate(ber)
         , lastHopMac(lastHop)
         , rssi(rssi)
     {
     }
~MacToNetwControlInfo()
veins::MacToNetwControlInfo::~MacToNetwControlInfo () inline override
     {
     }
Member Function Documentation
getAddress()
static const LAddress::L2Type& veins::MacToNetwControlInfo::getAddress (cMessage *const pMsg) inline static
     {
         return getAddressFromControlInfo(pMsg->getControlInfo());
     }
getAddressFromControlInfo()
static const LAddress::L2Type& veins::MacToNetwControlInfo::getAddressFromControlInfo (cObject *const pCtrlInfo) inline static
References getLastHopMac(), and veins::LAddress::L2NULL().
     {
         MacToNetwControlInfo* const cCtrlInfo = dynamic_cast<MacToNetwControlInfo* const>(pCtrlInfo);
         if (cCtrlInfo) return cCtrlInfo->getLastHopMac();
         return LAddress::L2NULL();
     }
getBitErrorRate()
double veins::MacToNetwControlInfo::getBitErrorRate () const inline
Returns the bit error rate for this packet.
     {
         return bitErrorRate;
     }
getLastHopMac()
const LAddress::L2Type& veins::MacToNetwControlInfo::getLastHopMac () const inline
Returns the MAC address of the packets last hop.
Referenced by getAddressFromControlInfo().
     {
         return lastHopMac;
     }
getRSSI()
virtual const double veins::MacToNetwControlInfo::getRSSI () inline virtual
Returns the packets received signal strength.
Returns
The received signal strength
     {
         return rssi;
     }
setBitErrorRate()
virtual void veins::MacToNetwControlInfo::setBitErrorRate (double ber) inline virtual
Sets the bit error rate for this control infos packet.
Parameters
ber The bit error rate
     {
         bitErrorRate = ber;
     }
setControlInfo()
static cObject* const veins::MacToNetwControlInfo::setControlInfo (cMessage *const pMsg, const LAddress::L2Type & pSrcAddr) inline static
Attaches a "control info" structure (object) to the message pMsg.
This is most useful when passing packets between protocol layers of a protocol stack, the control info will contain the source MAC address.
The "control info" object will be deleted when the message is deleted. Only one "control info" structure can be attached (the second setL3ToL2ControlInfo() call throws an error).
Parameters
pMsg The message where the "control info" shall be attached.
pSrcAddr The MAC address of the message sender.
Referenced by veins::BaseMacLayer::setUpControlInfo().
     {
         MacToNetwControlInfo* const cCtrlInfo = new MacToNetwControlInfo(pSrcAddr);
         pMsg->setControlInfo(cCtrlInfo);
         return cCtrlInfo;
     }
setLastHopMac()
virtual void veins::MacToNetwControlInfo::setLastHopMac (const LAddress::L2Type & lastHop) inline virtual
Sets the MAC address of the packets last hop.
Parameters
lastHop The last hops MAC address
     {
         lastHopMac = lastHop;
     }
setRSSI()
void veins::MacToNetwControlInfo::setRSSI (double _rssi) inline
Sets the packets received signal strength.
Parameters
_rssi The received signal strength
     {
         rssi = _rssi;
     }
Member Data Documentation
bitErrorRate
double veins::MacToNetwControlInfo::bitErrorRate protected
The bit error rate for this packet.
lastHopMac
LAddress::L2Type veins::MacToNetwControlInfo::lastHopMac protected
MAC address of the last hop of this packet.
rssi
double veins::MacToNetwControlInfo::rssi protected
The received signal strength for this packet.
The documentation for this class was generated from the following file:
MacToNetwControlInfo.h