Veins: veins::Spectrum Class Reference
veins::Spectrum Class Reference
#include <Spectrum.h>
Public Types
using Frequency = double
using Frequencies = std::vector< Frequency >
Public Member Functions
Spectrum ()=default
Spectrum (Frequencies freqs)
const double & operator[] (size_t index) const
size_t getNumFreqs () const
size_t indexOf (double freq) const
double freqAt (size_t freqIndex) const
Private Attributes
Frequencies frequencies
Friends
bool VEINS_API operator== (const Spectrum &lhs, const Spectrum &rhs)
std::ostream &VEINS_API operator<< (std::ostream &os, const Spectrum &s)
Member Typedef Documentation
Frequencies
using veins::Spectrum::Frequencies = std::vector<Frequency>
Frequency
using veins::Spectrum::Frequency = double
Constructor & Destructor Documentation
Spectrum() [1/2]
veins::Spectrum::Spectrum () default
Spectrum() [2/2]
veins::Spectrum::Spectrum (Spectrum::Frequencies freqs)
     : frequencies(normalizeFrequencies(freqs))
 {
 }
Member Function Documentation
freqAt()
double veins::Spectrum::freqAt (size_t freqIndex) const
References frequencies.
Referenced by veins::TwoRayInterferenceModel::filterSignal(), veins::SimplePathlossModel::filterSignal(), and veins::VehicleObstacleControl::getVehicleAttenuationSingle().
 {
     return frequencies.at(freqIndex);
 }
getNumFreqs()
size_t veins::Spectrum::getNumFreqs () const
References frequencies.
 {
     return frequencies.size();
 }
indexOf()
size_t veins::Spectrum::indexOf (double freq) const
References frequencies.
Referenced by veins::Signal::atFrequency(), and veins::PhyLayer80211p::attachSignal().
 {
     // Binary search
     auto it = std::lower_bound(frequencies.begin(), frequencies.end(), freq);
     bool found = it != frequencies.end() && (*it) == freq;
     ASSERT(found == true);
     return std::distance(frequencies.begin(), it);
 }
operator[]()
const double & veins::Spectrum::operator[] (size_t index) const
References frequencies.
 {
     return frequencies.at(index);
 }
Friends And Related Function Documentation
operator<<
std::ostream& VEINS_API operator<< (std::ostream & os, const Spectrum & s) friend
 {
     os << "Spectrum(";
     std::ostringstream ss;
     for (auto&& frequency : s.frequencies) {
         if (ss.tellp() != 0) {
             ss << ", ";
         }
         ss << frequency;
     }
     os << ss.str();
     os << ")";
     return os;
 }
operator==
bool VEINS_API operator== (const Spectrum & lhs, const Spectrum & rhs) friend
 {
     return lhs.frequencies == rhs.frequencies;
 }
Member Data Documentation
frequencies
Frequencies veins::Spectrum::frequencies private
Referenced by freqAt(), getNumFreqs(), indexOf(), veins::operator<<(), veins::operator==(), and operator[]().
The documentation for this class was generated from the following files:
Spectrum.h
Spectrum.cc