Veins: veins::TraCICoordinateTransformation Class Reference
veins::TraCICoordinateTransformation Class Reference
Helper class for converting SUMO coordinates to OMNeT++ Coordinates for a given network.
#include <TraCICoordinateTransformation.h>
Public Types
using OmnetCoord = Coord
using OmnetCoordList = std::list< OmnetCoord >
using TraCICoordList = std::list< TraCICoord >
using TraCIHeading = double
using OmnetHeading = Heading
Public Member Functions
TraCICoordinateTransformation (TraCICoord topleft, TraCICoord bottomright, float margin)
TraCICoord omnet2traci (const OmnetCoord &coord) const
TraCICoordList omnet2traci (const OmnetCoordList &coords) const
TraCIHeading omnet2traciHeading (OmnetHeading heading) const
TraCI's heading interpretation: 0 is north, 90 is east.
OmnetCoord traci2omnet (const TraCICoord &coord) const
OmnetCoordList traci2omnet (const TraCICoordList &coords) const
OmnetHeading traci2omnetHeading (TraCIHeading heading) const
OMNeT++'s heading interpretation: 0 is east, pi/2 is north.
Private Attributes
TraCICoord dimensions
TraCICoord topleft
TraCICoord bottomright
float margin
Detailed Description
Helper class for converting SUMO coordinates to OMNeT++ Coordinates for a given network.
Member Typedef Documentation
OmnetCoord
using veins::TraCICoordinateTransformation::OmnetCoord = Coord
OmnetCoordList
using veins::TraCICoordinateTransformation::OmnetCoordList = std::list<OmnetCoord>
OmnetHeading
using veins::TraCICoordinateTransformation::OmnetHeading = Heading
TraCICoordList
using veins::TraCICoordinateTransformation::TraCICoordList = std::list<TraCICoord>
TraCIHeading
using veins::TraCICoordinateTransformation::TraCIHeading = double
Constructor & Destructor Documentation
TraCICoordinateTransformation()
veins::TraCICoordinateTransformation::TraCICoordinateTransformation (TraCICoord topleft, TraCICoord bottomright, float margin)
References bottomright, margin, topleft, veins::TraCICoord::x, and veins::TraCICoord::y.
     : dimensions({bottomright.x - topleft.x, bottomright.y - topleft.y})
     , topleft(topleft)
     , bottomright(bottomright)
     , margin(margin)
 {
 }
Member Function Documentation
omnet2traci() [1/2]
TraCICoord veins::TraCICoordinateTransformation::omnet2traci (const OmnetCoord & coord) const
References dimensions, margin, topleft, veins::TraCICoord::x, veins::Coord::x, veins::TraCICoord::y, and veins::Coord::y.
Referenced by omnet2traci().
 {
     return {coord.x + topleft.x - margin, dimensions.y - (coord.y - topleft.y) + margin};
 }
omnet2traci() [2/2]
TraCICoordList veins::TraCICoordinateTransformation::omnet2traci (const OmnetCoordList & coords) const
References omnet2traci().
 {
     TraCICoordList result;
     for (auto&& coord : coords) {
         result.push_back(omnet2traci(coord));
     }
     return result;
 }
omnet2traciHeading()
TraCIHeading veins::TraCICoordinateTransformation::omnet2traciHeading (OmnetHeading heading) const
TraCI's heading interpretation: 0 is north, 90 is east.
References veins::Heading::getRad(), and M_PI.
 {
     // convert to degrees
     auto angle = o.getRad() * 180 / M_PI;
     // rotate angle
     angle = 90 - angle;
     // normalize angle to -180 <= angle < 180
     while (angle < -180) {
         angle += 360;
     }
     while (angle >= 180) {
         angle -= 360;
     }
     return angle;
 }
traci2omnet() [1/2]
OmnetCoord veins::TraCICoordinateTransformation::traci2omnet (const TraCICoord & coord) const
References dimensions, margin, topleft, veins::TraCICoord::x, and veins::TraCICoord::y.
Referenced by traci2omnet().
 {
     return {coord.x - topleft.x + margin, dimensions.y - (coord.y - topleft.y) + margin};
 }
traci2omnet() [2/2]
OmnetCoordList veins::TraCICoordinateTransformation::traci2omnet (const TraCICoordList & coords) const
References traci2omnet().
 {
     OmnetCoordList result;
     for (auto&& coord : coords) {
         result.push_back(traci2omnet(coord));
     }
     return result;
 }
traci2omnetHeading()
OmnetHeading veins::TraCICoordinateTransformation::traci2omnetHeading (TraCIHeading heading) const
OMNeT++'s heading interpretation: 0 is east, pi/2 is north.
References M_PI.
 {
     // rotate angle
     auto angle = 90 - o;
     // convert to rad
     angle = angle * M_PI / 180.0;
     // normalize angle to -M_PI <= angle < M_PI
     while (angle < -M_PI) {
         angle += 2 * M_PI;
     }
     while (angle >= M_PI) {
         angle -= 2 * M_PI;
     }
     return OmnetHeading(angle);
 }
Member Data Documentation
bottomright
TraCICoord veins::TraCICoordinateTransformation::bottomright private
Referenced by TraCICoordinateTransformation().
dimensions
TraCICoord veins::TraCICoordinateTransformation::dimensions private
Referenced by omnet2traci(), and traci2omnet().
margin
float veins::TraCICoordinateTransformation::margin private
Referenced by omnet2traci(), traci2omnet(), and TraCICoordinateTransformation().
topleft
TraCICoord veins::TraCICoordinateTransformation::topleft private
Referenced by omnet2traci(), traci2omnet(), and TraCICoordinateTransformation().
The documentation for this class was generated from the following files:
TraCICoordinateTransformation.h
TraCICoordinateTransformation.cc