Veins: veins::PhyLayer80211p Class Reference
veins::PhyLayer80211p Class Reference
Adaptation of the PhyLayer class for 802.11p.
#include <PhyLayer80211p.h>
Public Member Functions
void initialize (int stage) override
void setCCAThreshold (double ccaThreshold_dBm) override
Set the carrier sense threshold.
double getCCAThreshold ()
Return the cca threshold in dBm.
void notifyMacAboutRxStart (bool enable) override
Enable notifications about PHY-RXSTART.indication in MAC.
void requestChannelStatusIfIdle () override
Explicit request to PHY for the channel status.
Public Member Functions inherited from veins::BasePhyLayer
~BasePhyLayer () override
void finish () override
Call the deciders finish method.
void setCurrentRadioChannel (int newRadioChannel) override
Set the channel currently used by the radio.
int getCurrentRadioChannel () override
Return the channel currently used by the radio.
int getNbRadioChannels () override
Return the number of channels available on this radio.
void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out) override
Fill the given AirFrameVector with all AirFrames that intersect with the given time interval.
double getNoiseFloorValue () override
Return noise floor level (in mW).
void sendControlMsgToMac (cMessage *msg) override
Send the given message to via the control gate to the mac.
void sendUp (AirFrame *packet, DeciderResult *result) override
Pass the given packet along with the result up to the mac.
BaseWorldUtility * getWorldUtility () override
Return a pointer to the simulations world-utility-module.
void recordScalar (const char *name, double value, const char *unit=nullptr) override
Record a double into the scalar result file.
Public Member Functions inherited from veins::ChannelAccess
void initialize (int stage) override
Register with ConnectionManager.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Called by the signalling mechanism to inform of changes.
virtual ChannelMobilityPtrType getMobilityModule ()
Returns the host's mobility module.
virtual AntennaPosition getAntennaPosition () const
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Public Member Functions inherited from veins::DeciderToPhyInterface
virtual ~DeciderToPhyInterface ()
Public Member Functions inherited from veins::MacToPhyInterface
virtual ~MacToPhyInterface ()
Public Member Functions inherited from veins::Mac80211pToPhy11pInterface
virtual ~Mac80211pToPhy11pInterface ()=default
Public Member Functions inherited from veins::Decider80211pToPhy80211pInterface
virtual ~Decider80211pToPhy80211pInterface ()
Protected Types
enum ProtocolIds { IEEE_80211 = 12123 }
Protected Types inherited from veins::BasePhyLayer
enum AirFrameState { AirFrameState::start_receive = 1, AirFrameState::receiving, AirFrameState::end_receive }
The states of the receiving process for AirFrames.
enum ProtocolIds { PROTOCOL_ID_GENERIC = 0 }
using ParameterMap = std::map< std::string, cMsgPar >
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Protected Types inherited from veins::AccessModuleWrap< T >
using wrapType = T
Protected Member Functions
virtual std::unique_ptr< AnalogueModel > getAnalogueModelFromName (std::string name, ParameterMap &params) override
Creates and returns an instance of the AnalogueModel with the specified name.
std::unique_ptr< AnalogueModel > initializeSimplePathlossModel (ParameterMap &params)
Creates and initializes a SimplePathlossModel with the passed parameter values.
std::unique_ptr< AnalogueModel > initializeAntennaModel (ParameterMap &params)
Creates and initializes an AntennaModel with the passed parameter values.
virtual std::unique_ptr< AnalogueModel > initializeBreakpointPathlossModel (ParameterMap &params)
Creates and initializes a BreakpointPathlossModel with the passed parameter values.
std::unique_ptr< AnalogueModel > initializeSimpleObstacleShadowing (ParameterMap &params)
Creates and initializes a SimpleObstacleShadowing with the passed parameter values.
std::unique_ptr< AnalogueModel > initializeVehicleObstacleShadowing (ParameterMap &params)
Creates and initializes a VehicleObstacleShadowing with the passed parameter values.
virtual std::unique_ptr< AnalogueModel > initializePERModel (ParameterMap &params)
Creates a simple Packet Error Rate model that attenuates a percentage of the packets to zero, and does not attenuate the other packets.
std::unique_ptr< AnalogueModel > initializeTwoRayInterferenceModel (ParameterMap &params)
Creates and initializes a TwoRayInterferenceModel with the passed parameter values.
std::unique_ptr< AnalogueModel > initializeNakagamiFading (ParameterMap &params)
Creates and initializes a NakagamiFading with the passed parameter values.
virtual std::unique_ptr< Decider > getDeciderFromName (std::string name, ParameterMap &params) override
Creates and returns an instance of the Decider with the specified name.
virtual std::unique_ptr< Decider > initializeDecider80211p (ParameterMap &params)
Initializes a new Decider80211 from the passed parameter map.
std::unique_ptr< AirFrame > createAirFrame (cPacket *macPkt) override
Create a protocol-specific AirFrame Overloaded to create a specialize AirFrame11p.
void attachSignal (AirFrame *airFrame, cObject *ctrlInfo) override
Attach a signal to the given AirFrame.
void changeListeningChannel (Channel channel) override
virtual simtime_t getFrameDuration (int payloadLengthBits, MCS mcs) const override
void handleSelfMessage (cMessage *msg) override
Handle self scheduled messages.
int getRadioState () override
Return the current state the radio is in.
simtime_t setRadioState (int rs) override
Tell the BasePhyLayer to switch to the specified radio state.
Protected Member Functions inherited from veins::BasePhyLayer
template<class T >
T readPar (const char *parName, const T defaultValue)
Read and return the parameter with the passed name.
void initialize (int stage) override
Initialize members and associated objects according to parameterization.
void handleMessage (cMessage *msg) override
Process received messages and pass to specific handlers.
virtual std::unique_ptr< Radio > initializeRadio ()
Create and return the radio class to use.
virtual std::shared_ptr< Antenna > getAntennaFromName (std::string name, ParameterMap &params)
Create and return an instance of the Antenna with the specified name as a shared pointer.
virtual std::shared_ptr< Antenna > initializeSampledAntenna1D (ParameterMap &params)
Creates and returns an instance of the SampledAntenna1D class as a shared pointer.
virtual std::unique_ptr< AirFrame > encapsMsg (cPacket *msg)
Encapsulate messages from the upper layer into an AirFrame and set all necessary attributes.
virtual void filterSignal (AirFrame *frame)
Filter the passed AirFrame's Signal by every registered AnalogueModel.
virtual void finishRadioSwitching ()
Called when the switching process of the Radio is finished.
virtual int myProtocolId ()
Return the identifier of the protocol this phy uses to send messages.
virtual bool isKnownProtocolId (int id)
Return whether the protocol with the passed identifier is decodeable by the decider.
virtual void handleAirFrame (AirFrame *frame)
Handle messages received from the channel.
virtual void handleUpperMessage (cMessage *msg)
Handle messages received from the upper layer and start transmitting them.
virtual void handleUpperControlMessage (cMessage *msg)
Handle messages received from the upper layer through the control gate.
virtual void handleAirFrameStartReceive (AirFrame *msg)
Handle incoming AirFrames with the state AirFrameState::start_receive.
virtual void handleAirFrameReceiving (AirFrame *msg)
Handle incoming AirFrames with the state AirFrameState::receiving.
virtual void handleAirFrameEndReceive (AirFrame *msg)
Handle incoming AirFrames with the state AirFrameState::end_receive.
void sendControlMessageUp (cMessage *msg)
Send the passed control message to the upper layer.
void sendMacPktUp (cMessage *pkt)
Send the passed MacPkt to the upper layer.
void sendMessageDown (AirFrame *pkt)
Send the passed AirFrame to the channel.
void sendSelfMessage (cMessage *msg, simtime_t_cref time)
Schedule self message to passed point in time.
Protected Member Functions inherited from veins::ChannelAccess
simtime_t calculatePropagationDelay (const NicEntry *nic)
Calculates the propagation delay to the passed receiving nic.
void sendToChannel (cPacket *msg)
Sends a message to all nics connected to this one.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Member Functions inherited from veins::AccessModuleWrap< T >
AccessModuleWrap ()
T *const get (cModule *const from=nullptr)
Protected Attributes
double ccaThreshold
CCA threshold.
bool collectCollisionStatistics
enable/disable detection of packet collisions
bool allowTxDuringRx
allows/disallows interruption of current reception for txing
Protected Attributes inherited from veins::BasePhyLayer
int protocolId = PROTOCOL_ID_GENERIC
The ID of the protocol this phy can transceive.
double noiseFloorValue = 0
Catch-all for all factors negatively impacting SINR (e.g., thermal noise, noise figure, ...)
double minPowerLevel
The minimum receive power needed to even attempt decoding a frame.
bool recordStats
Stores if tracking of statistics (esp. cOutvectors) is enabled.
ChannelInfo channelInfo
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
std::unique_ptr< Radio > radio
The state machine storing the current radio state (TX, RX, SLEEP).
std::shared_ptr< Antenna > antenna
Shared pointer to the Antenna used for this node.
std::unique_ptr< Decider > decider
Pointer to the decider module.
AnalogueModelList analogueModels
The analogue models to use which might attenuate or amplify a signal.
AnalogueModelList analogueModelsThresholding
The analogue models to use which will only attenuate a signal.
int upperLayerIn
The id of the in-data gate from the Mac layer.
int upperLayerOut
The id of the out-data gate to the Mac layer.
int upperControlOut
The id of the out-control gate to the Mac layer.
int upperControlIn
The id of the in-control gate from the Mac layer.
cMessage * radioSwitchingOverTimer = nullptr
Self message scheduled to the point in time when the switching process of the radio is over.
cMessage * txOverTimer = nullptr
Self message scheduled to the point in time when the transmission of an AirFrame is over.
BaseWorldUtility * world = nullptr
Pointer to the World Utility, to obtain some global information.
Spectrum overallSpectrum
The underlying spectrum (definition of interesting freqs) for all signals.
Protected Attributes inherited from veins::ChannelAccess
bool useSendDirect
use sendDirect or not?
BaseConnectionManager * cc
Pointer to the PropagationModel module.
bool usePropagationDelay
Defines if the physical layer should simulate propagation delay.
bool isRegistered
Is this module already registered with ConnectionManager?
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
AntennaPosition antennaPosition
Current antenna position.
Heading antennaHeading
Current antenna heading (angle)
Coord antennaOffset = Coord(0, 0, 0)
Offset of antenna position (in m) with respect to what a BaseMobility module will tell us.
double antennaOffsetYaw = 0
Offset of antenna orientation (yaw, in rad) with respect to what a BaseMobility module will tell us.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Public Types inherited from veins::DeciderToPhyInterface
using AirFrameVector = std::list< AirFrame * >
Type for container of AirFrames.
Public Types inherited from veins::MacToPhyInterface
enum BasePhyMessageKinds {
TX_OVER = 22000, RADIO_SWITCHING_OVER, AIR_FRAME, PHY_RX_START,
PHY_RX_END_WITH_SUCCESS, PHY_RX_END_WITH_FAILURE, LAST_BASE_PHY_KIND
}
Message kinds used by every phy layer.
Public Types inherited from veins::Mac80211pToPhy11pInterface
enum BasePhyMessageKinds { CHANNEL_IDLE, CHANNEL_BUSY }
Static Public Member Functions inherited from veins::ChannelAccess
static BaseConnectionManager * getConnectionManager (cModule *nic)
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Static Protected Member Functions inherited from veins::BasePhyLayer
static short airFramePriority ()
Defines the scheduling priority of AirFrames.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Adaptation of the PhyLayer class for 802.11p.
See also
DemoBaseApplLayer
Mac1609_4
PhyLayer80211p
Decider80211p
Member Enumeration Documentation
ProtocolIds
enum veins::PhyLayer80211p::ProtocolIds protected
Enumerator
IEEE_80211
                      {
         IEEE_80211 = 12123
     };
Member Function Documentation
attachSignal()
void PhyLayer80211p::attachSignal (AirFrame * airFrame, cObject * ctrlInfo) override protected virtual
Attach a signal to the given AirFrame.
The attached Signal corresponds to the IEEE 802.11p standard. Parameters for the signal are passed in the control info. The indicated power levels are set up on the specified center frequency, as well as the neighboring 5MHz.
Note
The control info must be of type MacToPhyControlInfo11p
Reimplemented from veins::BasePhyLayer.
References veins::Signal::at(), veins::Signal::getDuration(), getFrameDuration(), veins::IEEE80211ChannelFrequencies, veins::Spectrum::indexOf(), veins::BasePhyLayer::overallSpectrum, veins::Signal::setCenterFrequencyIndex(), veins::Signal::setDataEnd(), and veins::Signal::setDataStart().
 {
     const auto ctrlInfo11p = check_and_cast<MacToPhyControlInfo11p*>(ctrlInfo);
     const auto duration = getFrameDuration(airFrame->getEncapsulatedPacket()->getBitLength(), ctrlInfo11p->mcs);
     ASSERT(duration > 0);
     Signal signal(overallSpectrum, simTime(), duration);
     auto freqIndex = overallSpectrum.indexOf(IEEE80211ChannelFrequencies.at(ctrlInfo11p->channelNr));
     signal.at(freqIndex - 1) = ctrlInfo11p->txPower_mW;
     signal.at(freqIndex) = ctrlInfo11p->txPower_mW;
     signal.at(freqIndex + 1) = ctrlInfo11p->txPower_mW;
     signal.setDataStart(freqIndex - 1);
     signal.setDataEnd(freqIndex + 1);
     signal.setCenterFrequencyIndex(freqIndex);
     // copy the signal into the AirFrame
     airFrame->setSignal(signal);
     airFrame->setDuration(signal.getDuration());
     airFrame->setMcs(static_cast<int>(ctrlInfo11p->mcs));
 }
changeListeningChannel()
void PhyLayer80211p::changeListeningChannel (Channel channel) override protected virtual
Implements veins::Mac80211pToPhy11pInterface.
References veins::Decider80211p::changeFrequency(), veins::BasePhyLayer::decider, and veins::IEEE80211ChannelFrequencies.
 {
     Decider80211p* dec = dynamic_cast<Decider80211p*>(decider.get());
     ASSERT(dec);
     double freq = IEEE80211ChannelFrequencies.at(channel);
     dec->changeFrequency(freq);
 }
createAirFrame()
unique_ptr< AirFrame > PhyLayer80211p::createAirFrame (cPacket * macPkt) override protected virtual
Create a protocol-specific AirFrame Overloaded to create a specialize AirFrame11p.
Reimplemented from veins::BasePhyLayer.
References veins::MacToPhyInterface::AIR_FRAME.
 {
     return make_unique<AirFrame11p>(macPkt->getName(), AIR_FRAME);
 }
getAnalogueModelFromName()
unique_ptr< AnalogueModel > PhyLayer80211p::getAnalogueModelFromName (std::string name, ParameterMap & params) override protected virtual
Creates and returns an instance of the AnalogueModel with the specified name.
Is able to initialize the following AnalogueModels:
Reimplemented from veins::BasePhyLayer.
References veins::BasePhyLayer::getAnalogueModelFromName(), initializeBreakpointPathlossModel(), initializeNakagamiFading(), initializePERModel(), initializeSimpleObstacleShadowing(), initializeSimplePathlossModel(), initializeTwoRayInterferenceModel(), initializeVehicleObstacleShadowing(), veins::BaseWorldUtility::use2D(), and veins::BasePhyLayer::world.
 {
     if (name == "SimplePathlossModel") {
         return initializeSimplePathlossModel(params);
     }
     else if (name == "BreakpointPathlossModel") {
         return initializeBreakpointPathlossModel(params);
     }
     else if (name == "PERModel") {
         return initializePERModel(params);
     }
     else if (name == "SimpleObstacleShadowing") {
         return initializeSimpleObstacleShadowing(params);
     }
     else if (name == "VehicleObstacleShadowing") {
         return initializeVehicleObstacleShadowing(params);
     }
     else if (name == "TwoRayInterferenceModel") {
         if (world->use2D()) throw cRuntimeError("The TwoRayInterferenceModel uses nodes' z-position as the antenna height over ground. Refusing to work in a 2D world");
         return initializeTwoRayInterferenceModel(params);
     }
     else if (name == "NakagamiFading") {
         return initializeNakagamiFading(params);
     }
     return BasePhyLayer::getAnalogueModelFromName(name, params);
 }
getCCAThreshold()
double PhyLayer80211p::getCCAThreshold ()
Return the cca threshold in dBm.
References ccaThreshold.
 {
     return 10 * log10(ccaThreshold);
 }
getDeciderFromName()
unique_ptr< Decider > PhyLayer80211p::getDeciderFromName (std::string name, ParameterMap & params) override protected virtual
Creates and returns an instance of the Decider with the specified name.
Is able to initialize the following Deciders:
Decider80211p
Reimplemented from veins::BasePhyLayer.
References veins::BasePhyLayer::getDeciderFromName(), IEEE_80211, initializeDecider80211p(), and veins::BasePhyLayer::protocolId.
 {
     if (name == "Decider80211p") {
         protocolId = IEEE_80211;
         return initializeDecider80211p(params);
     }
     return BasePhyLayer::getDeciderFromName(name, params);
 }
getFrameDuration()
simtime_t PhyLayer80211p::getFrameDuration (int payloadLengthBits, MCS mcs) const override protected virtual
Implements veins::Mac80211pToPhy11pInterface.
References veins::getNDBPS(), veins::PHY_HDR_PLCPSIGNAL_DURATION, veins::PHY_HDR_PREAMBLE_DURATION, veins::T_SYM_80211P, and veins::undefined.
Referenced by attachSignal().
 {
     Enter_Method_Silent();
     ASSERT(mcs != MCS::undefined);
     auto ndbps = getNDBPS(mcs);
     // calculate frame duration according to Equation (17-29) of the IEEE 802.11-2007 standard
     return PHY_HDR_PREAMBLE_DURATION + PHY_HDR_PLCPSIGNAL_DURATION + T_SYM_80211P * ceil(static_cast<double>(16 + payloadLengthBits + 6) / (ndbps));
 }
getRadioState()
int PhyLayer80211p::getRadioState () override protected virtual
Return the current state the radio is in.
See also
RadioState for possible values.
Reimplemented from veins::BasePhyLayer.
References veins::BasePhyLayer::getRadioState().
 {
     return BasePhyLayer::getRadioState();
 };
handleSelfMessage()
void PhyLayer80211p::handleSelfMessage (cMessage * msg) override protected virtual
Handle self scheduled messages.
Reimplemented from veins::BasePhyLayer.
References veins::MacToPhyInterface::AIR_FRAME, veins::Decider80211p::cca(), veins::BasePhyLayer::decider, veins::BasePhyLayer::finishRadioSwitching(), veins::BasePhyLayer::handleAirFrame(), veins::MacToPhyInterface::RADIO_SWITCHING_OVER, veins::BasePhyLayer::radioSwitchingOverTimer, veins::BasePhyLayer::sendControlMsgToMac(), veins::Decider80211p::setChannelIdleStatus(), veins::MacToPhyInterface::TX_OVER, and veins::BasePhyLayer::txOverTimer.
 {
     switch (msg->getKind()) {
     // transmission overBasePhyLayer::
     case TX_OVER: {
         ASSERT(msg == txOverTimer);
         sendControlMsgToMac(new cMessage("Transmission over", TX_OVER));
         // check if there is another packet on the chan, and change the chan-state to idle
         Decider80211p* dec = dynamic_cast<Decider80211p*>(decider.get());
         ASSERT(dec);
         if (dec->cca(simTime(), nullptr)) {
             // chan is idle
             EV_TRACE << "Channel idle after transmit!\n";
             dec->setChannelIdleStatus(true);
         }
         else {
             EV_TRACE << "Channel not yet idle after transmit!\n";
         }
         break;
     }
     // radio switch over
     case RADIO_SWITCHING_OVER:
         ASSERT(msg == radioSwitchingOverTimer);
         BasePhyLayer::finishRadioSwitching();
         break;
     // AirFrame
     case AIR_FRAME:
         BasePhyLayer::handleAirFrame(static_cast<AirFrame*>(msg));
         break;
     default:
         break;
     }
 }
initialize()
void PhyLayer80211p::initialize (int stage) override
References allowTxDuringRx, ccaThreshold, collectCollisionStatistics, veins::IEEE80211ChannelFrequencies, veins::BasePhyLayer::initialize(), and veins::BasePhyLayer::overallSpectrum.
 {
     if (stage == 0) {
         // get ccaThreshold before calling BasePhyLayer::initialize() which instantiates the deciders
         ccaThreshold = pow(10, par("ccaThreshold").doubleValue() / 10);
         allowTxDuringRx = par("allowTxDuringRx").boolValue();
         collectCollisionStatistics = par("collectCollisionStatistics").boolValue();
         // Create frequency mappings and initialize spectrum for signal representation
         Spectrum::Frequencies freqs;
         for (auto& channel : IEEE80211ChannelFrequencies) {
             freqs.push_back(channel.second - 5e6);
             freqs.push_back(channel.second);
             freqs.push_back(channel.second + 5e6);
         }
         overallSpectrum = Spectrum(freqs);
     }
     BasePhyLayer::initialize(stage);
 }
initializeAntennaModel()
std::unique_ptr<AnalogueModel> veins::PhyLayer80211p::initializeAntennaModel (ParameterMap & params) protected
Creates and initializes an AntennaModel with the passed parameter values.
initializeBreakpointPathlossModel()
unique_ptr< AnalogueModel > PhyLayer80211p::initializeBreakpointPathlossModel (ParameterMap & params) protected virtual
Creates and initializes a BreakpointPathlossModel with the passed parameter values.
References veins::ChannelAccess::cc, veins::BaseWorldUtility::getPgs(), veins::BaseWorldUtility::useTorus(), and veins::BasePhyLayer::world.
Referenced by getAnalogueModelFromName().
 {
     double alpha1 = -1, alpha2 = -1, breakpointDistance = -1;
     double L01 = -1, L02 = -1;
     bool useTorus = world->useTorus();
     const Coord& playgroundSize = *(world->getPgs());
     ParameterMap::iterator it;
     it = params.find("alpha1");
     if (it != params.end()) { // parameter alpha1 has been specified in config.xml
         // set alpha1
         alpha1 = it->second.doubleValue();
         EV_TRACE << "createPathLossModel(): alpha1 set from config.xml to " << alpha1 << endl;
         // check whether alpha is not smaller than specified in ConnectionManager
         if (cc->hasPar("alpha") && alpha1 < cc->par("alpha").doubleValue()) {
             // throw error
             throw cRuntimeError("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                    ConnectionManager. Please adjust your config.xml file accordingly");
         }
     }
     it = params.find("L01");
     if (it != params.end()) {
         L01 = it->second.doubleValue();
     }
     it = params.find("L02");
     if (it != params.end()) {
         L02 = it->second.doubleValue();
     }
     it = params.find("alpha2");
     if (it != params.end()) { // parameter alpha1 has been specified in config.xml
         // set alpha2
         alpha2 = it->second.doubleValue();
         EV_TRACE << "createPathLossModel(): alpha2 set from config.xml to " << alpha2 << endl;
         // check whether alpha is not smaller than specified in ConnectionManager
         if (cc->hasPar("alpha") && alpha2 < cc->par("alpha").doubleValue()) {
             // throw error
             throw cRuntimeError("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                    ConnectionManager. Please adjust your config.xml file accordingly");
         }
     }
     it = params.find("breakpointDistance");
     if (it != params.end()) { // parameter alpha1 has been specified in config.xml
         breakpointDistance = it->second.doubleValue();
         EV_TRACE << "createPathLossModel(): breakpointDistance set from config.xml to " << alpha2 << endl;
         // check whether alpha is not smaller than specified in ConnectionManager
     }
     if (alpha1 == -1 || alpha2 == -1 || breakpointDistance == -1 || L01 == -1 || L02 == -1) {
         throw cRuntimeError("Undefined parameters for breakpointPathlossModel. Please check your configuration.");
     }
     return make_unique<BreakpointPathlossModel>(this, L01, L02, alpha1, alpha2, breakpointDistance, useTorus, playgroundSize);
 }
initializeDecider80211p()
unique_ptr< Decider > PhyLayer80211p::initializeDecider80211p (ParameterMap & params) protected virtual
Initializes a new Decider80211 from the passed parameter map.
References allowTxDuringRx, ccaThreshold, collectCollisionStatistics, veins::BaseModule::findHost(), and veins::BasePhyLayer::minPowerLevel.
Referenced by getDeciderFromName().
 {
     double centerFreq = params["centerFrequency"];
     auto dec = make_unique<Decider80211p>(this, this, minPowerLevel, ccaThreshold, allowTxDuringRx, centerFreq, findHost()->getIndex(), collectCollisionStatistics);
     dec->setPath(getParentModule()->getFullPath());
     return unique_ptr<Decider>(std::move(dec));
 }
initializeNakagamiFading()
unique_ptr< AnalogueModel > PhyLayer80211p::initializeNakagamiFading (ParameterMap & params) protected
Creates and initializes a NakagamiFading with the passed parameter values.
Referenced by getAnalogueModelFromName().
 {
     bool constM = params["constM"].boolValue();
     double m = 0;
     if (constM) {
         m = params["m"].doubleValue();
     }
     return make_unique<NakagamiFading>(this, constM, m);
 }
initializePERModel()
unique_ptr< AnalogueModel > PhyLayer80211p::initializePERModel (ParameterMap & params) protected virtual
Creates a simple Packet Error Rate model that attenuates a percentage of the packets to zero, and does not attenuate the other packets.
Referenced by getAnalogueModelFromName().
 {
     double per = params["packetErrorRate"].doubleValue();
     return make_unique<PERModel>(this, per);
 }
initializeSimpleObstacleShadowing()
unique_ptr< AnalogueModel > PhyLayer80211p::initializeSimpleObstacleShadowing (ParameterMap & params) protected
Creates and initializes a SimpleObstacleShadowing with the passed parameter values.
References veins::ObstacleControlAccess::getIfExists(), veins::BaseWorldUtility::getPgs(), veins::BaseWorldUtility::useTorus(), and veins::BasePhyLayer::world.
Referenced by getAnalogueModelFromName().
 {
     // init with default value
     bool useTorus = world->useTorus();
     const Coord& playgroundSize = *(world->getPgs());
     ParameterMap::iterator it;
     ObstacleControl* obstacleControlP = ObstacleControlAccess().getIfExists();
     if (!obstacleControlP) throw cRuntimeError("initializeSimpleObstacleShadowing(): cannot find ObstacleControl module");
     return make_unique<SimpleObstacleShadowing>(this, *obstacleControlP, useTorus, playgroundSize);
 }
initializeSimplePathlossModel()
unique_ptr< AnalogueModel > PhyLayer80211p::initializeSimplePathlossModel (ParameterMap & params) protected
Creates and initializes a SimplePathlossModel with the passed parameter values.
References veins::ChannelAccess::cc, veins::BaseWorldUtility::getPgs(), veins::BaseWorldUtility::useTorus(), and veins::BasePhyLayer::world.
Referenced by getAnalogueModelFromName().
 {
     // init with default value
     double alpha = 2.0;
     bool useTorus = world->useTorus();
     const Coord& playgroundSize = *(world->getPgs());
     // get alpha-coefficient from config
     ParameterMap::iterator it = params.find("alpha");
     if (it != params.end()) { // parameter alpha has been specified in config.xml
         // set alpha
         alpha = it->second.doubleValue();
         EV_TRACE << "createPathLossModel(): alpha set from config.xml to " << alpha << endl;
         // check whether alpha is not smaller than specified in ConnectionManager
         if (cc->hasPar("alpha") && alpha < cc->par("alpha").doubleValue()) {
             // throw error
             throw cRuntimeError("TestPhyLayer::createPathLossModel(): alpha can't be smaller than specified in \
                    ConnectionManager. Please adjust your config.xml file accordingly");
         }
     }
     else // alpha has not been specified in config.xml
     {
         if (cc->hasPar("alpha")) { // parameter alpha has been specified in ConnectionManager
             // set alpha according to ConnectionManager
             alpha = cc->par("alpha").doubleValue();
             EV_TRACE << "createPathLossModel(): alpha set from ConnectionManager to " << alpha << endl;
         }
         else // alpha has not been specified in ConnectionManager
         {
             // keep alpha at default value
             EV_TRACE << "createPathLossModel(): alpha set from default value to " << alpha << endl;
         }
     }
     return make_unique<SimplePathlossModel>(this, alpha, useTorus, playgroundSize);
 }
initializeTwoRayInterferenceModel()
unique_ptr< AnalogueModel > PhyLayer80211p::initializeTwoRayInterferenceModel (ParameterMap & params) protected
Creates and initializes a TwoRayInterferenceModel with the passed parameter values.
Referenced by getAnalogueModelFromName().
 {
     ASSERT(params.count("DielectricConstant") == 1);
     double dielectricConstant = params["DielectricConstant"].doubleValue();
     return make_unique<TwoRayInterferenceModel>(this, dielectricConstant);
 }
initializeVehicleObstacleShadowing()
unique_ptr< AnalogueModel > PhyLayer80211p::initializeVehicleObstacleShadowing (ParameterMap & params) protected
Creates and initializes a VehicleObstacleShadowing with the passed parameter values.
References veins::VehicleObstacleControlAccess::getIfExists(), veins::BaseWorldUtility::getPgs(), veins::BaseWorldUtility::useTorus(), and veins::BasePhyLayer::world.
Referenced by getAnalogueModelFromName().
 {
     // init with default value
     bool useTorus = world->useTorus();
     const Coord& playgroundSize = *(world->getPgs());
     ParameterMap::iterator it;
     VehicleObstacleControl* vehicleObstacleControlP = VehicleObstacleControlAccess().getIfExists();
     if (!vehicleObstacleControlP) throw cRuntimeError("initializeVehicleObstacleShadowing(): cannot find VehicleObstacleControl module");
     return make_unique<VehicleObstacleShadowing>(this, *vehicleObstacleControlP, useTorus, playgroundSize);
 }
notifyMacAboutRxStart()
void PhyLayer80211p::notifyMacAboutRxStart (bool enable) override virtual
Enable notifications about PHY-RXSTART.indication in MAC.
Parameters
enable true if Mac needs to be notified about it
Implements veins::Mac80211pToPhy11pInterface.
References veins::BasePhyLayer::decider, and veins::Decider80211p::setNotifyRxStart().
 {
     Decider80211p* dec = dynamic_cast<Decider80211p*>(decider.get());
     ASSERT(dec);
     dec->setNotifyRxStart(enable);
 }
requestChannelStatusIfIdle()
void PhyLayer80211p::requestChannelStatusIfIdle () override virtual
Explicit request to PHY for the channel status.
Implements veins::Mac80211pToPhy11pInterface.
References veins::Decider80211p::cca(), veins::BasePhyLayer::decider, and veins::Decider80211p::setChannelIdleStatus().
 {
     Enter_Method_Silent();
     Decider80211p* dec = dynamic_cast<Decider80211p*>(decider.get());
     ASSERT(dec);
     if (dec->cca(simTime(), nullptr)) {
         // chan is idle
         EV_TRACE << "Request channel status: channel idle!\n";
         dec->setChannelIdleStatus(true);
     }
 }
setCCAThreshold()
void PhyLayer80211p::setCCAThreshold (double ccaThreshold_dBm) override virtual
Set the carrier sense threshold.
Parameters
ccaThreshold_dBm the cca threshold in dBm
Implements veins::Mac80211pToPhy11pInterface.
References ccaThreshold, veins::BasePhyLayer::decider, and veins::Decider80211p::setCCAThreshold().
 {
     ccaThreshold = pow(10, ccaThreshold_dBm / 10);
     Decider80211p* dec = dynamic_cast<Decider80211p*>(decider.get());
     ASSERT(dec);
     dec->setCCAThreshold(ccaThreshold_dBm);
 }
setRadioState()
simtime_t PhyLayer80211p::setRadioState (int rs) override protected virtual
Tell the BasePhyLayer to switch to the specified radio state.
The switching process can take some time depending on the specified switching times in the ned file.
Returns
Switching time from the current RadioState to the new RadioState or -1 if a state change is already in progress.
Reimplemented from veins::BasePhyLayer.
References veins::BasePhyLayer::decider, veins::BasePhyLayer::setRadioState(), and veins::Radio::TX.
 {
     if (rs == Radio::TX) decider->switchToTx();
     return BasePhyLayer::setRadioState(rs);
 }
Member Data Documentation
allowTxDuringRx
bool veins::PhyLayer80211p::allowTxDuringRx protected
allows/disallows interruption of current reception for txing
See detailed description in Decider80211p
Referenced by initialize(), and initializeDecider80211p().
ccaThreshold
double veins::PhyLayer80211p::ccaThreshold protected
CCA threshold.
See Decider80211p for details
Referenced by getCCAThreshold(), initialize(), initializeDecider80211p(), and setCCAThreshold().
collectCollisionStatistics
bool veins::PhyLayer80211p::collectCollisionStatistics protected
enable/disable detection of packet collisions
Referenced by initialize(), and initializeDecider80211p().
The documentation for this class was generated from the following files:
PhyLayer80211p.h
PhyLayer80211p.cc