Veins: veins::BaseConnectionManager::CoordSet Class Reference
veins::BaseConnectionManager::CoordSet Class Reference
Represents an minimalistic (hash)set of GridCoords.
Public Member Functions
CoordSet (unsigned sz)
Initializes the set (hashtable) with the a specified size.
~CoordSet ()
Delete every created GridCoord.
void add (const GridCoord &c)
Adds a GridCoord to the set.
GridCoord * next ()
Returns the next GridCoord in the set.
unsigned getSize ()
Returns the number of GridCoords currently saved in this set.
unsigned getmaxSize ()
Returns the maximum number of elements which can be stored inside this set.
Protected Member Functions
void insert (const GridCoord &c, unsigned pos)
Tries to insert a GridCoord at the specified position.
Protected Attributes
std::vector< GridCoord * > data
Holds the hash table.
unsigned maxSize
maximum size of the hash table.
unsigned size
Current number of entries in the hash table.
unsigned current
Holds the current element when iterating over this table.
Detailed Description
Represents an minimalistic (hash)set of GridCoords.
It is a workaround because c++ doesn't come with an hash set.
Constructor & Destructor Documentation
CoordSet()
veins::BaseConnectionManager::CoordSet::CoordSet (unsigned sz) inline
Initializes the set (hashtable) with the a specified size.
             : maxSize(sz)
             , size(0)
             , current(0)
         {
             data.resize(maxSize);
         }
~CoordSet()
veins::BaseConnectionManager::CoordSet::~CoordSet () inline
Delete every created GridCoord.
         {
             for (unsigned i = 0; i < maxSize; i++) {
                 if (data[i] != nullptr) {
                     delete data[i];
                 }
             }
         }
Member Function Documentation
add()
void veins::BaseConnectionManager::CoordSet::add (const GridCoord & c) inline
Adds a GridCoord to the set.
If a GridCoord with the same value already exists in the set nothing happens.
References veins::BaseConnectionManager::GridCoord::x, veins::BaseConnectionManager::GridCoord::y, and veins::BaseConnectionManager::GridCoord::z.
Referenced by veins::BaseConnectionManager::checkGrid(), veins::BaseConnectionManager::fillUnionWithNeighbors(), and veins::BaseConnectionManager::unregisterNic().
         {
             unsigned hash = (c.x * 10000 + c.y * 100 + c.z) % maxSize;
             insert(c, hash);
         }
getmaxSize()
unsigned veins::BaseConnectionManager::CoordSet::getmaxSize () inline
Returns the maximum number of elements which can be stored inside this set.
To prevent collisions the set should never be more than 75% filled.
         {
             return maxSize;
         }
getSize()
unsigned veins::BaseConnectionManager::CoordSet::getSize () inline
Returns the number of GridCoords currently saved in this set.
         {
             return size;
         }
insert()
void veins::BaseConnectionManager::CoordSet::insert (const GridCoord & c, unsigned pos) inline protected
Tries to insert a GridCoord at the specified position.
If the same Coord already exists there nothing happens. If an other Coord already exists there calculate a new Position to insert end recursively call this Method again. If the spot is empty the Coord is inserted.
         {
             if (data[pos] == nullptr) {
                 data[pos] = new GridCoord(c);
                 size++;
             }
             else {
                 if (*data[pos] != c) {
                     insert(c, (pos + 2) % maxSize);
                 }
             }
         }
next()
GridCoord* veins::BaseConnectionManager::CoordSet::next () inline
Returns the next GridCoord in the set.
You can iterate through the set only one time with this function!
Referenced by veins::BaseConnectionManager::checkGrid(), and veins::BaseConnectionManager::unregisterNic().
         {
             for (; current < maxSize; current++) {
                 if (data[current] != nullptr) {
                     return data[current++];
                 }
             }
             return nullptr;
         }
Member Data Documentation
current
unsigned veins::BaseConnectionManager::CoordSet::current protected
Holds the current element when iterating over this table.
data
std::vector<GridCoord*> veins::BaseConnectionManager::CoordSet::data protected
Holds the hash table.
maxSize
unsigned veins::BaseConnectionManager::CoordSet::maxSize protected
maximum size of the hash table.
size
unsigned veins::BaseConnectionManager::CoordSet::size protected
Current number of entries in the hash table.
The documentation for this class was generated from the following file:
BaseConnectionManager.h