Veins: veins::Decider80211p Class Reference
veins::Decider80211p Class Reference
Based on Decider80211.h from Karl Wessel and modifications by Christopher Saloman.
#include <Decider80211p.h>
Public Types
enum Decider80211ControlKinds { NOTHING = 22100, BITERROR, LAST_DECIDER_80211_CONTROL_KIND, RECWHILESEND }
enum PACKET_OK_RESULT { DECODED, NOT_DECODED, COLLISION }
tell the outcome of a packetOk() call, which might be correctly decoded, discarded due to low SNR or discarder due to low SINR (i.e.
Public Types inherited from veins::BaseDecider
enum BaseDeciderControlKinds { PACKET_DROPPED = 22100, LAST_BASE_DECIDER_CONTROL_KIND }
The kinds of ControlMessages this Decider sends.
Public Member Functions
Decider80211p (cComponent *owner, DeciderToPhyInterface *phy, double minPowerLevel, double ccaThreshold, bool allowTxDuringRx, double centerFrequency, int myIndex=-1, bool collectCollisionStatistics=false)
Initializes the Decider with a pointer to its PhyLayer and specific values for threshold and minPowerLevel.
void setPath (std::string myPath)
bool cca (simtime_t_cref, AirFrame *)
int getSignalState (AirFrame *frame) override
Returns the SignalState for the passed AirFrame.
~Decider80211p () override
void changeFrequency (double freq)
double getCCAThreshold ()
returns the CCA threshold in dBm
void setCCAThreshold (double ccaThreshold_dBm)
sets the CCA threshold
void setChannelIdleStatus (bool isIdle) override
Changes the "isIdle"-status to the passed value.
void finish () override
invoke this method when the phy layer is also finalized, so that statistics recorded by the decider can be written to the output file
void switchToTx () override
Notifies the decider that phy layer is starting a transmission.
void setNotifyRxStart (bool enable)
notify PHY-RXSTART.indication
Public Member Functions inherited from veins::BaseDecider
BaseDecider (cComponent *owner, DeciderToPhyInterface *phy, double minPowerLevel, int myIndex)
Initializes the decider with the passed values.
~BaseDecider () override
simtime_t processSignal (AirFrame *frame) override
Processes an AirFrame given by the PhyLayer.
Public Member Functions inherited from veins::Decider
Decider (cComponent *owner, DeciderToPhyInterface *phy)
Initializes the Decider with a pointer to its PhyLayer.
virtual ~Decider ()
virtual void channelChanged (int newChannel)
Called by phy layer to indicate that the channel this radio currently listens to has changed.
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Member Functions
virtual DeciderResult * checkIfSignalOk (AirFrame *frame)
Checks a mapping against a specific threshold (element-wise).
simtime_t processNewSignal (AirFrame *frame) override
Processes a new Signal.
simtime_t processSignalEnd (AirFrame *frame) override
Processes a received AirFrame.
enum PACKET_OK_RESULT packetOk (double snirMin, double snrMin, int lengthMPDU, double bitrate)
computes if packet is ok or has errors
Protected Member Functions inherited from veins::BaseDecider
virtual simtime_t processSignalHeader (AirFrame *frame)
Processes the end of the header of a received Signal.
virtual simtime_t processUnknownSignal (AirFrame *frame)
Processes any Signal for which no state could be found.
virtual void getChannelInfo (simtime_t_cref start, simtime_t_cref end, AirFrameVector &out)
Collects the AirFrame on the channel during the passed interval.
Protected Attributes
double snrThreshold
double ccaThreshold
Power level threshold used to declare channel busy if preamble portion is missed (802.11-2012 18.3.10.6 CCA requirements).
bool allowTxDuringRx
allows/disallows interruption of current reception for txing
double centerFrequency
The center frequency on which the decider listens for signals.
double myBusyTime
double myStartTime
std::string myPath
Decider80211pToPhy80211pInterface * phy11p
std::map< AirFrame *, int > signalStates
bool collectCollisionStats
enable/disable statistics collection for collisions
unsigned int collisions
count the number of collisions
bool notifyRxStart
notify PHY-RXSTART.indication
Protected Attributes inherited from veins::BaseDecider
double minPowerLevel
minPowerLevel value for receiving an AirFrame
ReceivedSignal currentSignal
pointer to the currently received AirFrame
bool isChannelIdle
Stores the idle state of the channel.
int myIndex
index for this Decider-instance given by Phy-Layer (mostly Host-index)
Protected Attributes inherited from veins::Decider
DeciderToPhyInterface * phy
A pointer to the physical layer of this Decider.
const simtime_t notAgain
simtime that tells the Phy-Layer not to pass an AirFrame again
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Additional Inherited Members
Protected Types inherited from veins::BaseDecider
enum SignalState { NEW, EXPECT_HEADER, EXPECT_END }
The current state of processing for a signal.
typedef std::pair< AirFrame *, int > ReceivedSignal
Pair of a AirFrame and the state it is in.
Protected Types inherited from veins::Decider
using AirFrameVector = DeciderToPhyInterface::AirFrameVector
Defines what an AirFrameVector shall be here.
Detailed Description
Based on Decider80211.h from Karl Wessel and modifications by Christopher Saloman.
Author
David Eckhoff
See also
DemoBaseApplLayer
Mac1609_4
PhyLayer80211p
Decider80211p
Member Enumeration Documentation
Decider80211ControlKinds
enum veins::Decider80211p::Decider80211ControlKinds
Enumerator
NOTHING
BITERROR
LAST_DECIDER_80211_CONTROL_KIND
RECWHILESEND
{
         NOTHING = 22100,
         BITERROR, // the phy has recognized a bit error in the packet
         LAST_DECIDER_80211_CONTROL_KIND,
         RECWHILESEND
     };
PACKET_OK_RESULT
enum veins::Decider80211p::PACKET_OK_RESULT
tell the outcome of a packetOk() call, which might be correctly decoded, discarded due to low SNR or discarder due to low SINR (i.e.
collision)
Enumerator
DECODED
NOT_DECODED
COLLISION
{
         DECODED,
         NOT_DECODED,
         COLLISION
     };
Constructor & Destructor Documentation
Decider80211p()
veins::Decider80211p::Decider80211p (cComponent * owner, DeciderToPhyInterface * phy, double minPowerLevel, double ccaThreshold, bool allowTxDuringRx, double centerFrequency, int myIndex = -1, bool collectCollisionStatistics = false) inline
Initializes the Decider with a pointer to its PhyLayer and specific values for threshold and minPowerLevel.
         : BaseDecider(owner, phy, minPowerLevel, myIndex)
         , ccaThreshold(ccaThreshold)
         , allowTxDuringRx(allowTxDuringRx)
         , centerFrequency(centerFrequency)
         , myBusyTime(0)
         , myStartTime(simTime().dbl())
         , collectCollisionStats(collectCollisionStatistics)
         , collisions(0)
         , notifyRxStart(false)
     {
         phy11p = dynamic_cast<Decider80211pToPhy80211pInterface*>(phy);
         ASSERT(phy11p);
     }
~Decider80211p()
Decider80211p::~Decider80211p () override
 {};
Member Function Documentation
cca()
bool Decider80211p::cca (simtime_t_cref time, AirFrame * exclude)
References ccaThreshold, centerFrequency, veins::BaseDecider::getChannelInfo(), veins::DeciderToPhyInterface::getNoiseFloorValue(), veins::BaseDecider::isChannelIdle, veins::SignalUtils::isChannelPowerBelowThreshold(), and veins::Decider::phy.
Referenced by veins::PhyLayer80211p::handleSelfMessage(), processNewSignal(), processSignalEnd(), and veins::PhyLayer80211p::requestChannelStatusIfIdle().
 {
     AirFrameVector airFrames;
     // collect all AirFrames that intersect with [start, end]
     getChannelInfo(time, time, airFrames);
     // In the reference implementation only centerFrequenvy - 5e6 (half bandwidth) is checked!
     // Although this is wrong, the same is done here to reproduce original results
     double minPower = phy->getNoiseFloorValue();
     bool isChannelIdle = minPower < ccaThreshold;
     if (airFrames.size() > 0) {
         size_t usedFreqIndex = airFrames.front()->getSignal().getSpectrum().indexOf(centerFrequency - 5e6);
         isChannelIdle = SignalUtils::isChannelPowerBelowThreshold(time, airFrames, usedFreqIndex, ccaThreshold - minPower, exclude);
     }
     return isChannelIdle;
 }
changeFrequency()
void Decider80211p::changeFrequency (double freq)
References centerFrequency.
Referenced by veins::PhyLayer80211p::changeListeningChannel().
 {
     centerFrequency = freq;
 }
checkIfSignalOk()
DeciderResult * Decider80211p::checkIfSignalOk (AirFrame * frame) protected virtual
Checks a mapping against a specific threshold (element-wise).
Returns
true , if every entry of the mapping is above threshold false , otherwise
References veins::BANDWIDTH_11P, collectCollisionStats, COLLISION, collisions, DECODED, veins::BaseDecider::getChannelInfo(), veins::SignalUtils::getMinSINR(), veins::DeciderToPhyInterface::getNoiseFloorValue(), veins::getOfdmDatarate(), veins::Signal::getReceptionStart(), NOT_DECODED, packetOk(), veins::Decider::phy, and veins::PHY_HDR_PREAMBLE_DURATION.
Referenced by processSignalEnd().
 {
     auto frame11p = check_and_cast<AirFrame11p*>(frame);
     Signal& s = frame->getSignal();
     simtime_t start = s.getReceptionStart();
     simtime_t end = s.getReceptionEnd();
     // compute receive power
     double recvPower_dBm = 10 * log10(s.getAtCenterFrequency());
     start = start + PHY_HDR_PREAMBLE_DURATION; // its ok if something in the training phase is broken
     AirFrameVector airFrames;
     getChannelInfo(start, end, airFrames);
     double noise = phy->getNoiseFloorValue();
     // Make sure to use the adjusted starting-point (which ignores the preamble)
     double sinrMin = SignalUtils::getMinSINR(start, end, frame, airFrames, noise);
     double snrMin;
     if (collectCollisionStats) {
         // snrMin = SignalUtils::getMinSNR(start, end, frame, noise);
         snrMin = s.getDataMin() / noise;
     }
     else {
         // just set to any value. if collectCollisionStats != true
         // it will be ignored by packetOk
         snrMin = 1e200;
     }
     double payloadBitrate = getOfdmDatarate(static_cast<MCS>(frame11p->getMcs()), BANDWIDTH_11P);
     DeciderResult80211* result = nullptr;
     switch (packetOk(sinrMin, snrMin, frame->getBitLength(), payloadBitrate)) {
     case DECODED:
         EV_TRACE << "Packet is fine! We can decode it" << std::endl;
         result = new DeciderResult80211(true, payloadBitrate, sinrMin, recvPower_dBm, false);
         break;
     case NOT_DECODED:
         if (!collectCollisionStats) {
             EV_TRACE << "Packet has bit Errors. Lost " << std::endl;
         }
         else {
             EV_TRACE << "Packet has bit Errors due to low power. Lost " << std::endl;
         }
         result = new DeciderResult80211(false, payloadBitrate, sinrMin, recvPower_dBm, false);
         break;
     case COLLISION:
         EV_TRACE << "Packet has bit Errors due to collision. Lost " << std::endl;
         collisions++;
         result = new DeciderResult80211(false, payloadBitrate, sinrMin, recvPower_dBm, true);
         break;
     default:
         ASSERT2(false, "Impossible packet result returned by packetOk(). Check the code.");
         break;
     }
     return result;
 }
finish()
void Decider80211p::finish () override virtual
invoke this method when the phy layer is also finalized, so that statistics recorded by the decider can be written to the output file
Reimplemented from veins::Decider.
References collectCollisionStats, collisions, myBusyTime, myStartTime, veins::Decider::phy, and veins::DeciderToPhyInterface::recordScalar().
 {
     simtime_t totalTime = simTime() - myStartTime;
     phy->recordScalar("busyTime", myBusyTime / totalTime.dbl());
     if (collectCollisionStats) {
         phy->recordScalar("ncollisions", collisions);
     }
 }
getCCAThreshold()
double Decider80211p::getCCAThreshold ()
returns the CCA threshold in dBm
References ccaThreshold.
 {
     return 10 * log10(ccaThreshold);
 }
getSignalState()
int Decider80211p::getSignalState (AirFrame * frame) override virtual
Returns the SignalState for the passed AirFrame.
The default implementation checks if the passed AirFrame is the "currentSignal" and returns its state or if not "NEW".
Reimplemented from veins::BaseDecider.
References veins::BaseDecider::NEW, and signalStates.
 {
     if (signalStates.find(frame) == signalStates.end()) {
         return NEW;
     }
     else {
         return signalStates[frame];
     }
 }
packetOk()
enum Decider80211p::PACKET_OK_RESULT Decider80211p::packetOk (double snirMin, double snrMin, int lengthMPDU, double bitrate) protected
computes if packet is ok or has errors
References veins::BANDWIDTH_11P, collectCollisionStats, COLLISION, DECODED, veins::NistErrorRate::getChunkSuccessRate(), NOT_DECODED, veins::PHY_HDR_BITRATE, veins::PHY_HDR_PLCPSIGNAL_LENGTH, veins::PHY_HDR_SERVICE_LENGTH, veins::PHY_TAIL_LENGTH, and RNGCONTEXT.
Referenced by checkIfSignalOk().
 {
     double packetOkSinr;
     double packetOkSnr;
     // compute success rate depending on mcs and bw
     packetOkSinr = NistErrorRate::getChunkSuccessRate(bitrate, BANDWIDTH_11P, sinrMin, PHY_HDR_SERVICE_LENGTH + lengthMPDU + PHY_TAIL_LENGTH);
     // check if header is broken
     double headerNoError = NistErrorRate::getChunkSuccessRate(PHY_HDR_BITRATE, BANDWIDTH_11P, sinrMin, PHY_HDR_PLCPSIGNAL_LENGTH);
     double headerNoErrorSnr;
     // compute PER also for SNR only
     if (collectCollisionStats) {
         packetOkSnr = NistErrorRate::getChunkSuccessRate(bitrate, BANDWIDTH_11P, snrMin, PHY_HDR_SERVICE_LENGTH + lengthMPDU + PHY_TAIL_LENGTH);
         headerNoErrorSnr = NistErrorRate::getChunkSuccessRate(PHY_HDR_BITRATE, BANDWIDTH_11P, snrMin, PHY_HDR_PLCPSIGNAL_LENGTH);
         // the probability of correct reception without considering the interference
         // MUST be greater or equal than when consider it
         ASSERT(packetOkSnr >= packetOkSinr);
         ASSERT(headerNoErrorSnr >= headerNoError);
     }
     // probability of no bit error in the PLCP header
     double rand = RNGCONTEXT dblrand();
     if (!collectCollisionStats) {
         if (rand > headerNoError) return NOT_DECODED;
     }
     else {
         if (rand > headerNoError) {
             // ups, we have a header error. is that due to interference?
             if (rand > headerNoErrorSnr) {
                 // no. we would have not been able to receive that even
                 // without interference
                 return NOT_DECODED;
             }
             else {
                 // yes. we would have decoded that without interference
                 return COLLISION;
             }
         }
     }
     // probability of no bit error in the rest of the packet
     rand = RNGCONTEXT dblrand();
     if (!collectCollisionStats) {
         if (rand > packetOkSinr) {
             return NOT_DECODED;
         }
         else {
             return DECODED;
         }
     }
     else {
         if (rand > packetOkSinr) {
             // ups, we have an error in the payload. is that due to interference?
             if (rand > packetOkSnr) {
                 // no. we would have not been able to receive that even
                 // without interference
                 return NOT_DECODED;
             }
             else {
                 // yes. we would have decoded that without interference
                 return COLLISION;
             }
         }
         else {
             return DECODED;
         }
     }
 }
processNewSignal()
simtime_t Decider80211p::processNewSignal (AirFrame * frame) override protected virtual
Processes a new Signal.
Returns the time it wants to handle the signal again.
Default implementation checks if the signals receiving power is above the minPowerLevel of the radio and we are not already trying to receive another AirFrame. If thats the case it waits for the end of the signal.
Reimplemented from veins::BaseDecider.
References cca(), veins::BaseDecider::currentSignal, veins::BaseDecider::EXPECT_END, veins::Decider80211pToPhy80211pInterface::getRadioState(), veins::BaseDecider::minPowerLevel, myBusyTime, notifyRxStart, veins::Decider::phy, phy11p, veins::MacToPhyInterface::PHY_RX_START, veins::DeciderToPhyInterface::sendControlMsgToMac(), setChannelIdleStatus(), signalStates, and veins::Radio::TX.
 {
     AirFrame11p* frame = check_and_cast<AirFrame11p*>(msg);
     // get the receiving power of the Signal at start-time and center frequency
     Signal& signal = frame->getSignal();
     signalStates[frame] = EXPECT_END;
     if (signal.smallerAtCenterFrequency(minPowerLevel)) {
         // annotate the frame, so that we won't try decoding it at its end
         frame->setUnderMinPowerLevel(true);
         // check channel busy status. a superposition of low power frames might turn channel status to busy
         if (cca(simTime(), nullptr) == false) {
             setChannelIdleStatus(false);
         }
         return signal.getReceptionEnd();
     }
     else {
         // This value might be just an intermediate result (due to short circuiting)
         double recvPower = signal.getAtCenterFrequency();
         setChannelIdleStatus(false);
         if (phy11p->getRadioState() == Radio::TX) {
             frame->setBitError(true);
             frame->setWasTransmitting(true);
             EV_TRACE << "AirFrame: " << frame->getId() << " (" << recvPower << ") received, while already sending. Setting BitErrors to true" << std::endl;
         }
         else {
             if (!currentSignal.first) {
                 // NIC is not yet synced to any frame, so lock and try to decode this frame
                 currentSignal.first = frame;
                 EV_TRACE << "AirFrame: " << frame->getId() << " with (" << recvPower << " > " << minPowerLevel << ") -> Trying to receive AirFrame." << std::endl;
                 if (notifyRxStart) {
                     phy->sendControlMsgToMac(new cMessage("RxStartStatus", MacToPhyInterface::PHY_RX_START));
                 }
             }
             else {
                 // NIC is currently trying to decode another frame. this frame will be simply treated as interference
                 EV_TRACE << "AirFrame: " << frame->getId() << " with (" << recvPower << " > " << minPowerLevel << ") -> Already synced to another AirFrame. Treating AirFrame as interference." << std::endl;
             }
             // channel turned busy
             // measure communication density
             myBusyTime += signal.getDuration().dbl();
         }
         return signal.getReceptionEnd();
     }
 }
processSignalEnd()
simtime_t Decider80211p::processSignalEnd (AirFrame * frame) override protected virtual
Processes a received AirFrame.
The SNR-mapping for the Signal is created and checked against the Deciders SNR-threshold. Depending on that the received AirFrame is either sent up to the MAC-Layer or dropped.
Returns
usually return a value for: 'do not pass it again'
Reimplemented from veins::BaseDecider.
References BITERROR, cca(), checkIfSignalOk(), COLLISION, veins::BaseDecider::currentSignal, veins::Decider80211pToPhy80211pInterface::getRadioState(), veins::BaseDecider::isChannelIdle, veins::DeciderResult::isSignalCorrect(), veins::Decider::notAgain, notifyRxStart, veins::Decider::phy, phy11p, veins::MacToPhyInterface::PHY_RX_END_WITH_FAILURE, veins::MacToPhyInterface::PHY_RX_END_WITH_SUCCESS, RECWHILESEND, veins::DeciderToPhyInterface::sendControlMsgToMac(), veins::DeciderToPhyInterface::sendUp(), setChannelIdleStatus(), signalStates, and veins::Radio::TX.
 {
     AirFrame11p* frame = check_and_cast<AirFrame11p*>(msg);
     // here the Signal is finally processed
     Signal& signal = frame->getSignal();
     double recvPower_dBm = 10 * log10(signal.getMax());
     bool whileSending = false;
     // remove this frame from our current signals
     signalStates.erase(frame);
     DeciderResult* result;
     if (frame->getUnderMinPowerLevel()) {
         // this frame was not even detected by the radio card
         result = new DeciderResult80211(false, 0, 0, recvPower_dBm);
     }
     else if (frame->getWasTransmitting() || phy11p->getRadioState() == Radio::TX) {
         // this frame was received while sending
         whileSending = true;
         result = new DeciderResult80211(false, 0, 0, recvPower_dBm);
     }
     else {
         // first check whether this is the frame NIC is currently synced on
         if (frame == currentSignal.first) {
             // check if the snr is above the Decider's specific threshold,
             // i.e. the Decider has received it correctly
             result = checkIfSignalOk(frame);
             // after having tried to decode the frame, the NIC is no more synced to the frame
             // and it is ready for syncing on a new one
             currentSignal.first = 0;
         }
         else {
             // if this is not the frame we are synced on, we cannot receive it
             result = new DeciderResult80211(false, 0, 0, recvPower_dBm);
         }
     }
     if (result->isSignalCorrect()) {
         EV_TRACE << "packet was received correctly, it is now handed to upper layer...\n";
         // go on with processing this AirFrame, send it to the Mac-Layer
         if (notifyRxStart) {
             phy->sendControlMsgToMac(new cMessage("RxStartStatus", MacToPhyInterface::PHY_RX_END_WITH_SUCCESS));
         }
         phy->sendUp(frame, result);
     }
     else {
         if (frame->getUnderMinPowerLevel()) {
             EV_TRACE << "packet was not detected by the card. power was under minPowerLevel threshold\n";
         }
         else if (whileSending) {
             EV_TRACE << "packet was received while sending, sending it as control message to upper layer\n";
             phy->sendControlMsgToMac(new cMessage("Error", RECWHILESEND));
         }
         else {
             EV_TRACE << "packet was not received correctly, sending it as control message to upper layer\n";
             if (notifyRxStart) {
                 phy->sendControlMsgToMac(new cMessage("RxStartStatus", MacToPhyInterface::PHY_RX_END_WITH_FAILURE));
             }
             if (((DeciderResult80211*) result)->isCollision()) {
                 phy->sendControlMsgToMac(new cMessage("Error", Decider80211p::COLLISION));
             }
             else {
                 phy->sendControlMsgToMac(new cMessage("Error", BITERROR));
             }
         }
         delete result;
     }
     if (phy11p->getRadioState() == Radio::TX) {
         EV_TRACE << "I'm currently sending\n";
     }
     // check if channel is idle now
     // we declare channel busy if CCA tells us so, or if we are currently
     // decoding a frame
     else if (cca(simTime(), frame) == false || currentSignal.first != 0) {
         EV_TRACE << "Channel not yet idle!\n";
     }
     else {
         // might have been idle before (when the packet rxpower was below sens)
         if (isChannelIdle != true) {
             EV_TRACE << "Channel idle now!\n";
             setChannelIdleStatus(true);
         }
     }
     return notAgain;
 }
setCCAThreshold()
void Decider80211p::setCCAThreshold (double ccaThreshold_dBm)
sets the CCA threshold
References ccaThreshold.
Referenced by veins::PhyLayer80211p::setCCAThreshold().
 {
     ccaThreshold = pow(10, ccaThreshold_dBm / 10);
 }
setChannelIdleStatus()
void Decider80211p::setChannelIdleStatus (bool isIdle) override virtual
Changes the "isIdle"-status to the passed value.
Reimplemented from veins::BaseDecider.
References veins::Mac80211pToPhy11pInterface::CHANNEL_BUSY, veins::Mac80211pToPhy11pInterface::CHANNEL_IDLE, veins::BaseDecider::isChannelIdle, veins::Decider::phy, and veins::DeciderToPhyInterface::sendControlMsgToMac().
Referenced by veins::PhyLayer80211p::handleSelfMessage(), processNewSignal(), processSignalEnd(), and veins::PhyLayer80211p::requestChannelStatusIfIdle().
 {
     isChannelIdle = isIdle;
     if (isIdle)
         phy->sendControlMsgToMac(new cMessage("ChannelStatus", Mac80211pToPhy11pInterface::CHANNEL_IDLE));
     else
         phy->sendControlMsgToMac(new cMessage("ChannelStatus", Mac80211pToPhy11pInterface::CHANNEL_BUSY));
 }
setNotifyRxStart()
void Decider80211p::setNotifyRxStart (bool enable)
notify PHY-RXSTART.indication
References notifyRxStart.
Referenced by veins::PhyLayer80211p::notifyMacAboutRxStart().
 {
     notifyRxStart = enable;
 }
setPath()
void veins::Decider80211p::setPath (std::string myPath) inline
     {
         this->myPath = myPath;
     }
switchToTx()
void Decider80211p::switchToTx () override virtual
Notifies the decider that phy layer is starting a transmission.
This helps the decider interrupting a current reception. In a standard 802.11 MAC, this should never happen, but in other MAC layers you might decide to interrupt an ongoing reception and start transmitting. Thank to this method, the decider can flag the ongoing frame as non received because of the transmission.
Reimplemented from veins::Decider.
References allowTxDuringRx, and veins::BaseDecider::currentSignal.
 {
     if (currentSignal.first != 0) {
         // we are currently trying to receive a frame.
         if (allowTxDuringRx) {
             // if the above layer decides to transmit anyhow, we need to abort reception
             AirFrame11p* currentFrame = dynamic_cast<AirFrame11p*>(currentSignal.first);
             ASSERT(currentFrame);
             // flag the frame as "while transmitting"
             currentFrame->setWasTransmitting(true);
             currentFrame->setBitError(true);
             // forget about the signal
             currentSignal.first = 0;
         }
         else {
             throw cRuntimeError("Decider80211p: mac layer requested phy to transmit a frame while currently receiving another");
         }
     }
 }
Member Data Documentation
allowTxDuringRx
bool veins::Decider80211p::allowTxDuringRx protected
allows/disallows interruption of current reception for txing
For a standard 802.11 MAC, starting a transmission while currently receiving a frame is forbidden, as the channel is in a BUSY state. For research purposes, however, one might use a custom MAC layer on top of an 802.11p OFDM PHY, and decide to interrupt an ongoing reception to start a transmission, whatever the reason. If the following variable is set to false, simulation will be terminated if this occurs. If not, simulation will continue, aborting current reception.
Referenced by switchToTx().
ccaThreshold
double veins::Decider80211p::ccaThreshold protected
Power level threshold used to declare channel busy if preamble portion is missed (802.11-2012 18.3.10.6 CCA requirements).
Notice that in 18.3.10.6, the mandatory CCA threshold for a 10 MHz channel is -65 dBm. However, there is another threshold called CCA-ED which requirements are defined in D.2.5. For a 10 MHz channel, CCA-ED threshold shall be -75 dBm. CCA-ED is required for certain operating classes that shall implement CCA-ED behavior. According to Table E-4 however, 802.11p channels should not implement it, so the correct threshold is -65 dBm. When considering ETSI ITS G5 (ETSI TS 102 687) things change again. Indeed, the DCC Sensitivity Control (DSC) part of the DCC algorithm changes the CCA threshold depending on the state. Values are listed in Table A.3: minimum value is -95 dBm, maximum value is -65 dBm, and default value is -85 dBm.
Referenced by cca(), getCCAThreshold(), and setCCAThreshold().
centerFrequency
double veins::Decider80211p::centerFrequency protected
The center frequency on which the decider listens for signals.
Referenced by cca(), and changeFrequency().
collectCollisionStats
bool veins::Decider80211p::collectCollisionStats protected
enable/disable statistics collection for collisions
For collecting statistics about collisions, we compute the Packet Error Rate for both SNR and SINR values. This might increase the simulation time, so if statistics about collisions are not needed, this variable should be set to false
Referenced by checkIfSignalOk(), finish(), and packetOk().
collisions
unsigned int veins::Decider80211p::collisions protected
count the number of collisions
Referenced by checkIfSignalOk(), and finish().
myBusyTime
double veins::Decider80211p::myBusyTime protected
Referenced by finish(), and processNewSignal().
myPath
std::string veins::Decider80211p::myPath protected
myStartTime
double veins::Decider80211p::myStartTime protected
Referenced by finish().
notifyRxStart
bool veins::Decider80211p::notifyRxStart protected
notify PHY-RXSTART.indication
Referenced by processNewSignal(), processSignalEnd(), and setNotifyRxStart().
phy11p
Decider80211pToPhy80211pInterface* veins::Decider80211p::phy11p protected
Referenced by processNewSignal(), and processSignalEnd().
signalStates
std::map<AirFrame*, int> veins::Decider80211p::signalStates protected
Referenced by getSignalState(), processNewSignal(), and processSignalEnd().
snrThreshold
double veins::Decider80211p::snrThreshold protected
The documentation for this class was generated from the following files:
Decider80211p.h
Decider80211p.cc