Veins: veins::BasePhyLayer Class Reference
veins::BasePhyLayer Class Reference
The BasePhyLayer represents the physical layer of a nic.
#include <BasePhyLayer.h>
Public Member Functions
~BasePhyLayer () override
void finish () override
Call the deciders finish method.
MacToPhyInterface implementation
These methods implement the MacToPhyInterface.
int getRadioState () override
Return the current state the radio is in.
simtime_t setRadioState (int rs) override
Tell the BasePhyLayer to switch to the specified radio state.
void setCurrentRadioChannel (int newRadioChannel) override
Set the channel currently used by the radio.
int getCurrentRadioChannel () override
Return the channel currently used by the radio.
int getNbRadioChannels () override
Return the number of channels available on this radio.
DeciderToPhyInterface implementation
These methods implement the DeciderToPhyInterface.
void getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector &out) override
Fill the given AirFrameVector with all AirFrames that intersect with the given time interval.
double getNoiseFloorValue () override
Return noise floor level (in mW).
void sendControlMsgToMac (cMessage *msg) override
Send the given message to via the control gate to the mac.
void sendUp (AirFrame *packet, DeciderResult *result) override
Pass the given packet along with the result up to the mac.
BaseWorldUtility * getWorldUtility () override
Return a pointer to the simulations world-utility-module.
void recordScalar (const char *name, double value, const char *unit=nullptr) override
Record a double into the scalar result file.
Public Member Functions inherited from veins::ChannelAccess
void initialize (int stage) override
Register with ConnectionManager.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Called by the signalling mechanism to inform of changes.
virtual ChannelMobilityPtrType getMobilityModule ()
Returns the host's mobility module.
virtual AntennaPosition getAntennaPosition () const
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Public Member Functions inherited from veins::DeciderToPhyInterface
virtual ~DeciderToPhyInterface ()
Public Member Functions inherited from veins::MacToPhyInterface
virtual ~MacToPhyInterface ()
Protected Types
enum AirFrameState { AirFrameState::start_receive = 1, AirFrameState::receiving, AirFrameState::end_receive }
The states of the receiving process for AirFrames.
enum ProtocolIds { PROTOCOL_ID_GENERIC = 0 }
using ParameterMap = std::map< std::string, cMsgPar >
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Protected Types inherited from veins::AccessModuleWrap< T >
using wrapType = T
Protected Member Functions
template<class T >
T readPar (const char *parName, const T defaultValue)
Read and return the parameter with the passed name.
void initialize (int stage) override
Initialize members and associated objects according to parameterization.
void handleMessage (cMessage *msg) override
Process received messages and pass to specific handlers.
virtual std::unique_ptr< Radio > initializeRadio ()
Create and return the radio class to use.
virtual std::unique_ptr< AnalogueModel > getAnalogueModelFromName (std::string name, ParameterMap &params)
Create and return an instance of the AnalogueModel with the specified name.
virtual std::unique_ptr< Decider > getDeciderFromName (std::string name, ParameterMap &params)
Create and return an instance of the Decider with the specified name.
virtual std::shared_ptr< Antenna > getAntennaFromName (std::string name, ParameterMap &params)
Create and return an instance of the Antenna with the specified name as a shared pointer.
virtual std::shared_ptr< Antenna > initializeSampledAntenna1D (ParameterMap &params)
Creates and returns an instance of the SampledAntenna1D class as a shared pointer.
virtual std::unique_ptr< AirFrame > createAirFrame (cPacket *macPkt)
Create a protocol-specific AirFrame.
virtual void attachSignal (AirFrame *airFrame, cObject *ctrlInfo)
Create a signal corresponding to the received control information.
virtual std::unique_ptr< AirFrame > encapsMsg (cPacket *msg)
Encapsulate messages from the upper layer into an AirFrame and set all necessary attributes.
virtual void filterSignal (AirFrame *frame)
Filter the passed AirFrame's Signal by every registered AnalogueModel.
virtual void finishRadioSwitching ()
Called when the switching process of the Radio is finished.
virtual int myProtocolId ()
Return the identifier of the protocol this phy uses to send messages.
virtual bool isKnownProtocolId (int id)
Return whether the protocol with the passed identifier is decodeable by the decider.
Handle Messages
virtual void handleAirFrame (AirFrame *frame)
Handle messages received from the channel.
virtual void handleUpperMessage (cMessage *msg)
Handle messages received from the upper layer and start transmitting them.
virtual void handleUpperControlMessage (cMessage *msg)
Handle messages received from the upper layer through the control gate.
virtual void handleSelfMessage (cMessage *msg)
Handle self scheduled messages.
virtual void handleAirFrameStartReceive (AirFrame *msg)
Handle incoming AirFrames with the state AirFrameState::start_receive.
virtual void handleAirFrameReceiving (AirFrame *msg)
Handle incoming AirFrames with the state AirFrameState::receiving.
virtual void handleAirFrameEndReceive (AirFrame *msg)
Handle incoming AirFrames with the state AirFrameState::end_receive.
Send Messages
void sendControlMessageUp (cMessage *msg)
Send the passed control message to the upper layer.
void sendMacPktUp (cMessage *pkt)
Send the passed MacPkt to the upper layer.
void sendMessageDown (AirFrame *pkt)
Send the passed AirFrame to the channel.
void sendSelfMessage (cMessage *msg, simtime_t_cref time)
Schedule self message to passed point in time.
Protected Member Functions inherited from veins::ChannelAccess
simtime_t calculatePropagationDelay (const NicEntry *nic)
Calculates the propagation delay to the passed receiving nic.
void sendToChannel (cPacket *msg)
Sends a message to all nics connected to this one.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Member Functions inherited from veins::AccessModuleWrap< T >
AccessModuleWrap ()
T *const get (cModule *const from=nullptr)
Static Protected Member Functions
static short airFramePriority ()
Defines the scheduling priority of AirFrames.
Protected Attributes
int protocolId = PROTOCOL_ID_GENERIC
The ID of the protocol this phy can transceive.
double noiseFloorValue = 0
Catch-all for all factors negatively impacting SINR (e.g., thermal noise, noise figure, ...)
double minPowerLevel
The minimum receive power needed to even attempt decoding a frame.
bool recordStats
Stores if tracking of statistics (esp. cOutvectors) is enabled.
ChannelInfo channelInfo
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
std::unique_ptr< Radio > radio
The state machine storing the current radio state (TX, RX, SLEEP).
std::shared_ptr< Antenna > antenna
Shared pointer to the Antenna used for this node.
std::unique_ptr< Decider > decider
Pointer to the decider module.
AnalogueModelList analogueModels
The analogue models to use which might attenuate or amplify a signal.
AnalogueModelList analogueModelsThresholding
The analogue models to use which will only attenuate a signal.
int upperLayerIn
The id of the in-data gate from the Mac layer.
int upperLayerOut
The id of the out-data gate to the Mac layer.
int upperControlOut
The id of the out-control gate to the Mac layer.
int upperControlIn
The id of the in-control gate from the Mac layer.
cMessage * radioSwitchingOverTimer = nullptr
Self message scheduled to the point in time when the switching process of the radio is over.
cMessage * txOverTimer = nullptr
Self message scheduled to the point in time when the transmission of an AirFrame is over.
BaseWorldUtility * world = nullptr
Pointer to the World Utility, to obtain some global information.
Spectrum overallSpectrum
The underlying spectrum (definition of interesting freqs) for all signals.
Protected Attributes inherited from veins::ChannelAccess
bool useSendDirect
use sendDirect or not?
BaseConnectionManager * cc
Pointer to the PropagationModel module.
bool usePropagationDelay
Defines if the physical layer should simulate propagation delay.
bool isRegistered
Is this module already registered with ConnectionManager?
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
AntennaPosition antennaPosition
Current antenna position.
Heading antennaHeading
Current antenna heading (angle)
Coord antennaOffset = Coord(0, 0, 0)
Offset of antenna position (in m) with respect to what a BaseMobility module will tell us.
double antennaOffsetYaw = 0
Offset of antenna orientation (yaw, in rad) with respect to what a BaseMobility module will tell us.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Private Member Functions
void getParametersFromXML (cXMLElement *xmlData, ParameterMap &outputMap)
Read the parameters of a XML element and stores them in the passed ParameterMap reference.
void initializeAnalogueModels (cXMLElement *xmlConfig)
Initialize the AnalogueModels with the data from the passed XML-config data.
void initializeDecider (cXMLElement *xmlConfig)
Initialize the Decider with the data from the passed XML-config data.
void initializeAntenna (cXMLElement *xmlConfig)
Initialize the Antenna with the data from the passed XML-config data.
Additional Inherited Members
Public Types inherited from veins::DeciderToPhyInterface
using AirFrameVector = std::list< AirFrame * >
Type for container of AirFrames.
Public Types inherited from veins::MacToPhyInterface
enum BasePhyMessageKinds {
TX_OVER = 22000, RADIO_SWITCHING_OVER, AIR_FRAME, PHY_RX_START,
PHY_RX_END_WITH_SUCCESS, PHY_RX_END_WITH_FAILURE, LAST_BASE_PHY_KIND
}
Message kinds used by every phy layer.
Static Public Member Functions inherited from veins::ChannelAccess
static BaseConnectionManager * getConnectionManager (cModule *nic)
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
The BasePhyLayer represents the physical layer of a nic.
The BasePhyLayer is directly connected to the mac layer via OMNeT channels and is able to send messages to other physical layers through sub-classing from ChannelAcces. In order to implement a physical layer, subclass the BasePhyLayer and override these methods:
initializeRadio
getAnalogueModelFromName
getDeciderFromName
createAirFrame
attachSignal
The BasePhyLayer encapsulates three sub modules: The AnalogueModels, which are responsible for simulating the attenuation of received signals, and the Decider, which provides the main functionality of the physical layer like signal classification (noise or not noise) and demodulation (calculating transmission errors). Furthermore, the Antenna used for gain calculation is managed by the BasePhyLayer.
The BasePhyLayer itself is responsible for the OMNeT depended parts of the physical layer which are the following:
Module initialization:
read ned-parameters and initialize module, Decider, AnalogueModels and Antenna
Message handling:
receive messages from mac layer and hand them to the Decider or directly send them to the channel
receive AirFrames from the channel, hand them to the AnalogueModels for filtering, simulate delay and transmission duration, hand it to the Decider for evaluation and send received packets to the mac layer
keep track of currently active AirFrames on the channel (see ChannelInfo)
The actual evaluation of incoming signals is done by the Decider.
base class ChannelAccess:
provides access to the channel via the ConnectionManager
base class DeciderToPhyInterface:
interface for the Decider
base class MacToPhyInterface:
interface for the Mac
Member Typedef Documentation
ParameterMap
using veins::BasePhyLayer::ParameterMap = std::map<std::string, cMsgPar> protected
Used at initialisation to pass the parameters to the AnalogueModel and Decider.
Member Enumeration Documentation
AirFrameState
enum veins::BasePhyLayer::AirFrameState strong protected
The states of the receiving process for AirFrames.
Enumerator
start_receive
Start of actual receiving process of the AirFrame.
receiving
AirFrame is being received.
end_receive
Receiving process over.
{
         start_receive = 1, ///< Start of actual receiving process of the AirFrame.
         receiving, ///< AirFrame is being received.
         end_receive ///< Receiving process over.
     };
ProtocolIds
enum veins::BasePhyLayer::ProtocolIds protected
Enumerator
PROTOCOL_ID_GENERIC
                      {
         PROTOCOL_ID_GENERIC = 0,
     };
Constructor & Destructor Documentation
~BasePhyLayer()
BasePhyLayer::~BasePhyLayer () override
References channelInfo, veins::ChannelInfo::getAirFrames(), radioSwitchingOverTimer, and txOverTimer.
 {
     // get AirFrames from ChannelInfo and delete
     // (although ChannelInfo normally owns the AirFrames it
     // is not able to cancel and delete them itself
     AirFrameVector channel;
     channelInfo.getAirFrames(0, simTime(), channel);
     for (AirFrameVector::iterator it = channel.begin(); it != channel.end(); ++it) {
         cancelAndDelete(*it);
     }
     // free timer messages
     if (txOverTimer) {
         cancelAndDelete(txOverTimer);
         txOverTimer = nullptr;
     }
     if (radioSwitchingOverTimer) {
         cancelAndDelete(radioSwitchingOverTimer);
         radioSwitchingOverTimer = nullptr;
     }
 }
Member Function Documentation
airFramePriority()
static short veins::BasePhyLayer::airFramePriority () inline static protected
Defines the scheduling priority of AirFrames.
AirFrames use a slightly higher priority than normal to ensure channel consistency. This means that before anything else happens at a time point t every AirFrame which ended at t has been removed and every AirFrame started at t has been added to the channel.
Referenced by encapsMsg().
     {
         return 10;
     }
attachSignal()
virtual void veins::BasePhyLayer::attachSignal (AirFrame * airFrame, cObject * ctrlInfo) inline protected virtual
Create a signal corresponding to the received control information.
Reimplemented in veins::PhyLayer80211p.
Referenced by encapsMsg().
     {
         throw cRuntimeError("Not implemented in the BasePhyLayer. Override in subclass.");
     }
createAirFrame()
unique_ptr< AirFrame > BasePhyLayer::createAirFrame (cPacket * macPkt) protected virtual
Create a protocol-specific AirFrame.
Reimplemented in veins::PhyLayer80211p.
References veins::MacToPhyInterface::AIR_FRAME.
Referenced by encapsMsg().
 {
     return make_unique<AirFrame>(macPkt->getName(), AIR_FRAME);
 }
encapsMsg()
unique_ptr< AirFrame > BasePhyLayer::encapsMsg (cPacket * msg) protected virtual
Encapsulate messages from the upper layer into an AirFrame and set all necessary attributes.
References airFramePriority(), attachSignal(), createAirFrame(), veins::BaseWorldUtility::getUniqueAirFrameId(), myProtocolId(), radio, and world.
Referenced by handleUpperMessage().
 {
     // the cMessage passed must be a MacPacket... but no cast needed here
     // MacPkt* pkt = static_cast<MacPkt*>(msg);
     // ...and must always have a ControlInfo attached (contains Signal)
     auto ctrlInfo = unique_ptr<cObject>(macPkt->removeControlInfo());
     ASSERT(ctrlInfo);
     // create the new AirFrame
     auto frame = createAirFrame(macPkt);
     // set the members
     // set priority of AirFrames above the normal priority to ensure
     // channel consistency (before any thing else happens at a time
     // point t make sure that the channel has removed every AirFrame
     // ended at t and added every AirFrame started at t)
     frame->setSchedulingPriority(airFramePriority());
     frame->setProtocolId(myProtocolId());
     frame->setId(world->getUniqueAirFrameId());
     frame->setChannel(radio->getCurrentChannel());
     frame->setBitLength(0); // as the PHY might mix multiple different encoding rates (and things that might not be bits at all)
     frame->encapsulate(macPkt);
     // attach the spectrum-dependent Signal to the airFrame
     attachSignal(frame.get(), ctrlInfo.get());
     // --- from here on, the AirFrame is the owner of the MacPacket ---
     macPkt = nullptr;
     EV_TRACE << "AirFrame encapsulated, length: " << frame->getBitLength() << "\n";
     return frame;
 }
filterSignal()
void BasePhyLayer::filterSignal (AirFrame * frame) protected virtual
Filter the passed AirFrame's Signal by every registered AnalogueModel.
Moreover, the antenna gains are calculated and added to the signal.
Note
Only models from analogueModels are applied. Those referenced in analogueModelsThresholding are passed to the Signal to enable more efficient handling.
See also
analogueModels
analogueModelsThresholding
References analogueModels, analogueModelsThresholding, veins::POA::antenna, antenna, veins::ChannelAccess::antennaHeading, veins::ChannelAccess::antennaPosition, veins::AntennaPosition::getPositionAt(), veins::POA::orientation, veins::POA::pos, veins::Signal::setAnalogueModelList(), veins::Signal::setReceiverPoa(), veins::Signal::setSenderPoa(), and veins::Heading::toCoord().
Referenced by handleAirFrameStartReceive().
 {
     ASSERT(dynamic_cast<ChannelAccess* const>(frame->getArrivalModule()) == this);
     ASSERT(dynamic_cast<ChannelAccess* const>(frame->getSenderModule()));
     Signal& signal = frame->getSignal();
     // Extract position and orientation of sender and receiver (this module) first
     const AntennaPosition receiverPosition = antennaPosition;
     const Coord receiverOrientation = antennaHeading.toCoord();
     // get POA from frame with the sender's position, orientation and antenna
     POA& senderPOA = frame->getPoa();
     const AntennaPosition senderPosition = senderPOA.pos;
     const Coord senderOrientation = senderPOA.orientation;
     // add position information to signal
     signal.setSenderPoa(senderPOA);
     signal.setReceiverPoa({receiverPosition, receiverOrientation, antenna});
     // compute gains at sender and receiver antenna
     double receiverGain = antenna->getGain(receiverPosition.getPositionAt(), receiverOrientation, senderPosition.getPositionAt());
     double senderGain = senderPOA.antenna->getGain(senderPosition.getPositionAt(), senderOrientation, receiverPosition.getPositionAt());
     // add the resulting total gain to the attenuations list
     EV_TRACE << "Sender's antenna gain: " << senderGain << endl;
     EV_TRACE << "Own (receiver's) antenna gain: " << receiverGain << endl;
     signal *= receiverGain * senderGain;
     // go on with AnalogueModels
     // attach analogue models suitable for thresholding to signal (for later evaluation)
     signal.setAnalogueModelList(&analogueModelsThresholding);
     // apply all analouge models that are *not* suitable for thresholding now
     for (auto& analogueModel : analogueModels) {
         analogueModel->filterSignal(&signal);
     }
 }
finish()
void BasePhyLayer::finish () override
Call the deciders finish method.
References decider.
 {
     // give decider the chance to do something
     decider->finish();
 }
finishRadioSwitching()
void BasePhyLayer::finishRadioSwitching () protected virtual
Called when the switching process of the Radio is finished.
The default implementation sends a confirmation message to the mac layer.
See also
MacToPhyInterface::RADIO_SWITCHING_OVER
References radio, veins::MacToPhyInterface::RADIO_SWITCHING_OVER, and sendControlMsgToMac().
Referenced by veins::PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), and setRadioState().
 {
     radio->endSwitch(simTime());
     sendControlMsgToMac(new cMessage("Radio switching over", RADIO_SWITCHING_OVER));
 }
getAnalogueModelFromName()
virtual std::unique_ptr<AnalogueModel> veins::BasePhyLayer::getAnalogueModelFromName (std::string name, ParameterMap & params) inline protected virtual
Create and return an instance of the AnalogueModel with the specified name.
This method is used by the BasePhyLayer during initialisation to load the AnalogueModels which has been specified in the NED file.
Reimplemented in veins::PhyLayer80211p.
Referenced by veins::PhyLayer80211p::getAnalogueModelFromName(), and initializeAnalogueModels().
     {
         return nullptr;
     }
getAntennaFromName()
std::shared_ptr< Antenna > BasePhyLayer::getAntennaFromName (std::string name, ParameterMap & params) protected virtual
Create and return an instance of the Antenna with the specified name as a shared pointer.
This method is called during initialization to load the Antenna specified. If no special antenna has been specified, an object of the base Antenna class is instantiated, representing an isotropic antenna.
References initializeSampledAntenna1D().
Referenced by initializeAntenna().
 {
     if (name == "SampledAntenna1D") {
         return initializeSampledAntenna1D(params);
     }
     return std::make_shared<Antenna>();
 }
getChannelInfo()
void BasePhyLayer::getChannelInfo (simtime_t_cref from, simtime_t_cref to, AirFrameVector & out) override virtual
Fill the given AirFrameVector with all AirFrames that intersect with the given time interval.
Implements veins::DeciderToPhyInterface.
References channelInfo, and veins::ChannelInfo::getAirFrames().
 {
     channelInfo.getAirFrames(from, to, out);
 }
getCurrentRadioChannel()
int BasePhyLayer::getCurrentRadioChannel () override virtual
Return the channel currently used by the radio.
Implements veins::DeciderToPhyInterface.
References radio.
 {
     return radio->getCurrentChannel();
 }
getDeciderFromName()
unique_ptr< Decider > BasePhyLayer::getDeciderFromName (std::string name, ParameterMap & params) protected virtual
Create and return an instance of the Decider with the specified name.
This method is used by the BasePhyLayer during initialisation to load the Decider which has been specified in the ned file.
Reimplemented in veins::PhyLayer80211p.
Referenced by veins::PhyLayer80211p::getDeciderFromName(), and initializeDecider().
 {
     return nullptr;
 }
getNbRadioChannels()
int BasePhyLayer::getNbRadioChannels () override virtual
Return the number of channels available on this radio.
Implements veins::MacToPhyInterface.
 {
     return par("nbRadioChannels");
 }
getNoiseFloorValue()
double BasePhyLayer::getNoiseFloorValue () override virtual
Return noise floor level (in mW).
Implements veins::DeciderToPhyInterface.
References noiseFloorValue.
 {
     return noiseFloorValue;
 }
getParametersFromXML()
void BasePhyLayer::getParametersFromXML (cXMLElement * xmlData, ParameterMap & outputMap) private
Read the parameters of a XML element and stores them in the passed ParameterMap reference.
Referenced by initializeAnalogueModels(), initializeAntenna(), and initializeDecider().
 {
     cXMLElementList parameters = xmlData->getElementsByTagName("Parameter");
     for (cXMLElementList::const_iterator it = parameters.begin(); it != parameters.end(); it++) {
         const char* name = (*it)->getAttribute("name");
         const char* type = (*it)->getAttribute("type");
         const char* value = (*it)->getAttribute("value");
         if (name == nullptr || type == nullptr || value == nullptr) throw cRuntimeError("Invalid parameter, could not find name, type or value");
         std::string sType = type; // needed for easier comparision
         std::string sValue = value; // needed for easier comparision
         cMsgPar param(name);
         // parse type of parameter and set value
         if (sType == "bool") {
             param.setBoolValue(sValue == "true" || sValue == "1");
         }
         else if (sType == "double") {
             param.setDoubleValue(strtod(value, nullptr));
         }
         else if (sType == "string") {
             param.setStringValue(value);
         }
         else if (sType == "long") {
             param.setLongValue(strtol(value, nullptr, 0));
         }
         else {
             throw cRuntimeError("Unknown parameter type: '%s'", sType.c_str());
         }
         // add parameter to output map
         outputMap[name] = param;
     }
 }
getRadioState()
int BasePhyLayer::getRadioState () override virtual
Return the current state the radio is in.
See also
RadioState for possible values.
Implements veins::MacToPhyInterface.
Reimplemented in veins::PhyLayer80211p.
References radio.
Referenced by veins::PhyLayer80211p::getRadioState().
 {
     Enter_Method_Silent();
     ASSERT(radio);
     return radio->getCurrentState();
 }
getWorldUtility()
BaseWorldUtility * BasePhyLayer::getWorldUtility () override virtual
Return a pointer to the simulations world-utility-module.
Implements veins::DeciderToPhyInterface.
References world.
 {
     return world;
 }
handleAirFrame()
void BasePhyLayer::handleAirFrame (AirFrame * frame) protected virtual
Handle messages received from the channel.
See also
handleAirFrameStartReceive
handleAirFrameReceiving
handleAirFrameEndReceive
References end_receive, handleAirFrameEndReceive(), handleAirFrameReceiving(), handleAirFrameStartReceive(), receiving, and start_receive.
Referenced by handleMessage(), veins::PhyLayer80211p::handleSelfMessage(), and handleSelfMessage().
 {
     // TODO: ask jerome to set air frame priority in his UWBIRPhy
     // ASSERT(frame->getSchedulingPriority() == airFramePriority());
     switch (static_cast<AirFrameState>(frame->getState())) {
     case AirFrameState::start_receive:
         handleAirFrameStartReceive(frame);
         break;
     case AirFrameState::receiving: {
         handleAirFrameReceiving(frame);
         break;
     }
     case AirFrameState::end_receive:
         handleAirFrameEndReceive(frame);
         break;
     default:
         throw cRuntimeError("Unknown AirFrame state: %s", frame->getState());
     }
 }
handleAirFrameEndReceive()
void BasePhyLayer::handleAirFrameEndReceive (AirFrame * msg) protected virtual
Handle incoming AirFrames with the state AirFrameState::end_receive.
References channelInfo, veins::ChannelInfo::isChannelEmpty(), and veins::ChannelInfo::removeAirFrame().
Referenced by handleAirFrame(), and handleAirFrameReceiving().
 {
     EV_TRACE << "End of Airframe with ID " << frame->getId() << "." << endl;
     simtime_t earliestInfoPoint = channelInfo.removeAirFrame(frame);
     /* clean information in the radio until earliest time-point
      * of information in the ChannelInfo,
      * since this time-point might have changed due to removal of
      * the AirFrame
      */
     if (channelInfo.isChannelEmpty()) {
         earliestInfoPoint = simTime();
     }
 }
handleAirFrameReceiving()
void BasePhyLayer::handleAirFrameReceiving (AirFrame * msg) protected virtual
Handle incoming AirFrames with the state AirFrameState::receiving.
References decider, end_receive, veins::Signal::getDuration(), veins::Signal::getReceptionStart(), handleAirFrameEndReceive(), and sendSelfMessage().
Referenced by handleAirFrame(), and handleAirFrameStartReceive().
 {
     Signal& signal = frame->getSignal();
     simtime_t nextHandleTime = decider->processSignal(frame);
     ASSERT(signal.getDuration() == frame->getDuration());
     simtime_t signalEndTime = signal.getReceptionStart() + frame->getDuration();
     // check if this is the end of the receiving process
     if (simTime() >= signalEndTime) {
         frame->setState(static_cast<int>(AirFrameState::end_receive));
         handleAirFrameEndReceive(frame);
         return;
     }
     // smaller zero means don't give it to me again
     if (nextHandleTime < 0) {
         nextHandleTime = signalEndTime;
         frame->setState(static_cast<int>(AirFrameState::end_receive));
         // invalid point in time
     }
     else if (nextHandleTime < simTime() || nextHandleTime > signalEndTime) {
         throw cRuntimeError("Invalid next handle time returned by Decider. Expected a value between current simulation time (%.2f) and end of signal (%.2f) but got %.2f", SIMTIME_DBL(simTime()), SIMTIME_DBL(signalEndTime), SIMTIME_DBL(nextHandleTime));
     }
     EV_TRACE << "Handed AirFrame with ID " << frame->getId() << " to Decider. Next handling in " << nextHandleTime - simTime() << "s." << endl;
     sendSelfMessage(frame, nextHandleTime);
 }
handleAirFrameStartReceive()
void BasePhyLayer::handleAirFrameStartReceive (AirFrame * msg) protected virtual
Handle incoming AirFrames with the state AirFrameState::start_receive.
References veins::ChannelInfo::addAirFrame(), channelInfo, decider, end_receive, filterSignal(), veins::Signal::getReceptionStart(), veins::Signal::getSendingStart(), handleAirFrameReceiving(), veins::ChannelInfo::isChannelEmpty(), isKnownProtocolId(), receiving, sendSelfMessage(), veins::Signal::setPropagationDelay(), and veins::ChannelAccess::usePropagationDelay.
Referenced by handleAirFrame().
 {
     EV_TRACE << "Received new AirFrame " << frame << " from channel." << endl;
     channelInfo.addAirFrame(frame, simTime());
     ASSERT(!channelInfo.isChannelEmpty());
     if (usePropagationDelay) {
         Signal& s = frame->getSignal();
         simtime_t delay = simTime() - s.getSendingStart();
         s.setPropagationDelay(delay);
     }
     ASSERT(frame->getSignal().getReceptionStart() == simTime());
     filterSignal(frame);
     if (decider && isKnownProtocolId(frame->getProtocolId())) {
         frame->setState(static_cast<int>(AirFrameState::receiving));
         // pass the AirFrame the first time to the Decider
         handleAirFrameReceiving(frame);
         // if no decider is defined we will schedule the message directly to its end
     }
     else {
         Signal& signal = frame->getSignal();
         simtime_t signalEndTime = signal.getReceptionStart() + frame->getDuration();
         frame->setState(static_cast<int>(AirFrameState::end_receive));
         sendSelfMessage(frame, signalEndTime);
     }
 }
handleMessage()
void BasePhyLayer::handleMessage (cMessage * msg) override protected
Process received messages and pass to specific handlers.
See also
handleSelfMessage
handleUpperMessage
handleUpperControlMessage
handleAirFrame
References veins::MacToPhyInterface::AIR_FRAME, handleAirFrame(), handleSelfMessage(), handleUpperControlMessage(), handleUpperMessage(), upperControlIn, and upperLayerIn.
 {
     // self messages
     if (msg->isSelfMessage()) {
         handleSelfMessage(msg);
         // MacPkts <- MacToPhyControlInfo
     }
     else if (msg->getArrivalGateId() == upperLayerIn) {
         handleUpperMessage(msg);
         // controlmessages
     }
     else if (msg->getArrivalGateId() == upperControlIn) {
         handleUpperControlMessage(msg);
         // AirFrames
     }
     else if (msg->getKind() == AIR_FRAME) {
         handleAirFrame(static_cast<AirFrame*>(msg));
         // unknown message
     }
     else {
         EV << "Unknown message received." << endl;
         delete msg;
     }
 }
handleSelfMessage()
void BasePhyLayer::handleSelfMessage (cMessage * msg) protected virtual
Handle self scheduled messages.
Reimplemented in veins::PhyLayer80211p.
References veins::MacToPhyInterface::AIR_FRAME, finishRadioSwitching(), handleAirFrame(), veins::MacToPhyInterface::RADIO_SWITCHING_OVER, radioSwitchingOverTimer, sendControlMsgToMac(), veins::MacToPhyInterface::TX_OVER, and txOverTimer.
Referenced by handleMessage().
 {
     switch (msg->getKind()) {
     // transmission over
     case TX_OVER:
         ASSERT(msg == txOverTimer);
         sendControlMsgToMac(new cMessage("Transmission over", TX_OVER));
         break;
     // radio switch over
     case RADIO_SWITCHING_OVER:
         ASSERT(msg == radioSwitchingOverTimer);
         finishRadioSwitching();
         break;
     // AirFrame
     case AIR_FRAME:
         handleAirFrame(static_cast<AirFrame*>(msg));
         break;
     default:
         break;
     }
 }
handleUpperControlMessage()
void BasePhyLayer::handleUpperControlMessage (cMessage * msg) protected virtual
Handle messages received from the upper layer through the control gate.
Referenced by handleMessage().
 {
     throw cRuntimeError("Received unknown control message from upper layer!");
 }
handleUpperMessage()
void BasePhyLayer::handleUpperMessage (cMessage * msg) protected virtual
Handle messages received from the upper layer and start transmitting them.
References antenna, veins::ChannelAccess::antennaHeading, veins::ChannelAccess::antennaPosition, encapsMsg(), radio, sendMessageDown(), sendSelfMessage(), veins::Heading::toCoord(), veins::Radio::TX, and txOverTimer.
Referenced by handleMessage().
 {
     // check if Radio is in TX state
     if (radio->getCurrentState() != Radio::TX) {
         delete msg;
         msg = nullptr;
         throw cRuntimeError("Error: message for sending received, but radio not in state TX");
     }
     // check if not already sending
     if (txOverTimer->isScheduled()) {
         delete msg;
         msg = nullptr;
         throw cRuntimeError("Error: message for sending received, but radio already sending");
     }
     // build the AirFrame to send
     ASSERT(dynamic_cast<cPacket*>(msg) != nullptr);
     unique_ptr<AirFrame> frame = encapsMsg(static_cast<cPacket*>(msg));
     // Prepare a POA object and attach it to the created Airframe
     AntennaPosition pos = antennaPosition;
     Coord orient = antennaHeading.toCoord();
     frame->setPoa({pos, orient, antenna});
     // make sure there is no self message of kind TX_OVER scheduled
     // and schedule the actual one
     ASSERT(!txOverTimer->isScheduled());
     sendSelfMessage(txOverTimer, simTime() + frame->getDuration());
     sendMessageDown(frame.release());
 }
initialize()
void BasePhyLayer::initialize (int stage) override protected
Initialize members and associated objects according to parameterization.
References veins::ChannelAccess::cc, veins::FWMath::dBm2mW(), veins::FindModule< T >::findGlobalModule(), veins::ChannelAccess::initialize(), initializeAnalogueModels(), initializeAntenna(), initializeDecider(), initializeRadio(), minPowerLevel, noiseFloorValue, radio, veins::MacToPhyInterface::RADIO_SWITCHING_OVER, radioSwitchingOverTimer, recordStats, veins::MacToPhyInterface::TX_OVER, txOverTimer, upperControlIn, upperControlOut, upperLayerIn, upperLayerOut, and world.
Referenced by veins::PhyLayer80211p::initialize().
 {
     ChannelAccess::initialize(stage);
     if (stage == 0) {
         // if using sendDirect, make sure that messages arrive without delay
         gate("radioIn")->setDeliverOnReceptionStart(true);
         upperLayerIn = findGate("upperLayerIn");
         upperLayerOut = findGate("upperLayerOut");
         upperControlOut = findGate("upperControlOut");
         upperControlIn = findGate("upperControlIn");
         if (par("useNoiseFloor").boolValue()) {
             noiseFloorValue = FWMath::dBm2mW(par("noiseFloor").doubleValue());
         }
         else {
             noiseFloorValue = 0;
         }
         minPowerLevel = par("minPowerLevel").doubleValue();
         minPowerLevel = FWMath::dBm2mW(minPowerLevel);
         recordStats = par("recordStats").boolValue();
         radio = initializeRadio();
         world = FindModule<BaseWorldUtility*>::findGlobalModule();
         if (world == nullptr) {
             throw cRuntimeError("Could not find BaseWorldUtility module");
         }
         if (cc->hasPar("sat") && (minPowerLevel - FWMath::dBm2mW(cc->par("sat").doubleValue())) < -0.000001) {
             throw cRuntimeError("minPowerLevel can't be smaller than the signal attenuation threshold (sat) in ConnectionManager. Please adjust your omnetpp.ini file accordingly.");
         }
         initializeAnalogueModels(par("analogueModels").xmlValue());
         initializeDecider(par("decider").xmlValue());
         initializeAntenna(par("antenna").xmlValue());
         radioSwitchingOverTimer = new cMessage("radio switching over", RADIO_SWITCHING_OVER);
         txOverTimer = new cMessage("transmission over", TX_OVER);
     }
 }
initializeAnalogueModels()
void BasePhyLayer::initializeAnalogueModels (cXMLElement * xmlConfig) private
Initialize the AnalogueModels with the data from the passed XML-config data.
References analogueModels, analogueModelsThresholding, getAnalogueModelFromName(), and getParametersFromXML().
Referenced by initialize().
 {
     if (xmlConfig == nullptr) {
         throw cRuntimeError("No analogue models configuration file specified.");
     }
     cXMLElementList analogueModelList = xmlConfig->getElementsByTagName("AnalogueModel");
     if (analogueModelList.empty()) {
         throw cRuntimeError("No analogue models configuration found in configuration file.");
     }
     // iterate over all AnalogueModel-entries, get a new AnalogueModel instance and add
     // it to analogueModels
     for (auto&& analogueModelData : analogueModelList) {
         const char* name = analogueModelData->getAttribute("type");
         const char* thresholdingFlag = analogueModelData->getAttribute("thresholding");
         if (name == nullptr) {
             throw cRuntimeError("Could not read name of analogue model.");
         }
         ParameterMap params;
         getParametersFromXML(analogueModelData, params);
         auto newAnalogueModel = getAnalogueModelFromName(name, params);
         if (!newAnalogueModel) {
             throw cRuntimeError("Could not find an analogue model with the name \"%s\".", name);
         }
         // attach the new AnalogueModel to the AnalogueModelList
         if (thresholdingFlag && std::string(thresholdingFlag) == "true") {
             if (!newAnalogueModel->neverIncreasesPower()) {
                 throw cRuntimeError("Tried to instantiate analogue model \"%s\" with tresholding=true, but model does not support this.", name);
             }
             analogueModelsThresholding.push_back(std::move(newAnalogueModel));
         }
         else {
             analogueModels.push_back(std::move(newAnalogueModel));
         }
         EV_TRACE << "AnalogueModel \"" << name << "\" loaded." << endl;
     }
 }
initializeAntenna()
void BasePhyLayer::initializeAntenna (cXMLElement * xmlConfig) private
Initialize the Antenna with the data from the passed XML-config data.
References antenna, getAntennaFromName(), and getParametersFromXML().
Referenced by initialize().
 {
     antenna = nullptr;
     if (xmlConfig == nullptr) {
         throw cRuntimeError("No antenna configuration file specified.");
     }
     cXMLElementList antennaList = xmlConfig->getElementsByTagName("Antenna");
     if (antennaList.empty()) {
         throw cRuntimeError("No antenna configuration found in configuration file.");
     }
     cXMLElement* antennaData;
     if (antennaList.size() > 1) {
         int num = intuniform(0, antennaList.size() - 1);
         antennaData = antennaList[num];
     }
     else {
         antennaData = antennaList.front();
     }
     const char* name = antennaData->getAttribute("type");
     if (name == nullptr) {
         throw cRuntimeError("Could not read type of antenna from configuration file.");
     }
     ParameterMap params;
     getParametersFromXML(antennaData, params);
     antenna = getAntennaFromName(name, params);
     if (antenna == nullptr) {
         throw cRuntimeError("Could not find an antenna with the name \"%s\".", name);
     }
     const char* id = antennaData->getAttribute("id");
     EV_TRACE << "Antenna \"" << name << "\" with ID \"" << id << "\" loaded." << endl;
 }
initializeDecider()
void BasePhyLayer::initializeDecider (cXMLElement * xmlConfig) private
Initialize the Decider with the data from the passed XML-config data.
References decider, getDeciderFromName(), and getParametersFromXML().
Referenced by initialize().
 {
     decider = nullptr;
     if (xmlConfig == nullptr) {
         throw cRuntimeError("No decider configuration file specified.");
     }
     cXMLElementList deciderList = xmlConfig->getElementsByTagName("Decider");
     if (deciderList.empty()) {
         throw cRuntimeError("No decider configuration found in configuration file.");
     }
     if (deciderList.size() > 1) {
         throw cRuntimeError("More than one decider configuration found in configuration file.");
     }
     cXMLElement* deciderData = deciderList.front();
     const char* name = deciderData->getAttribute("type");
     if (name == nullptr) {
         throw cRuntimeError("Could not read type of decider from configuration file.");
     }
     ParameterMap params;
     getParametersFromXML(deciderData, params);
     decider = getDeciderFromName(name, params);
     if (decider == nullptr) {
         throw cRuntimeError("Could not find a decider with the name \"%s\".", name);
     }
     EV_TRACE << "Decider \"" << name << "\" loaded." << endl;
 }
initializeRadio()
unique_ptr< Radio > BasePhyLayer::initializeRadio () protected virtual
Create and return the radio class to use.
References veins::Radio::createNewRadio(), radio, readPar(), recordStats, veins::Radio::RX, veins::Radio::SLEEP, and veins::Radio::TX.
Referenced by initialize().
 {
     int initialRadioState = par("initialRadioState");
     int nbRadioChannels = readPar("nbRadioChannels", 1);
     int initialRadioChannel = readPar("initialRadioChannel", 0);
     auto radio = Radio::createNewRadio(recordStats, initialRadioState, initialRadioChannel, nbRadioChannels);
     //    - switch times to TX
     // if no RX to TX defined asume same time as sleep to TX
     radio->setSwitchTime(Radio::RX, Radio::TX, (hasPar("timeRXToTX") ? par("timeRXToTX") : par("timeSleepToTX")).doubleValue());
     // if no sleep to TX defined asume same time as RX to TX
     radio->setSwitchTime(Radio::SLEEP, Radio::TX, (hasPar("timeSleepToTX") ? par("timeSleepToTX") : par("timeRXToTX")).doubleValue());
     //    - switch times to RX
     // if no TX to RX defined asume same time as sleep to RX
     radio->setSwitchTime(Radio::TX, Radio::RX, (hasPar("timeTXToRX") ? par("timeTXToRX") : par("timeSleepToRX")).doubleValue());
     // if no sleep to RX defined asume same time as TX to RX
     radio->setSwitchTime(Radio::SLEEP, Radio::RX, (hasPar("timeSleepToRX") ? par("timeSleepToRX") : par("timeTXToRX")).doubleValue());
     //    - switch times to sleep
     // if no TX to sleep defined asume same time as RX to sleep
     radio->setSwitchTime(Radio::TX, Radio::SLEEP, (hasPar("timeTXToSleep") ? par("timeTXToSleep") : par("timeRXToSleep")).doubleValue());
     // if no RX to sleep defined asume same time as TX to sleep
     radio->setSwitchTime(Radio::RX, Radio::SLEEP, (hasPar("timeRXToSleep") ? par("timeRXToSleep") : par("timeTXToSleep")).doubleValue());
     return radio;
 }
initializeSampledAntenna1D()
std::shared_ptr< Antenna > BasePhyLayer::initializeSampledAntenna1D (ParameterMap & params) protected virtual
Creates and returns an instance of the SampledAntenna1D class as a shared pointer.
The given parameters (i.e. samples and optional randomness parameters) are evaluated and passed to the antenna's constructor.
Referenced by getAntennaFromName().
 {
     // get samples of the modeled antenna and put them in a vector
     ParameterMap::iterator it = params.find("samples");
     if (it == params.end()) {
         throw cRuntimeError("BasePhyLayer::initializeSampledAntenna1D(): No samples specified for this antenna. \
                 Please adjust your xml file accordingly.");
     }
     std::vector<double> values;
     std::stringstream samplesStream(it->second.stringValue());
     std::copy(std::istream_iterator<double>(samplesStream), std::istream_iterator<double>(), std::back_inserter(values));
     // get optional random offsets for the antenna's samples
     std::string offsetType = "";
     std::vector<double> offsetParams;
     it = params.find("random-offsets");
     if (it != params.end()) {
         std::string buf;
         std::stringstream offsetStream(it->second.stringValue());
         offsetStream >> offsetType;
         std::copy(std::istream_iterator<double>(offsetStream), std::istream_iterator<double>(), std::back_inserter(offsetParams));
     }
     // get optional random rotation of the whole pattern
     std::string rotationType = "";
     std::vector<double> rotationParams;
     it = params.find("random-rotation");
     if (it != params.end()) {
         std::string buf;
         std::stringstream rotationStream(it->second.stringValue());
         rotationStream >> rotationType;
         std::copy(std::istream_iterator<double>(rotationStream), std::istream_iterator<double>(), std::back_inserter(rotationParams));
     }
     return std::make_shared<SampledAntenna1D>(values, offsetType, offsetParams, rotationType, rotationParams, this->getRNG(0));
 }
isKnownProtocolId()
virtual bool veins::BasePhyLayer::isKnownProtocolId (int id) inline protected virtual
Return whether the protocol with the passed identifier is decodeable by the decider.
Default implementation checks only if the passed id is the same as the one returned by "myProtocolId()".
Parameters
id The identifier of the protocol of an AirFrame.
Returns
true if the passed protocol id is supported by this phy. layer.
Referenced by handleAirFrameStartReceive().
     {
         return id == myProtocolId();
     }
myProtocolId()
virtual int veins::BasePhyLayer::myProtocolId () inline protected virtual
Return the identifier of the protocol this phy uses to send messages.
Returns
An integer representing the identifier of the used protocol.
Referenced by encapsMsg().
     {
         return protocolId;
     }
readPar()
template<class T > template bool BasePhyLayer::readPar< bool > (const char * parName, const T defaultValue) protected
Read and return the parameter with the passed name.
If the parameter couldn't be found the value of defaultValue is returned.
Parameters
parName The name of the ned-parameter
defaultValue The value to be returned if the parameter couldn't be found
Referenced by initializeRadio().
 {
     if (hasPar(parName))
         return par(parName);
     else
         return defaultValue;
 }
recordScalar()
void BasePhyLayer::recordScalar (const char * name, double value, const char * unit = nullptr) override virtual
Record a double into the scalar result file.
Implements the method from DeciderToPhyInterface, method-calls are forwarded to OMNeT-method 'recordScalar'.
See also
cComponent::recordScalar
Implements veins::DeciderToPhyInterface.
 {
     ChannelAccess::recordScalar(name, value, unit);
 }
sendControlMessageUp()
void BasePhyLayer::sendControlMessageUp (cMessage * msg) protected
Send the passed control message to the upper layer.
References upperControlOut.
Referenced by sendControlMsgToMac().
 {
     send(msg, upperControlOut);
 }
sendControlMsgToMac()
void BasePhyLayer::sendControlMsgToMac (cMessage * msg) override virtual
Send the given message to via the control gate to the mac.
See also
upperControlOut
Implements veins::DeciderToPhyInterface.
References sendControlMessageUp().
Referenced by finishRadioSwitching(), veins::PhyLayer80211p::handleSelfMessage(), and handleSelfMessage().
 {
     sendControlMessageUp(msg);
 }
sendMacPktUp()
void BasePhyLayer::sendMacPktUp (cMessage * pkt) protected
Send the passed MacPkt to the upper layer.
References upperLayerOut.
Referenced by sendUp().
 {
     send(pkt, upperLayerOut);
 }
sendMessageDown()
void BasePhyLayer::sendMessageDown (AirFrame * pkt) protected
Send the passed AirFrame to the channel.
References veins::ChannelAccess::sendToChannel().
Referenced by handleUpperMessage().
 {
     sendToChannel(msg);
 }
sendSelfMessage()
void BasePhyLayer::sendSelfMessage (cMessage * msg, simtime_t_cref time) protected
Schedule self message to passed point in time.
Referenced by handleAirFrameReceiving(), handleAirFrameStartReceive(), handleUpperMessage(), and setRadioState().
 {
     // TODO: maybe delete this method because it doesn't makes much sense,
     //        or change it to "scheduleIn(msg, timeDelta)" which schedules
     //        a message to +timeDelta from current time
     scheduleAt(time, msg);
 }
sendUp()
void BasePhyLayer::sendUp (AirFrame * packet, DeciderResult * result) override virtual
Pass the given packet along with the result up to the mac.
Implements veins::DeciderToPhyInterface.
References sendMacPktUp(), and veins::PhyToMacControlInfo::setControlInfo().
 {
     EV_TRACE << "Decapsulating MacPacket from Airframe with ID " << frame->getId() << " and sending it up to MAC." << endl;
     cMessage* packet = frame->decapsulate();
     ASSERT(packet);
     PhyToMacControlInfo::setControlInfo(packet, result);
     sendMacPktUp(packet);
 }
setCurrentRadioChannel()
void BasePhyLayer::setCurrentRadioChannel (int newRadioChannel) override virtual
Set the channel currently used by the radio.
Implements veins::MacToPhyInterface.
References decider, radio, and txOverTimer.
 {
     if (txOverTimer && txOverTimer->isScheduled()) {
         EV_WARN << "Switched channel while sending an AirFrame. The effects this would have on the transmission are not simulated by the BasePhyLayer!";
     }
     radio->setCurrentChannel(newRadioChannel);
     decider->channelChanged(newRadioChannel);
     EV_TRACE << "Switched radio to channel " << newRadioChannel << endl;
 }
setRadioState()
simtime_t BasePhyLayer::setRadioState (int rs) override virtual
Tell the BasePhyLayer to switch to the specified radio state.
The switching process can take some time depending on the specified switching times in the ned file.
Returns
Switching time from the current RadioState to the new RadioState or -1 if a state change is already in progress.
Implements veins::MacToPhyInterface.
Reimplemented in veins::PhyLayer80211p.
References finishRadioSwitching(), radio, radioSwitchingOverTimer, sendSelfMessage(), and txOverTimer.
Referenced by veins::PhyLayer80211p::setRadioState().
 {
     Enter_Method_Silent();
     ASSERT(radio);
     if (txOverTimer && txOverTimer->isScheduled()) {
         EV_WARN << "Switched radio while sending an AirFrame. The effects this would have on the transmission are not simulated by the BasePhyLayer!";
     }
     simtime_t switchTime = radio->switchTo(rs, simTime());
     // invalid switch time, we are probably already switching
     if (switchTime < 0) return switchTime;
     // if switching is done in exactly zero-time no extra self-message is scheduled
     if (switchTime == 0.0) {
         // TODO: in case of zero-time-switch, send no control-message to mac!
         // maybe call a method finishRadioSwitchingSilent()
         finishRadioSwitching();
     }
     else {
         sendSelfMessage(radioSwitchingOverTimer, simTime() + switchTime);
     }
     return switchTime;
 }
Member Data Documentation
analogueModels
AnalogueModelList veins::BasePhyLayer::analogueModels protected
The analogue models to use which might attenuate or amplify a signal.
Referenced by filterSignal(), and initializeAnalogueModels().
analogueModelsThresholding
AnalogueModelList veins::BasePhyLayer::analogueModelsThresholding protected
The analogue models to use which will only attenuate a signal.
These models are not applied immediately, but only attached to the signal. This enables lazy application of the models.
Referenced by filterSignal(), and initializeAnalogueModels().
antenna
std::shared_ptr<Antenna> veins::BasePhyLayer::antenna protected
Shared pointer to the Antenna used for this node.
Using a shared pointer ensures proper handling of a signal is possible, even after the sender has been destroyed.
Referenced by filterSignal(), handleUpperMessage(), and initializeAntenna().
channelInfo
ChannelInfo veins::BasePhyLayer::channelInfo protected
Channel info keeps track of received AirFrames and provides information about currently active AirFrames at the channel.
Referenced by getChannelInfo(), handleAirFrameEndReceive(), handleAirFrameStartReceive(), and ~BasePhyLayer().
decider
std::unique_ptr<Decider> veins::BasePhyLayer::decider protected
Pointer to the decider module.
Referenced by veins::PhyLayer80211p::changeListeningChannel(), finish(), handleAirFrameReceiving(), handleAirFrameStartReceive(), veins::PhyLayer80211p::handleSelfMessage(), initializeDecider(), veins::PhyLayer80211p::notifyMacAboutRxStart(), veins::PhyLayer80211p::requestChannelStatusIfIdle(), veins::PhyLayer80211p::setCCAThreshold(), setCurrentRadioChannel(), and veins::PhyLayer80211p::setRadioState().
minPowerLevel
double veins::BasePhyLayer::minPowerLevel protected
The minimum receive power needed to even attempt decoding a frame.
Referenced by initialize(), and veins::PhyLayer80211p::initializeDecider80211p().
noiseFloorValue
double veins::BasePhyLayer::noiseFloorValue = 0 protected
Catch-all for all factors negatively impacting SINR (e.g., thermal noise, noise figure, ...)
Referenced by getNoiseFloorValue(), and initialize().
overallSpectrum
Spectrum veins::BasePhyLayer::overallSpectrum protected
The underlying spectrum (definition of interesting freqs) for all signals.
Referenced by veins::PhyLayer80211p::attachSignal(), and veins::PhyLayer80211p::initialize().
protocolId
int veins::BasePhyLayer::protocolId = PROTOCOL_ID_GENERIC protected
The ID of the protocol this phy can transceive.
Referenced by veins::PhyLayer80211p::getDeciderFromName().
radio
std::unique_ptr<Radio> veins::BasePhyLayer::radio protected
The state machine storing the current radio state (TX, RX, SLEEP).
Referenced by encapsMsg(), finishRadioSwitching(), getCurrentRadioChannel(), getRadioState(), handleUpperMessage(), initialize(), initializeRadio(), setCurrentRadioChannel(), and setRadioState().
radioSwitchingOverTimer
cMessage* veins::BasePhyLayer::radioSwitchingOverTimer = nullptr protected
Self message scheduled to the point in time when the switching process of the radio is over.
Referenced by veins::PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), initialize(), setRadioState(), and ~BasePhyLayer().
recordStats
bool veins::BasePhyLayer::recordStats protected
Stores if tracking of statistics (esp. cOutvectors) is enabled.
Referenced by initialize(), and initializeRadio().
txOverTimer
cMessage* veins::BasePhyLayer::txOverTimer = nullptr protected
Self message scheduled to the point in time when the transmission of an AirFrame is over.
Referenced by veins::PhyLayer80211p::handleSelfMessage(), handleSelfMessage(), handleUpperMessage(), initialize(), setCurrentRadioChannel(), setRadioState(), and ~BasePhyLayer().
upperControlIn
int veins::BasePhyLayer::upperControlIn protected
The id of the in-control gate from the Mac layer.
Referenced by handleMessage(), and initialize().
upperControlOut
int veins::BasePhyLayer::upperControlOut protected
The id of the out-control gate to the Mac layer.
Referenced by initialize(), and sendControlMessageUp().
upperLayerIn
int veins::BasePhyLayer::upperLayerIn protected
The id of the in-data gate from the Mac layer.
Referenced by handleMessage(), and initialize().
upperLayerOut
int veins::BasePhyLayer::upperLayerOut protected
The id of the out-data gate to the Mac layer.
Referenced by initialize(), and sendMacPktUp().
world
BaseWorldUtility* veins::BasePhyLayer::world = nullptr protected
Pointer to the World Utility, to obtain some global information.
Referenced by encapsMsg(), veins::PhyLayer80211p::getAnalogueModelFromName(), getWorldUtility(), initialize(), veins::PhyLayer80211p::initializeBreakpointPathlossModel(), veins::PhyLayer80211p::initializeSimpleObstacleShadowing(), veins::PhyLayer80211p::initializeSimplePathlossModel(), and veins::PhyLayer80211p::initializeVehicleObstacleShadowing().
The documentation for this class was generated from the following files:
BasePhyLayer.h
BasePhyLayer.cc