Veins: veins::SimplePathlossModel Class Reference
veins::SimplePathlossModel Class Reference
Basic implementation of a SimplePathlossModel.
#include <SimplePathlossModel.h>
Public Member Functions
SimplePathlossModel (cComponent *owner, double alpha, bool useTorus, const Coord &playgroundSize)
Initializes the analogue model.
void filterSignal (Signal *) override
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
bool neverIncreasesPower () override
If the model never increases the power level of any signal given to filterSignal, it returns true here.
Public Member Functions inherited from veins::AnalogueModel
AnalogueModel (cComponent *owner)
virtual ~AnalogueModel ()
Public Member Functions inherited from veins::HasLogProxy
HasLogProxy (cComponent *owner)
const cComponent * getThisPtr () const
Protected Attributes
double pathLossAlphaHalf
Path loss coefficient.
const bool useTorus
Information needed about the playground.
const Coord & playgroundSize
The size of the playground.
Protected Attributes inherited from veins::HasLogProxy
cComponent * owner
Detailed Description
Basic implementation of a SimplePathlossModel.
An example config.xml for this AnalogueModel can be the following:
 <AnalogueModel type="SimplePathlossModel">
     <!-- Environment parameter of the pathloss formula
          If ommited default value is 3.5-->
     <parameter name="alpha" type="double" value="3.5"/>
 </AnalogueModel>
Constructor & Destructor Documentation
SimplePathlossModel()
veins::SimplePathlossModel::SimplePathlossModel (cComponent * owner, double alpha, bool useTorus, const Coord & playgroundSize) inline
Initializes the analogue model.
playgroundSize need to be valid as long as this instance exists.
The constructor needs some specific knowledge in order to create its mapping properly:
Parameters
owner pointer to the cComponent that owns this AnalogueModel
alpha the coefficient alpha (specified e.g. in config.xml and passed in constructor call)
useTorus information about the playground the host is moving in
playgroundSize information about the playground the host is moving in
         : AnalogueModel(owner)
         , pathLossAlphaHalf(alpha * 0.5)
         , useTorus(useTorus)
         , playgroundSize(playgroundSize)
     {
     }
Member Function Documentation
filterSignal()
void SimplePathlossModel::filterSignal (Signal * signal) override virtual
Filters a specified AirFrame's Signal by adding an attenuation over time to the Signal.
Calculate the distance factor
Implements veins::AnalogueModel.
References veins::Spectrum::freqAt(), veins::Signal::getNumValues(), veins::AntennaPosition::getPositionAt(), veins::Signal::getReceiverPoa(), veins::Signal::getSenderPoa(), veins::Signal::getSpectrum(), M_PI, pathLossAlphaHalf, playgroundSize, veins::POA::pos, veins::BaseWorldUtility::speedOfLight(), and useTorus.
 {
     auto senderPos = signal->getSenderPoa().pos.getPositionAt();
     auto receiverPos = signal->getReceiverPoa().pos.getPositionAt();
     /** Calculate the distance factor */
     double sqrDistance = useTorus ? receiverPos.sqrTorusDist(senderPos, playgroundSize) : receiverPos.sqrdist(senderPos);
     EV_TRACE << "sqrdistance is: " << sqrDistance << endl;
     if (sqrDistance <= 1.0) {
         // attenuation is negligible
         return;
     }
     // the part of the attenuation only depending on the distance
     double distFactor = pow(sqrDistance, -pathLossAlphaHalf) / (16.0 * M_PI * M_PI);
     EV_TRACE << "distance factor is: " << distFactor << endl;
     Signal attenuation(signal->getSpectrum());
     for (uint16_t i = 0; i < signal->getNumValues(); i++) {
         double wavelength = BaseWorldUtility::speedOfLight() / signal->getSpectrum().freqAt(i);
         attenuation.at(i) = (wavelength * wavelength) * distFactor;
     }
     *signal *= attenuation;
 }
neverIncreasesPower()
bool veins::SimplePathlossModel::neverIncreasesPower () inline override virtual
If the model never increases the power level of any signal given to filterSignal, it returns true here.
This allows optimized signal handling.
Reimplemented from veins::AnalogueModel.
     {
         return true;
     }
Member Data Documentation
pathLossAlphaHalf
double veins::SimplePathlossModel::pathLossAlphaHalf protected
Path loss coefficient.
Referenced by filterSignal().
playgroundSize
const Coord& veins::SimplePathlossModel::playgroundSize protected
The size of the playground.
Referenced by filterSignal().
useTorus
const bool veins::SimplePathlossModel::useTorus protected
Information needed about the playground.
Referenced by filterSignal().
The documentation for this class was generated from the following files:
SimplePathlossModel.h
SimplePathlossModel.cc