Veins: veins::ChannelAccess Class Reference
veins::ChannelAccess Class Reference
Basic class for all physical layers, please don't touch!!
#include <ChannelAccess.h>
Public Member Functions
void initialize (int stage) override
Register with ConnectionManager.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Called by the signalling mechanism to inform of changes.
virtual ChannelMobilityPtrType getMobilityModule ()
Returns the host's mobility module.
virtual AntennaPosition getAntennaPosition () const
Public Member Functions inherited from veins::BatteryAccess
BatteryAccess ()
BatteryAccess (unsigned stacksize)
Public Member Functions inherited from veins::BaseModule
BaseModule ()
BaseModule (unsigned stacksize)
void initialize (int) override
Basic initialization for all modules.
int numInitStages () const override
Divide initialization into two stages.
std::string logName (void) const
Function to get the logging name of the host.
const cModule *const getNode () const
Get a reference to the local node module.
void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
Static Public Member Functions
static BaseConnectionManager * getConnectionManager (cModule *nic)
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Protected Member Functions
simtime_t calculatePropagationDelay (const NicEntry *nic)
Calculates the propagation delay to the passed receiving nic.
void sendToChannel (cPacket *msg)
Sends a message to all nics connected to this one.
Protected Member Functions inherited from veins::BatteryAccess
void registerWithBattery (const std::string &name, int numAccounts)
Registers this module as a device with the battery module.
void draw (DrawAmount &amount, int account)
Draws the amount defined by the passed DrawAmount from the battery on account of the passed account.
void drawCurrent (double amount, int account)
Draws the passed amount of current (in mA) over time from the battery on account of the passed account.
void drawEnergy (double amount, int account)
Draws the passed amount of energy (in mWs) from the battery on account of the passed account.
Protected Member Functions inherited from veins::BaseModule
virtual void handleHostState (const HostState &state)
Called whenever the hosts state changes.
void switchHostState (HostState::States state)
Switches the host to the passed state.
cModule *const findHost (void)
Function to get a pointer to the host module.
const cModule *const findHost (void) const
void finish () override
Function to get the logging name of id.
void finish (cComponent *component, simsignal_t signalID) override
Protected Member Functions inherited from veins::AccessModuleWrap< T >
AccessModuleWrap ()
T *const get (cModule *const from=nullptr)
Protected Attributes
bool useSendDirect
use sendDirect or not?
BaseConnectionManager * cc
Pointer to the PropagationModel module.
bool usePropagationDelay
Defines if the physical layer should simulate propagation delay.
bool isRegistered
Is this module already registered with ConnectionManager?
BaseWorldUtility * world
Pointer to the World Utility, to obtain some global information.
AntennaPosition antennaPosition
Current antenna position.
Heading antennaHeading
Current antenna heading (angle)
Coord antennaOffset = Coord(0, 0, 0)
Offset of antenna position (in m) with respect to what a BaseMobility module will tell us.
double antennaOffsetYaw = 0
Offset of antenna orientation (yaw, in rad) with respect to what a BaseMobility module will tell us.
Protected Attributes inherited from veins::BatteryAccess
BaseBattery * battery
Stores pointer to the battery module.
int deviceID
This devices id for the battery module.
Protected Attributes inherited from veins::BaseModule
bool notAffectedByHostState
Stores if this module is affected by changes in the hosts state.
Additional Inherited Members
Protected Types inherited from veins::AccessModuleWrap< T >
using wrapType = T
Static Protected Attributes inherited from veins::BaseModule
static const simsignal_t catHostStateSignal = registerSignal("org_car2x_veins_base_utils_hoststate")
Stores the category of the HostState.
Detailed Description
Basic class for all physical layers, please don't touch!!
This class is not supposed to work on its own, but it contains functions and lists that cooperate with ConnectionManager to handle the dynamically created gates. This means EVERY physical layer (the lowest layer in a host) has to be derived from this class!!!!
Please don't touch this class.
Author
Marc Loebbers
Member Function Documentation
calculatePropagationDelay()
simtime_t ChannelAccess::calculatePropagationDelay (const NicEntry * nic) protected
Calculates the propagation delay to the passed receiving nic.
claim the Move pattern of the sender from the Signal
References antennaPosition, veins::NicEntry::chAccess, veins::Coord::distance(), veins::AntennaPosition::getPositionAt(), veins::BaseWorldUtility::speedOfLight(), and usePropagationDelay.
Referenced by sendToChannel().
 {
     if (!usePropagationDelay) return 0;
     ChannelAccess* const senderModule = this;
     ChannelAccess* const receiverModule = nic->chAccess;
     // const simtime_t_cref sStart         = simTime();
     ASSERT(senderModule);
     ASSERT(receiverModule);
     /** claim the Move pattern of the sender from the Signal */
     Coord senderPos = senderModule->antennaPosition.getPositionAt();
     Coord receiverPos = receiverModule->antennaPosition.getPositionAt();
     // this time-point is used to calculate the distance between sending and receiving host
     return receiverPos.distance(senderPos) / BaseWorldUtility::speedOfLight();
 }
getAntennaPosition()
virtual AntennaPosition veins::ChannelAccess::getAntennaPosition () const inline virtual
     {
         return antennaPosition;
     }
getConnectionManager()
BaseConnectionManager * ChannelAccess::getConnectionManager (cModule * nic) static
Returns a pointer to the ConnectionManager responsible for the passed NIC module.
Parameters
nic a pointer to a NIC module
Returns
a pointer to a connection manager module or NULL if an error occurred
Referenced by veins::TraCIScenarioManager::deleteManagedModule(), veins::BaseMacLayer::getConnectionManager(), and initialize().
 {
     std::string cmName = nic->hasPar("connectionManagerName") ? nic->par("connectionManagerName").stringValue() : "";
     if (cmName != "") {
         cModule* ccModule = cSimulation::getActiveSimulation()->getModuleByPath(cmName.c_str());
         return dynamic_cast<BaseConnectionManager*>(ccModule);
     }
     else {
         throw cRuntimeError("Variable connectionManagerName must be specified");
     }
 }
getMobilityModule()
virtual ChannelMobilityPtrType veins::ChannelAccess::getMobilityModule () inline virtual
Returns the host's mobility module.
References veins::AccessModuleWrap< T >::get().
     {
         return ChannelMobilityAccessType::get(this);
     }
initialize()
void ChannelAccess::initialize (int stage) override
Register with ConnectionManager.
Upon initialization ChannelAccess registers the nic parent module to have all its connections handeled by ConnectionManager
References antennaOffset, antennaOffsetYaw, cc, veins::BaseModule::findHost(), getConnectionManager(), veins::BaseModule::initialize(), isRegistered, veins::BaseMobility::mobilityStateChangedSignal, usePropagationDelay, veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by veins::BasePhyLayer::initialize().
 {
     BatteryAccess::initialize(stage);
     if (stage == 0) {
         if (hasPar("antennaOffsetX")) {
             antennaOffset.x = par("antennaOffsetX").doubleValue();
         }
         if (hasPar("antennaOffsetY")) {
             antennaOffset.y = par("antennaOffsetY").doubleValue();
         }
         if (hasPar("antennaOffsetZ")) {
             antennaOffset.z = par("antennaOffsetZ").doubleValue();
         }
         if (hasPar("antennaOffsetYaw")) {
             antennaOffsetYaw = par("antennaOffsetYaw").doubleValue();
         }
         findHost()->subscribe(BaseMobility::mobilityStateChangedSignal, this);
         cModule* nic = getParentModule();
         cc = getConnectionManager(nic);
         if (cc == nullptr) throw cRuntimeError("Could not find connectionmanager module");
         isRegistered = false;
     }
     usePropagationDelay = par("usePropagationDelay");
 }
receiveSignal()
void ChannelAccess::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override
Called by the signalling mechanism to inform of changes.
ChannelAccess is subscribed to position changes and informs the ConnectionManager.
References antennaHeading, antennaOffset, antennaOffsetYaw, antennaPosition, cc, veins::Heading::fromCoord(), isRegistered, veins::BaseMobility::mobilityStateChangedSignal, veins::BaseConnectionManager::registerNic(), veins::Coord::rotatedYaw(), veins::BaseConnectionManager::updateNicPos(), and useSendDirect.
 {
     if (signalID == BaseMobility::mobilityStateChangedSignal) {
         ChannelMobilityPtrType const mobility = check_and_cast<ChannelMobilityPtrType>(obj);
         auto heading = Heading::fromCoord(mobility->getCurrentOrientation());
         antennaPosition = AntennaPosition(getId(), mobility->getPositionAt(simTime()) + antennaOffset.rotatedYaw(-heading.getRad()), mobility->getCurrentSpeed(), simTime());
         antennaHeading = Heading(heading.getRad() + antennaOffsetYaw);
         if (isRegistered) {
             cc->updateNicPos(getParentModule()->getId(), antennaPosition.getPositionAt(), antennaHeading);
         }
         else {
             // register the nic with ConnectionManager
             // returns true, if sendDirect is used
             useSendDirect = cc->registerNic(getParentModule(), this, antennaPosition.getPositionAt(), antennaHeading);
             isRegistered = true;
         }
     }
 }
sendToChannel()
void ChannelAccess::sendToChannel (cPacket * msg) protected
Sends a message to all nics connected to this one.
This function has to be called whenever a packet is supposed to be sent to the channel. Don't try to figure out what gates you have and which ones are connected, this function does this for you!
depending on which ConnectionManager module is used, the messages are send via sendDirect() or to the respective gates.
References calculatePropagationDelay(), cc, veins::BaseConnectionManager::getGateList(), and useSendDirect.
Referenced by veins::BasePhyLayer::sendMessageDown().
 {
     const NicEntry::GateList& gateList = cc->getGateList(getParentModule()->getId());
     NicEntry::GateList::const_iterator i = gateList.begin();
     if (useSendDirect) {
         // use Andras stuff
         if (i != gateList.end()) {
             simtime_t delay = SIMTIME_ZERO;
             for (; i != --gateList.end(); ++i) {
                 // calculate delay (Propagation) to this receiving nic
                 delay = calculatePropagationDelay(i->first);
                 int radioStart = i->second->getId();
                 int radioEnd = radioStart + i->second->size();
                 for (int g = radioStart; g != radioEnd; ++g) sendDirect(static_cast<cPacket*>(msg->dup()), delay, msg->getDuration(), i->second->getOwnerModule(), g);
             }
             // calculate delay (Propagation) to this receiving nic
             delay = calculatePropagationDelay(i->first);
             int radioStart = i->second->getId();
             int radioEnd = radioStart + i->second->size();
             for (int g = radioStart; g != --radioEnd; ++g) sendDirect(static_cast<cPacket*>(msg->dup()), delay, msg->getDuration(), i->second->getOwnerModule(), g);
             sendDirect(msg, delay, msg->getDuration(), i->second->getOwnerModule(), radioEnd);
         }
         else {
             EV_WARN << "Nic is not connected to any gates!" << endl;
             delete msg;
         }
     }
     else {
         // use our stuff
         EV_TRACE << "sendToChannel: sending to gates\n";
         if (i != gateList.end()) {
             simtime_t delay = SIMTIME_ZERO;
             for (; i != --gateList.end(); ++i) {
                 // calculate delay (Propagation) to this receiving nic
                 delay = calculatePropagationDelay(i->first);
                 sendDelayed(static_cast<cPacket*>(msg->dup()), delay, i->second);
             }
             // calculate delay (Propagation) to this receiving nic
             delay = calculatePropagationDelay(i->first);
             sendDelayed(msg, delay, i->second);
         }
         else {
             EV_WARN << "Nic is not connected to any gates!" << endl;
             delete msg;
         }
     }
 }
Member Data Documentation
antennaHeading
Heading veins::ChannelAccess::antennaHeading protected
Current antenna heading (angle)
Referenced by veins::BasePhyLayer::filterSignal(), veins::BasePhyLayer::handleUpperMessage(), and receiveSignal().
antennaOffset
Coord veins::ChannelAccess::antennaOffset = Coord(0, 0, 0) protected
Offset of antenna position (in m) with respect to what a BaseMobility module will tell us.
Referenced by initialize(), and receiveSignal().
antennaOffsetYaw
double veins::ChannelAccess::antennaOffsetYaw = 0 protected
Offset of antenna orientation (yaw, in rad) with respect to what a BaseMobility module will tell us.
Referenced by initialize(), and receiveSignal().
antennaPosition
AntennaPosition veins::ChannelAccess::antennaPosition protected
Current antenna position.
Referenced by calculatePropagationDelay(), veins::BasePhyLayer::filterSignal(), veins::BasePhyLayer::handleUpperMessage(), and receiveSignal().
cc
BaseConnectionManager* veins::ChannelAccess::cc protected
Pointer to the PropagationModel module.
Referenced by initialize(), veins::BasePhyLayer::initialize(), veins::PhyLayer80211p::initializeBreakpointPathlossModel(), veins::PhyLayer80211p::initializeSimplePathlossModel(), receiveSignal(), and sendToChannel().
isRegistered
bool veins::ChannelAccess::isRegistered protected
Is this module already registered with ConnectionManager?
Referenced by initialize(), and receiveSignal().
usePropagationDelay
bool veins::ChannelAccess::usePropagationDelay protected
Defines if the physical layer should simulate propagation delay.
Referenced by calculatePropagationDelay(), veins::BasePhyLayer::handleAirFrameStartReceive(), and initialize().
useSendDirect
bool veins::ChannelAccess::useSendDirect protected
use sendDirect or not?
Referenced by receiveSignal(), and sendToChannel().
world
BaseWorldUtility* veins::ChannelAccess::world protected
Pointer to the World Utility, to obtain some global information.
The documentation for this class was generated from the following files:
ChannelAccess.h
ChannelAccess.cc