Veins: anonymous_namespace{BaseConnectionManager.cc} Namespace Reference
anonymous_namespace{BaseConnectionManager.cc} Namespace Reference
Functions
static double dist (double coord1, double coord2, double size)
On a torus the end and the begin of the axes are connected so you get a circle.
double sqrTorusDist (Coord c, Coord b, Coord size)
Function Documentation
dist()
static double anonymous_namespace{BaseConnectionManager.cc}::dist (double coord1, double coord2, double size) static
On a torus the end and the begin of the axes are connected so you get a circle.
On a circle the distance between two points can't be greater than half of the circumference. If the normal distance between two points on one axis is bigger than half of the size there must be a "shorter way" over the border on this axis
References veins::FWMath::modulo().
Referenced by veins::Coord::distance(), veins::Coord::sqrdist(), and sqrTorusDist().
 {
     double difference = fabs(coord1 - coord2);
     if (difference == 0)
         // NOTE: event if size is zero
         return 0;
     else {
         ASSERT(size != 0);
         double dist = FWMath::modulo(difference, size);
         return std::min(dist, size - dist);
     }
 }
sqrTorusDist()
double anonymous_namespace{BaseConnectionManager.cc}::sqrTorusDist (Coord c, Coord b, Coord size)
References dist(), veins::Coord::x, veins::Coord::y, and veins::Coord::z.
Referenced by veins::BaseConnectionManager::isInRange(), and veins::Coord::sqrdist().
 {
     double xDist = dist(c.x, b.x, size.x);
     double yDist = dist(c.y, b.y, size.y);
     double zDist = dist(c.z, b.z, size.z);
     return xDist * xDist + yDist * yDist + zDist * zDist;
 }