Veins: anonymous_namespace{MobileHostObstacle.cc} Namespace Reference
anonymous_namespace{MobileHostObstacle.cc} Namespace Reference
Functions
bool isPointInObstacle (Coord point, const MobileHostObstacle::Coords &shape)
double segmentsIntersectAt (Coord p1From, Coord p1To, Coord p2From, Coord p2To)
Function Documentation
isPointInObstacle()
bool anonymous_namespace{MobileHostObstacle.cc}::isPointInObstacle (Coord point, const MobileHostObstacle::Coords & shape)
References anonymous_namespace{BBoxLookup.cc}::intersects(), veins::Coord::x, and veins::Coord::y.
Referenced by veins::MobileHostObstacle::getIntersectionPoint().
 {
     bool isInside = false;
     auto i = shape.begin();
     auto j = (shape.rbegin() + 1).base();
     for (; i != shape.end(); j = i++) {
         bool inYRangeUp = (point.y >= i->y) && (point.y < j->y);
         bool inYRangeDown = (point.y >= j->y) && (point.y < i->y);
         bool inYRange = inYRangeUp || inYRangeDown;
         if (!inYRange) continue;
         bool intersects = point.x < (i->x + ((point.y - i->y) * (j->x - i->x) / (j->y - i->y)));
         if (!intersects) continue;
         isInside = !isInside;
     }
     return isInside;
 }
segmentsIntersectAt()
double anonymous_namespace{MobileHostObstacle.cc}::segmentsIntersectAt (Coord p1From, Coord p1To, Coord p2From, Coord p2To)
References veins::Coord::x, and veins::Coord::y.
Referenced by veins::MobileHostObstacle::getIntersectionPoint().
 {
     Coord p1Vec = p1To - p1From;
     Coord p2Vec = p2To - p2From;
     Coord p1p2 = p1From - p2From;
     double D = (p1Vec.x * p2Vec.y - p1Vec.y * p2Vec.x);
     double p1Frac = (p2Vec.x * p1p2.y - p2Vec.y * p1p2.x) / D;
     if (p1Frac < 0 || p1Frac > 1) return -1;
     double p2Frac = (p1Vec.x * p1p2.y - p1Vec.y * p1p2.x) / D;
     if (p2Frac < 0 || p2Frac > 1) return -1;
     return p1Frac;
 }