Veins: veins::SignalUtils Namespace Reference
veins::SignalUtils Namespace Reference
Namespaces
anonymous_namespace{SignalUtils.cc}
Typedefs
using AirFrameVector = DeciderToPhyInterface::AirFrameVector
Functions
bool VEINS_API isChannelPowerBelowThreshold (simtime_t now, AirFrameVector &interfererFrames, size_t freqIndex, double threshold, AirFrame *exclude=nullptr)
check if the summed power of interfererFrames's signals at freqIndex is below a given threshold.
double VEINS_API getMinSINR (simtime_t start, simtime_t end, AirFrame *signalFrame, AirFrameVector &interfererFrames, double noise)
return the minimal Signal to (Interference + Noise) Ratio at any data channel of signalFrame's signal
Typedef Documentation
AirFrameVector
using veins::SignalUtils::AirFrameVector = typedef DeciderToPhyInterface::AirFrameVector
Function Documentation
getMinSINR()
double VEINS_API veins::SignalUtils::getMinSINR (simtime_t start, simtime_t end, AirFrame * signalFrame, AirFrameVector & interfererFrames, double noise)
return the minimal Signal to (Interference + Noise) Ratio at any data channel of signalFrame's signal
Important: The AirFrameVector interfererFrames is assumed to be sorted by signal reception start time!
This function ensures that all analogue models attached to the signal of each interfererFrame and the signalFrame are applied. Only considers the given interval between [start, end) and assumes time-independent noise that is the same for all channels.
References veins::Signal::at(), veins::Signal::getDataEnd(), veins::Signal::getDataStart(), veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference(), and veins::Signal::getSpectrum().
Referenced by veins::Decider80211p::checkIfSignalOk().
 {
     ASSERT(start >= signalFrame->getSignal().getReceptionStart());
     ASSERT(end <= signalFrame->getSignal().getReceptionEnd());
     // Make sure all filters are applied
     signalFrame->getSignal().applyAllAnalogueModels();
     for (auto& interfererFrame : interfererFrames) {
         interfererFrame->getSignal().applyAllAnalogueModels();
     }
     Signal& signal = signalFrame->getSignal();
     Spectrum spectrum = signal.getSpectrum();
     Signal interference = getMaxInterference(start, end, signalFrame, interfererFrames);
     Signal sinr = signal / (interference + noise);
     double min_sinr = INFINITY;
     for (uint16_t i = signal.getDataStart(); i < signal.getDataEnd(); i++) {
         min_sinr = std::min(min_sinr, sinr.at(i));
     }
     return min_sinr;
 }
isChannelPowerBelowThreshold()
bool VEINS_API veins::SignalUtils::isChannelPowerBelowThreshold (simtime_t now, AirFrameVector & interfererFrames, size_t freqIndex, double threshold, AirFrame * exclude = nullptr)
check if the summed power of interfererFrames's signals at freqIndex is below a given threshold.
Only considers the signals active at time now and ignores the AirFrame given as exclude.
This function will apply analogue models attached to the interfererFrames's signals. It will skip applying analogue models once it is clear that the interferer signals are below threshold. This is known as "thresholding" or some sort of short-circuit evaluation.
TODO: apply analogue models one by one instead of group-wise. Currently assumes that all signals have the same analogue model (classes) attached to them. Each model is applied for all signals before the next check for the threshold is performed. This can be optimized to minimize the number of analog models needed to be applied.
References veins::Signal::getAnalogueModelList(), veins::Signal::getReceptionEnd(), veins::Signal::getReceptionStart(), and veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::powerLevelSumAtFrequencyIndex().
Referenced by veins::Decider80211p::cca().
 {
     if (interfererFrames.empty()) {
         // No interferers, so the channel interference is below any threshold
         return true;
     }
     // extract valid signals on the channel at the time of interest
     // TODO: possibly move this filtering outside of this function
     std::vector<Signal*> interferers;
     for (auto& interfererFrame : interfererFrames) {
         Signal* interferer = &interfererFrame->getSignal();
         if (interferer->getReceptionStart() <= now && interferer->getReceptionEnd() > now && interfererFrame != exclude) {
             interferers.push_back(interferer);
         }
     }
     // check once before applying analogModels
     if (powerLevelSumAtFrequencyIndex(interferers, freqIndex) < threshold) {
         return true;
     }
     // start applying analogue models
     auto analogueModelCount = interfererFrames.front()->getSignal().getAnalogueModelList()->size();
     for (auto signalPtr : interferers) {
         ASSERT(analogueModelCount == signalPtr->getAnalogueModelList()->size());
     }
     for (size_t analogueModelIndex = 0; analogueModelIndex < analogueModelCount; ++analogueModelIndex) {
         for (auto signalPtr : interferers) {
             signalPtr->applyAnalogueModel(analogueModelIndex);
         }
         if (powerLevelSumAtFrequencyIndex(interferers, freqIndex) < threshold) {
             return true;
         }
     }
     // After all attenuation is performed, there interference is still higher than the threshold
     ASSERT(powerLevelSumAtFrequencyIndex(interferers, freqIndex) >= threshold);
     return false;
 }