Veins: veins::SignalUtils::anonymous_namespace{SignalUtils.cc} Namespace Reference
veins::SignalUtils::anonymous_namespace{SignalUtils.cc} Namespace Reference
Classes
struct greaterByReceptionEnd
Functions
Signal getMaxInterference (simtime_t start, simtime_t end, AirFrame *const referenceFrame, AirFrameVector &interfererFrames)
double powerLevelSumAtFrequencyIndex (const std::vector< Signal *> &signals, size_t freqIndex)
Function Documentation
getMaxInterference()
Signal veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::getMaxInterference (simtime_t start, simtime_t end, AirFrame *const referenceFrame, AirFrameVector & interfererFrames)
References veins::Signal::at(), veins::Signal::getDataEnd(), veins::Signal::getDataStart(), veins::Signal::getReceptionEnd(), veins::Signal::getReceptionStart(), and veins::Signal::getSpectrum().
Referenced by veins::SignalUtils::getMinSINR().
 {
     Spectrum spectrum = referenceFrame->getSignal().getSpectrum();
     Signal maxInterference(spectrum);
     Signal currentInterference(spectrum);
     std::priority_queue<Signal, std::vector<Signal>, greaterByReceptionEnd<Signal>> signalEndings;
     simtime_t currentTime = 0;
     interfererFrames.sort([](const AirFrame* x, const AirFrame* y) { return x->getSignal().getReceptionStart() < y->getSignal().getReceptionStart(); });
     for (auto& interfererFrame : interfererFrames) {
         if (interfererFrame->getTreeId() == referenceFrame->getTreeId()) continue; // skip the signal we want to compare to
         const Signal& signal = interfererFrame->getSignal();
         if (signal.getReceptionEnd() <= start || signal.getReceptionStart() > end) continue; // skip signals outside our interval of interest
         ASSERT(signal.getReceptionEnd() > start); // fail on signals ending before start of interval of interest (should be filtered out anyways)
         ASSERT(signal.getReceptionStart() <= end); // fail on signal starting aftser the interval of interest
         ASSERT(signal.getReceptionStart() >= currentTime); // assume frames are sorted by reception start time
         ASSERT(signal.getSpectrum() == spectrum);
         // fetch next signal and advance current time to its start
         signalEndings.push(signal);
         currentTime = signal.getReceptionStart();
         // abort at end time
         if (currentTime >= end) break;
         // remove signals ending before the start of the current one
         while (signalEndings.top().getReceptionEnd() <= currentTime) {
             currentInterference -= signalEndings.top();
             signalEndings.pop();
         }
         // add curent signal to current total interference
         currentInterference += signal;
         // update maximum observed interference
         for (uint16_t spectrumIndex = signal.getDataStart(); spectrumIndex < signal.getDataEnd(); spectrumIndex++) {
             maxInterference.at(spectrumIndex) = std::max(currentInterference.at(spectrumIndex), maxInterference.at(spectrumIndex));
         }
     }
     return maxInterference;
 }
powerLevelSumAtFrequencyIndex()
double veins::SignalUtils::anonymous_namespace{SignalUtils.cc}::powerLevelSumAtFrequencyIndex (const std::vector< Signal *> & signals, size_t freqIndex)
Referenced by veins::SignalUtils::isChannelPowerBelowThreshold().
 {
     double powerLevelSum = 0;
     for (auto signalPtr : signals) {
         powerLevelSum += signalPtr->at(freqIndex);
     }
     return powerLevelSum;
 }