Veins: veins::TimerSpecification Struct Reference
veins::TimerSpecification Struct Reference
A class which specifies a Timer.
#include <TimerManager.h>
Public Member Functions
TimerSpecification (std::function< void()> callback)
Create a new TimerSpecification.
TimerSpecification & interval (omnetpp::simtime_t interval)
Set the period between two timer occurences.
TimerSpecification & repetitions (size_t n)
Set the number of repetitions.
TimerSpecification & relativeStart (omnetpp::simtime_t start)
Set the timer's start time.
TimerSpecification & absoluteStart (omnetpp::simtime_t start)
Set the timer's start time.
TimerSpecification & relativeEnd (omnetpp::simtime_t end)
Set the timer's end time.
TimerSpecification & absoluteEnd (omnetpp::simtime_t end)
Set the timer's end time.
TimerSpecification & openEnd ()
Set the timer to be open ended.
TimerSpecification & oneshotIn (omnetpp::simtime_t in)
Set the timer to execute once in a given time.
TimerSpecification & oneshotAt (omnetpp::simtime_t at)
Set the timer to execute once at a given time.
Private Types
enum StartMode { StartMode::relative, StartMode::absolute, StartMode::immediate }
enum EndMode { EndMode::relative, EndMode::absolute, EndMode::repetition, EndMode::open }
Private Member Functions
void finalize ()
Finalizes this instance such that its values are independent of current simulation time.
bool valid () const
Checks validity of this specification, i.e., whether all necessary information is set.
bool validOccurence (omnetpp::simtime_t time) const
Check that the given time is a valid occurence for this timer.
Private Attributes
friend TimerManager
StartMode start_mode_
Interpretation of start time._.
omnetpp::simtime_t start_
Time of the Timer's first occurence. Interpretation depends on start_mode_.
EndMode end_mode_
Interpretation of end time._.
unsigned end_count_
Number of repetitions of the timer. Only valid when end_mode_ == repetition.
omnetpp::simtime_t end_time_
Last possible occurence of the timer. Only valid when end_mode_ != repetition.
omnetpp::simtime_t period_
Time between events.
std::function< void()> callback_
The function to be called when the Timer is triggered.
Detailed Description
A class which specifies a Timer.
This includes timing information as well as its callback.
Member Enumeration Documentation
EndMode
enum veins::TimerSpecification::EndMode strong private
Enumerator
relative
absolute
repetition
open
{
         relative,
         absolute,
         repetition,
         open
     };
StartMode
enum veins::TimerSpecification::StartMode strong private
Enumerator
relative
absolute
immediate
{
         relative,
         absolute,
         immediate
     };
Constructor & Destructor Documentation
TimerSpecification()
TimerSpecification::TimerSpecification (std::function< void()> callback)
Create a new TimerSpecification.
The created timer is invalid, an interval is missing for it to be usable. By default, the timer starts running immediately and triggers first after the first time after the interval. After that, it will continue to run until the simulation ends, calling the callback after the interval has elapsed. In order to create a timer, this needs to be passed to TimerManager::create.
Parameters
callback The callback which is executed when the timer is triggered.
See also
TimerManager
     : start_mode_(StartMode::immediate)
     , end_mode_(EndMode::open)
     , period_(-1)
     , callback_(callback)
 {
 }
Member Function Documentation
absoluteEnd()
TimerSpecification & TimerSpecification::absoluteEnd (omnetpp::simtime_t end)
Set the timer's end time.
Any previously set end time will be overwritten.
Parameters
end The absolute end time. The latest possible occurence is at this time. Values before the current start time will prevent any executions.
References absolute, end_mode_, and end_time_.
 {
     end_mode_ = EndMode::absolute;
     end_time_ = end;
     return *this;
 }
absoluteStart()
TimerSpecification & TimerSpecification::absoluteStart (omnetpp::simtime_t start)
Set the timer's start time.
Any previously set start time will be overwritten.
Parameters
start The absolute start time. The first occurence will be exactly at this time. Passing a value earlier than the current simtime will result in an error.
Note
You cannot use this in conjunction with repetition().
References absolute, start_, and start_mode_.
Referenced by oneshotAt().
 {
     start_mode_ = StartMode::absolute;
     start_ = start;
     return *this;
 }
finalize()
void TimerSpecification::finalize () private
Finalizes this instance such that its values are independent of current simulation time.
After calling this function, start_mode_ is guaranteed to be StartMode::absolute and end_mode_ to be EndMode::absolute or EndMode::open.
References absolute, end_count_, end_mode_, end_time_, immediate, open, period_, relative, repetition, start_, and start_mode_.
Referenced by veins::TimerManager::create().
 {
     switch (start_mode_) {
     case StartMode::relative:
         start_ += simTime();
         start_mode_ = StartMode::absolute;
         break;
     case StartMode::absolute:
         break;
     case StartMode::immediate:
         start_ = simTime() + period_;
         break;
     }
     switch (end_mode_) {
     case EndMode::relative:
         end_time_ += simTime();
         end_mode_ = EndMode::absolute;
         break;
     case EndMode::absolute:
         break;
     case EndMode::repetition:
         end_time_ = start_ + ((end_count_ - 1) * period_);
         end_mode_ = EndMode::absolute;
         break;
     case EndMode::open:
         break;
     }
 }
interval()
TimerSpecification & TimerSpecification::interval (omnetpp::simtime_t interval)
Set the period between two timer occurences.
References period_.
Referenced by oneshotAt(), and oneshotIn().
 {
     ASSERT(interval > 0);
     period_ = interval;
     return *this;
 }
oneshotAt()
TimerSpecification & TimerSpecification::oneshotAt (omnetpp::simtime_t at)
Set the timer to execute once at a given time.
Any previously set start time, end time, and interval will be overwritten.
References absoluteStart(), interval(), and repetitions().
 {
     return this->absoluteStart(at).interval(1).repetitions(1);
 }
oneshotIn()
TimerSpecification & TimerSpecification::oneshotIn (omnetpp::simtime_t in)
Set the timer to execute once in a given time.
Any previously set start time, end time, and interval will be overwritten.
References interval(), relativeStart(), and repetitions().
 {
     return this->relativeStart(in).interval(1).repetitions(1);
 }
openEnd()
TimerSpecification & TimerSpecification::openEnd ()
Set the timer to be open ended.
Any previously set end time will be overwritten.
References end_mode_, and open.
 {
     end_mode_ = EndMode::open;
     return *this;
 }
relativeEnd()
TimerSpecification & TimerSpecification::relativeEnd (omnetpp::simtime_t end)
Set the timer's end time.
Any previously set end time will be overwritten.
Parameters
end Time after which this timer will no longer be executed, relative to the current simulation time. E.g., passing simtime_t(1, SIMTIME_S) will stop the execution of the time after one second has passed.
References end_mode_, end_time_, and relative.
 {
     end_mode_ = EndMode::relative;
     end_time_ = end;
     return *this;
 }
relativeStart()
TimerSpecification & TimerSpecification::relativeStart (omnetpp::simtime_t start)
Set the timer's start time.
Any previously set start time will be overwritten.
Parameters
start Time of first execution relative to the current simulation time. E.g., passing simtime_t(1, SIMTIME_S) will execute the timer in one second.
Note
You cannot use this in conjunction with repetition().
References relative, start_, and start_mode_.
Referenced by oneshotIn().
 {
     start_mode_ = StartMode::relative;
     start_ = start;
     return *this;
 }
repetitions()
TimerSpecification & TimerSpecification::repetitions (size_t n)
Set the number of repetitions.
Note
You cannot use both this and absoluteEnd or relativeEnd.
References end_count_, end_mode_, and repetition.
Referenced by oneshotAt(), and oneshotIn().
 {
     end_mode_ = EndMode::repetition;
     end_count_ = n;
     return *this;
 }
valid()
bool veins::TimerSpecification::valid () const inline private
Checks validity of this specification, i.e., whether all necessary information is set.
Referenced by veins::TimerManager::create().
     {
         return period_ != -1;
     }
validOccurence()
bool TimerSpecification::validOccurence (omnetpp::simtime_t time) const private
Check that the given time is a valid occurence for this timer.
References end_mode_, end_time_, open, period_, and start_.
 {
     const bool afterStart = time >= start_;
     const bool beforeEnd = time <= end_time_;
     const bool atPeriod = omnetpp::fmod(time - start_, period_) == 0;
     return afterStart && (beforeEnd || end_mode_ == EndMode::open) && atPeriod;
 }
Member Data Documentation
callback_
std::function<void()> veins::TimerSpecification::callback_ private
The function to be called when the Timer is triggered.
end_count_
unsigned veins::TimerSpecification::end_count_ private
Number of repetitions of the timer. Only valid when end_mode_ == repetition.
Referenced by finalize(), and repetitions().
end_mode_
EndMode veins::TimerSpecification::end_mode_ private
Interpretation of end time._.
Referenced by absoluteEnd(), finalize(), openEnd(), relativeEnd(), repetitions(), and validOccurence().
end_time_
omnetpp::simtime_t veins::TimerSpecification::end_time_ private
Last possible occurence of the timer. Only valid when end_mode_ != repetition.
Referenced by absoluteEnd(), finalize(), relativeEnd(), and validOccurence().
period_
omnetpp::simtime_t veins::TimerSpecification::period_ private
Time between events.
Referenced by finalize(), interval(), and validOccurence().
start_
omnetpp::simtime_t veins::TimerSpecification::start_ private
Time of the Timer's first occurence. Interpretation depends on start_mode_.
Referenced by absoluteStart(), finalize(), relativeStart(), and validOccurence().
start_mode_
StartMode veins::TimerSpecification::start_mode_ private
Interpretation of start time._.
Referenced by absoluteStart(), finalize(), and relativeStart().
TimerManager
friend veins::TimerSpecification::TimerManager private
The documentation for this struct was generated from the following files:
TimerManager.h
TimerManager.cc