//
// Generated file, do not edit! Created by nedtool 5.5 from veins/modules/messages/ReportMessage.msg.
//

#ifndef __VEINS_REPORTMESSAGE_M_H
#define __VEINS_REPORTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/base/utils/Coord.h"
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/messages/ReportMessage.msg:35</tt> by nedtool.
 * <pre>
 * packet ReportMessage extends BaseFrame1609_4
 * {
 *     Coord senderPos;
 *     LAddress::L2Type senderAddress = -1;
 *     int senderType;
 * }
 * </pre>
 */
class VEINS_API ReportMessage : public ::veins::BaseFrame1609_4
{
  protected:
    Coord senderPos;
    LAddress::L2Type senderAddress;
    int senderType;

  private:
    void copy(const ReportMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReportMessage&);

  public:
    ReportMessage(const char *name=nullptr, short kind=0);
    ReportMessage(const ReportMessage& other);
    virtual ~ReportMessage();
    ReportMessage& operator=(const ReportMessage& other);
    virtual ReportMessage *dup() const override {return new ReportMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual Coord& getSenderPos();
    virtual const Coord& getSenderPos() const {return const_cast<ReportMessage*>(this)->getSenderPos();}
    virtual void setSenderPos(const Coord& senderPos);
    virtual LAddress::L2Type& getSenderAddress();
    virtual const LAddress::L2Type& getSenderAddress() const {return const_cast<ReportMessage*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
    virtual int getSenderType() const;
    virtual void setSenderType(int senderType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ReportMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ReportMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_REPORTMESSAGE_M_H

